"""Guarded installer for step 2 (sky art, night sky change, clouds) in Space Racers v3.
Before state: ../backup/after.json (config after step 1) and before/*.lua (live sources). Modes: AUDIT, APPLY, ROLLBACK."""
import json
from pathlib import Path
HERE = Path(__file__).resolve().parent
state = json.loads((HERE.parent / 'backup/after.json').read_text(encoding='utf8'))
spec = json.loads((HERE / 'spec.json').read_text(encoding='utf8'))
assert state['place_id'] == 93959280828322 and state['mode'] == 'Edit'
CFG = ['ReplicatedStorage', 'Config', 'World', 'Lighting']
SKIES = ['ReplicatedStorage', 'Assets', 'World', 'Skies']
def child(node, name):
    found = [c for c in node['children'] if c['name'] == name]
    assert len(found) == 1, name
    return found[0]
def lua(v):
    if v is None: return 'nil'
    if type(v) is bool: return str(v).lower()
    if type(v) in (int, float): return repr(v)
    if isinstance(v, str):
        return '"' + v.replace('\\', '\\\\').replace('"', '\\"').replace('\r', '\\r').replace('\n', '\\n').replace('\t', '\\t') + '"'
    if isinstance(v, list): return '{' + ','.join(lua(x) for x in v) + '}'
    if v.get('Type') == 'Color3': return 'Color3.new(%r,%r,%r)' % (v['R'], v['G'], v['B'])
    if v.get('Type') == 'Vector3': return 'Vector3.new(%r,%r,%r)' % (v['X'], v['Y'], v['Z'])
    return '{' + ','.join('[%s]=%s' % (lua(k), lua(x)) for k, x in v.items()) + '}'
def colour(rgb): return dict(Type='Color3', R=rgb[0] / 255, G=rgb[1] / 255, B=rgb[2] / 255)
ops = []
# 1. sources first, so the new config is never read by old code that would reject it
paths = json.loads((HERE / 'before/paths.json').read_text())
for path in paths:
    name = path.split('.')[-1]
    before = (HERE / 'before' / (name + '.lua')).read_bytes().decode('utf8')
    after = (HERE / 'after' / (name + '.lua')).read_bytes().decode('utf8')
    assert before != after and len(after.encode()) < 150000
    ops.append(dict(kind='source', path=path.split('.'), class_name='ModuleScript', before=before, after=after))
# 2. sky templates
existing = {s['name'] for s in state['skies']}
for name, sky in spec['skies'].items():
    assert name not in existing
    props = {('Skybox' + f): 'rbxassetid://' + i for f, i in sky['faces'].items()}
    for key in ('SunTextureId', 'MoonTextureId', 'SunAngularSize', 'MoonAngularSize', 'StarCount'): props[key] = sky[key]
    props['CelestialBodiesShown'] = True; props['SkyboxOrientation'] = dict(Type='Vector3', X=0, Y=0, Z=0)
    ops.append(dict(kind='tree', path=SKIES + [name], class_name='Sky', after=dict(name=name, class_name='Sky', attributes={}, properties=props, children=[])))
# 3. Clouds section in every look
presets = child(state['config'], 'ContinuousPresets')
assert {c['name'] for c in presets['children']} == set(spec['clouds'])
for look, values in spec['clouds'].items():
    assert not [c for c in child(presets, look)['children'] if c['name'] == 'Clouds']
    attrs = dict(Enabled=True, Cover=values['Cover'], Density=values['Density'], Color=colour(values['Color']))
    ops.append(dict(kind='tree', path=CFG + ['ContinuousPresets', look, 'Clouds'], class_name='Folder', after=dict(name='Clouds', class_name='Folder', attributes=attrs, properties={}, children=[])))
# 4. look values changed again for the new sky
for look, sections in spec['looks'].items():
    for section, values in sections.items():
        old = child(child(presets, look), section)['attributes']
        for key, value in values.items():
            prev = old[key]
            after = colour(value) if isinstance(value, list) else value
            assert type(prev) == type(after) or (type(prev) in (int, float) and type(after) in (int, float)), (look, section, key)
            if json.dumps(prev, sort_keys=True) != json.dumps(after, sort_keys=True):
                ops.append(dict(kind='attribute', path=CFG + ['ContinuousPresets', look, section], class_name='Folder', key=key, before=prev, after=after))
# 5. cycle settings last: these switch the new behaviour on
current = state['config']['attributes']
for key, value in spec['config'].items():
    prev = current.get(key)
    assert prev != value
    ops.append(dict(kind='attribute', path=CFG, class_name='Folder', key=key, before=prev, after=value))
bundle = dict(placeId=state['place_id'], beforeCapture='scripts/lighting_realism/backup/after.json @ ' + state['taken_utc'], operations=ops, guards=[])
engine = (HERE.parent.parent / 'continuous_lighting/installer_engine.lua').read_text(encoding='utf8')
text = '-- Generated by scripts/lighting_realism/step2/build.py. ROLLBACK restores the state after step 1.\nlocal bundle=' + lua(bundle) + '\nlocal run=(function()\n' + engine + '\nend)()\nreturn function(mode) assert(mode=="AUDIT" or mode=="APPLY" or mode=="ROLLBACK","Use AUDIT, APPLY or ROLLBACK") return run(mode) end\n'
(HERE / 'install.lua').write_text(text, encoding='utf8', newline='\n')
print(json.dumps(dict(operations=len(ops), kinds={k: sum(1 for o in ops if o['kind'] == k) for k in ('source', 'tree', 'attribute')}, installer_bytes=len(text))))
