"""Guarded installer for step 3 (sky change at nightfall, dim moon, stylised grade, far blur) in Space Racers v3.
Before state: ../backup/after-step2.json. Attribute and property changes only. Modes: AUDIT, APPLY, ROLLBACK."""
import json
from pathlib import Path
HERE = Path(__file__).resolve().parent
state = json.loads((HERE.parent / 'backup/after-step2.json').read_text(encoding='utf8'))
spec = json.loads((HERE / 'spec.json').read_text(encoding='utf8'))
assert state['place_id'] == 93959280828322 and state['mode'] == 'Edit'
CFG = ['ReplicatedStorage', 'Config', 'World', 'Lighting']
SKIES = ['ReplicatedStorage', 'Assets', 'World', 'Skies']
def child(node, name):
    found = [c for c in node['children'] if c['name'] == name]
    assert len(found) == 1, name
    return found[0]
def lua(v):
    if v is None: return 'nil'
    if type(v) is bool: return str(v).lower()
    if type(v) in (int, float): return repr(v)
    if isinstance(v, str): return json.dumps(v)
    if isinstance(v, list): return '{' + ','.join(lua(x) for x in v) + '}'
    if v.get('Type') == 'Color3': return 'Color3.new(%r,%r,%r)' % (v['R'], v['G'], v['B'])
    return '{' + ','.join('[%s]=%s' % (lua(k), lua(x)) for k, x in v.items()) + '}'
def same(a, b):
    if type(a) in (int, float) and type(b) in (int, float) and type(a) is not bool and type(b) is not bool: return abs(a - b) < 1e-7
    return type(a) == type(b) and a == b
ops, summary = [], {}
def attribute(path, old, key, value, label):
    assert key in old, label
    prev = old[key]
    if isinstance(value, list): value = dict(Type='Color3', R=value[0] / 255, G=value[1] / 255, B=value[2] / 255)
    assert (type(prev) is bool) == (type(value) is bool) and isinstance(prev, dict) == isinstance(value, dict), label
    if not same(prev, value):
        ops.append(dict(kind='attribute', path=path, class_name='Folder', key=key, before=prev, after=value)); summary[label] = [prev, value]
presets = child(state['config'], 'ContinuousPresets'); looks = child(state['config'], 'ContinuousLooks')
for look, sections in spec['looks'].items():
    for section, values in sections.items():
        old = child(child(presets, look), section)['attributes']
        for key, value in values.items(): attribute(CFG + ['ContinuousPresets', look, section], old, key, value, '%s.%s.%s' % (look, section, key))
for name, values in spec['milestones'].items():
    old = child(looks, name)['attributes']
    for key, value in values.items(): attribute(CFG + ['ContinuousLooks', name], old, key, value, 'milestone.%s.%s' % (name, key))
for name, props in spec['skies'].items():
    sky = [s for s in state['skies'] if s['name'] == name]; assert len(sky) == 1
    for key, value in props.items():
        prev = sky[0]['properties'][key]
        if not same(prev, value):
            ops.append(dict(kind='property', path=SKIES + [name], class_name='Sky', key=key, before=prev, after=value)); summary['sky.%s.%s' % (name, key)] = [prev, value]
for key, value in spec['config'].items(): attribute(CFG, state['config']['attributes'], key, value, 'config.' + key)
bundle = dict(placeId=state['place_id'], beforeCapture='scripts/lighting_realism/backup/after-step2.json @ ' + state['taken_utc'], operations=ops, guards=[])
engine = (HERE.parent.parent / 'continuous_lighting/installer_engine.lua').read_text(encoding='utf8')
text = '-- Generated by scripts/lighting_realism/step3/build.py. ROLLBACK restores the state after step 2.\nlocal bundle=' + lua(bundle) + '\nlocal run=(function()\n' + engine + '\nend)()\nreturn function(mode) assert(mode=="AUDIT" or mode=="APPLY" or mode=="ROLLBACK","Use AUDIT, APPLY or ROLLBACK") return run(mode) end\n'
(HERE / 'install.lua').write_text(text, encoding='utf8', newline='\n')
(HERE / 'changes.json').write_text(json.dumps(summary, indent=1) + '\n', encoding='utf8', newline='\n')
print(json.dumps(dict(operations=len(ops), installer_bytes=len(text))))
