-- Owns the generated sprite geometry of the uploaded Pulse images (sheet cells, digit metrics, ring angles, touch sizes); holds data only and no asset id.
-- Pulse UI (phase2). ReplicatedStorage.Modules.Game.UIPulse.Kit.Sprites. Requires: none.
-- GENERATED by gen_sprites.py from scripts/ui_restyle/assets. Never edit by hand. Numbers are source-image pixels.
local Sprites = {}

-- UI glyph sheet: {column, row} in cells of Cell px, zero-based.
Sprites.Icons = table.freeze({
	Asset = "IconSheet",
	Cell = 128,
	Glyphs = table.freeze({
		["garage"] = table.freeze({ 0, 0 }),
		["dealership"] = table.freeze({ 1, 0 }),
		["customise"] = table.freeze({ 2, 0 }),
		["race_flag"] = table.freeze({ 3, 0 }),
		["map"] = table.freeze({ 4, 0 }),
		["settings_cog"] = table.freeze({ 5, 0 }),
		["controls"] = table.freeze({ 6, 0 }),
		["gamepad"] = table.freeze({ 7, 0 }),
		["car"] = table.freeze({ 0, 1 }),
		["passenger"] = table.freeze({ 1, 1 }),
		["players"] = table.freeze({ 2, 1 }),
		["taxi"] = table.freeze({ 3, 1 }),
		["parcel"] = table.freeze({ 4, 1 }),
		["exit"] = table.freeze({ 5, 1 }),
		["back"] = table.freeze({ 6, 1 }),
		["steering_wheel"] = table.freeze({ 7, 1 }),
		["trophy"] = table.freeze({ 0, 2 }),
		["medal"] = table.freeze({ 1, 2 }),
		["star"] = table.freeze({ 2, 2 }),
		["coin"] = table.freeze({ 3, 2 }),
		["timer"] = table.freeze({ 4, 2 }),
		["loop"] = table.freeze({ 5, 2 }),
		["laps"] = table.freeze({ 6, 2 }),
		["checkpoints"] = table.freeze({ 7, 2 }),
		["pin"] = table.freeze({ 0, 3 }),
		["set_route"] = table.freeze({ 1, 3 }),
		["route"] = table.freeze({ 2, 3 }),
		["north"] = table.freeze({ 3, 3 }),
		["boost"] = table.freeze({ 4, 3 }),
		["upgrade"] = table.freeze({ 5, 3 }),
		["lock"] = table.freeze({ 6, 3 }),
		["tick"] = table.freeze({ 7, 3 }),
		["chevron_left"] = table.freeze({ 0, 4 }),
		["chevron_right"] = table.freeze({ 1, 4 }),
		["chevron_up"] = table.freeze({ 2, 4 }),
		["chevron_down"] = table.freeze({ 3, 4 }),
		["plus"] = table.freeze({ 4, 4 }),
		["minus"] = table.freeze({ 5, 4 }),
		["close"] = table.freeze({ 6, 4 }),
		["title_mark"] = table.freeze({ 7, 4 }),
		["warning"] = table.freeze({ 0, 5 }),
		["info"] = table.freeze({ 1, 5 }),
		["duel"] = table.freeze({ 2, 5 }),
		["paint"] = table.freeze({ 3, 5 }),
		["keycap_blank"] = table.freeze({ 4, 5 }),
		["dpad"] = table.freeze({ 5, 5 }),
		["pad_select"] = table.freeze({ 6, 5 }),
		["pad_start"] = table.freeze({ 7, 5 }),
		["pad_a"] = table.freeze({ 0, 6 }),
		["pad_b"] = table.freeze({ 1, 6 }),
		["pad_x"] = table.freeze({ 2, 6 }),
		["pad_y"] = table.freeze({ 3, 6 }),
		["pad_lb"] = table.freeze({ 4, 6 }),
		["pad_rb"] = table.freeze({ 5, 6 }),
		["pad_lt"] = table.freeze({ 6, 6 }),
		["pad_rt"] = table.freeze({ 7, 6 }),
		["drift"] = table.freeze({ 0, 7 }),
		["gauge"] = table.freeze({ 1, 7 }),
	}),
})

-- Map marker sheet. Pin glyphs anchor at (0.5, PinTipY); the rest at the centre.
Sprites.MapIcons = table.freeze({
	Asset = "MapIconSheet",
	Cell = 128,
	PinTipY = 0.921875,
	Pins = table.freeze({
		Waypoint = true,
		TaxiDrop = true,
		CourierDrop = true,
	}),
	Glyphs = table.freeze({
		["Race"] = table.freeze({ 0, 0 }),
		["TimeTrial"] = table.freeze({ 1, 0 }),
		["Duel"] = table.freeze({ 2, 0 }),
		["Job"] = table.freeze({ 3, 0 }),
		["TaxiFare"] = table.freeze({ 0, 1 }),
		["CourierPickup"] = table.freeze({ 1, 1 }),
		["TaxiDrop"] = table.freeze({ 2, 1 }),
		["CourierDrop"] = table.freeze({ 3, 1 }),
		["Customisation"] = table.freeze({ 0, 2 }),
		["Dealership"] = table.freeze({ 1, 2 }),
		["Garage"] = table.freeze({ 2, 2 }),
		["Waypoint"] = table.freeze({ 3, 2 }),
		["Player"] = table.freeze({ 0, 3 }),
		["OtherPlayer"] = table.freeze({ 1, 3 }),
	}),
})

-- Digit sheets by cell height: glyph = {x, y, advance, originX}.
Sprites.Digits = table.freeze({
	[256] = table.freeze({
		Asset = "Digits256",
		Cell = table.freeze({ 148, 256 }),
		Cap = 185,
		Baseline = 218,
		Pitch = 130,
		PitchTight = 117,
		Glyphs = table.freeze({
			["0"] = table.freeze({ 0, 0, 117, 16 }),
			["1"] = table.freeze({ 148, 0, 75, 36 }),
			["2"] = table.freeze({ 296, 0, 116, 16 }),
			["3"] = table.freeze({ 444, 0, 114, 17 }),
			["4"] = table.freeze({ 592, 0, 130, 9 }),
			["5"] = table.freeze({ 740, 0, 115, 16 }),
			["6"] = table.freeze({ 0, 256, 115, 16 }),
			["7"] = table.freeze({ 148, 256, 108, 20 }),
			["8"] = table.freeze({ 296, 256, 114, 17 }),
			["9"] = table.freeze({ 444, 256, 114, 17 }),
		}),
	}),
	[128] = table.freeze({
		Asset = "Digits128",
		Cell = table.freeze({ 80, 128 }),
		Cap = 92,
		Baseline = 108,
		Pitch = 65,
		PitchTight = 58,
		Glyphs = table.freeze({
			["0"] = table.freeze({ 0, 0, 58, 11 }),
			["1"] = table.freeze({ 80, 0, 38, 21 }),
			["2"] = table.freeze({ 160, 0, 58, 11 }),
			["3"] = table.freeze({ 240, 0, 57, 12 }),
			["4"] = table.freeze({ 320, 0, 65, 8 }),
			["5"] = table.freeze({ 400, 0, 58, 11 }),
			["6"] = table.freeze({ 480, 0, 58, 11 }),
			["7"] = table.freeze({ 560, 0, 54, 13 }),
			["8"] = table.freeze({ 640, 0, 57, 12 }),
			["9"] = table.freeze({ 720, 0, 57, 12 }),
		}),
	}),
})

-- Punctuation and unit words by cell height: glyph = {x, y, w, h, advance, originX}.
Sprites.Punct = table.freeze({
	[256] = table.freeze({
		Asset = "DigitsPunct",
		Glyphs = table.freeze({
			[":"] = table.freeze({ 0, 0, 84, 256, 76, 4 }),
			["."] = table.freeze({ 84, 0, 68, 256, 60, 4 }),
			[","] = table.freeze({ 152, 0, 70, 256, 57, 6 }),
			["$"] = table.freeze({ 222, 0, 138, 256, 116, 11 }),
			["%"] = table.freeze({ 360, 0, 204, 256, 195, 4 }),
			["+"] = table.freeze({ 564, 0, 122, 256, 112, 5 }),
			["-"] = table.freeze({ 686, 0, 98, 256, 86, 6 }),
			["/"] = table.freeze({ 784, 0, 142, 256, 114, 14 }),
			["x"] = table.freeze({ 0, 256, 144, 256, 118, 13 }),
			["K"] = table.freeze({ 144, 256, 164, 256, 129, 17 }),
			["M"] = table.freeze({ 308, 256, 172, 256, 143, 14 }),
			["MPH"] = table.freeze({ 480, 256, 414, 256, 388, 13 }),
			["KM/H"] = table.freeze({ 0, 512, 536, 256, 510, 13 }),
			["XP"] = table.freeze({ 536, 512, 270, 256, 247, 11 }),
		}),
	}),
	[128] = table.freeze({
		Asset = "DigitsPunct",
		Glyphs = table.freeze({
			[":"] = table.freeze({ 0, 768, 46, 128, 38, 4 }),
			["."] = table.freeze({ 46, 768, 38, 128, 30, 4 }),
			[","] = table.freeze({ 84, 768, 40, 128, 29, 5 }),
			["$"] = table.freeze({ 124, 768, 74, 128, 58, 8 }),
			["%"] = table.freeze({ 198, 768, 106, 128, 97, 4 }),
			["+"] = table.freeze({ 304, 768, 66, 128, 56, 5 }),
			["-"] = table.freeze({ 370, 768, 54, 128, 43, 5 }),
			["/"] = table.freeze({ 424, 768, 76, 128, 57, 9 }),
			["x"] = table.freeze({ 500, 768, 78, 128, 59, 9 }),
			["K"] = table.freeze({ 578, 768, 88, 128, 65, 11 }),
			["M"] = table.freeze({ 666, 768, 92, 128, 71, 10 }),
			["MPH"] = table.freeze({ 758, 768, 212, 128, 194, 9 }),
			["KM/H"] = table.freeze({ 0, 896, 274, 128, 255, 9 }),
			["XP"] = table.freeze({ 274, 896, 142, 128, 123, 9 }),
		}),
	}),
})

-- Angles are degrees clockwise from +X in screen space (0 = 3 o'clock, 90 = 6, 180 = 9, 270 = 12).
Sprites.Rings = table.freeze({
	Size = 512,
	Gauge = table.freeze({
		StartDeg = 135,
		SweepDeg = 270,
		ArcRadius = 210,
		BoostRadius = 184,
		TipFraction = 0.09,
	}),
	Minimap = table.freeze({
		FrameScale = 512 / 480,
	}),
	Rank = table.freeze({
		FrameScale = 1.099 * 512 / 480,
		StartDeg = 180,
		SweepRegular = 90,
		CompactFromDeg = 165,
		CompactToDeg = 285,
	}),
	TitleSlash = table.freeze({
		Size = table.freeze({ 160, 192 }),
		Design = table.freeze({ 53.3, 64 }),
	}),
})

-- Touch controls: asset keys and sizes in dp (ctx.Dp).
Sprites.Touch = table.freeze({
	Accelerate = table.freeze({
		Idle = "TouchAccelerate",
		Pressed = "TouchAcceleratePressed",
		PlateDp = table.freeze({ 72, 100 }),
		FrameDp = table.freeze({ 110, 110 }),
		HitDp = table.freeze({ 96, 112 }),
	}),
	Brake = table.freeze({
		Idle = "TouchBrake",
		Pressed = "TouchBrakePressed",
		PlateDp = table.freeze({ 76, 64 }),
		FrameDp = table.freeze({ 86, 86 }),
		HitDp = table.freeze({ 80, 64 }),
	}),
	Turn = table.freeze({
		Idle = "TouchTurn",
		Pressed = "TouchTurnPressed",
		PlateDp = table.freeze({ 52, 52 }),
		FrameDp = table.freeze({ 62, 62 }),
		HitDp = table.freeze({ 52, 60 }),
	}),
	Drift = table.freeze({
		Idle = "TouchDrift",
		Pressed = "TouchDriftPressed",
		PlateDp = table.freeze({ 52, 52 }),
		FrameDp = table.freeze({ 62, 62 }),
		HitDp = table.freeze({ 52, 52 }),
	}),
	Boost = table.freeze({
		Idle = "TouchBoost",
		Pressed = "TouchBoostPressed",
		PlateDp = table.freeze({ 48, 48 }),
		FrameDp = table.freeze({ 58, 58 }),
		HitDp = table.freeze({ 52, 52 }),
	}),
})

Sprites.Source = table.freeze({
	Generator = "scripts/ui_restyle/phase2/kit/k1/gen_sprites.py",
	Inputs = table.freeze({
		["digits.json"] = "sha256:cfdc8351f131e2fb6a46e5785ee7a812496e80a04201c3a1dd0691c9e93b3bdd",
		["icons.json"] = "sha256:64e78d2312a2697d9ecfa58e68381c16c954d2bcf1215ff883e7b75639fd0c8a",
		["map_icons.json"] = "sha256:0251ee2e1ede79956c21382071345ab4cd21c5e4ada89033586ebb26ad48f0ce",
		["rings.json"] = "sha256:500633cad3ad551a8006fa8cbf1e62659c129d3b8ab5efc16890085ef7eb44a1",
		["static_geometry.json"] = "sha256:5e8299357831f9c01befc78f732b9fa139e32fc1088107062fc48b899d2ac6a8",
		["touch.json"] = "sha256:780e768b00428dfe2ccd23efb85583f22bddcb2e304524e350cd5163e8d74c74",
		["uploaded_assets.json"] = "sha256:936f1be433bc23aa31b082ea77ec6da0cc541855ee1c71bf49793cd9e9e6e8d2",
	}),
})

return table.freeze(Sprites)
