-- Phase 1 pure library tests. Invoked with a table of library sources; creates only unparented instances.
return function(sources)
	local results, failures = {}, 0
	local function load(name)
		local fn, err = loadstring(sources[name]); assert(fn, name .. ": " .. tostring(err)); return fn()
	end
	local function test(name, body)
		local ok, err = pcall(body)
		table.insert(results, (ok and "PASS " or "FAIL ") .. name .. (ok and "" or (": " .. tostring(err))))
		if not ok then failures += 1 end
	end
	local Signal, Scope, Config, Tags = load("Signal"), load("ConnectionScope"), load("ConfigReader"), load("Tags")

	test("signal fires handlers with args", function()
		local s, got = Signal.new(), {}
		s:Connect(function(a, b) table.insert(got, a + b) end)
		s:Fire(2, 3); task.wait()
		assert(got[1] == 5)
	end)
	test("signal isolates failing handler", function()
		local s, ran = Signal.new(), false
		s:Connect(function() error("boom") end)
		s:Connect(function() ran = true end)
		s:Fire(); task.wait()
		assert(ran)
	end)
	test("signal once/disconnect/destroy", function()
		local s, count = Signal.new(), 0
		s:Once(function() count += 1 end)
		local c = s:Connect(function() count += 10 end)
		s:Fire(); task.wait(); c:Disconnect(); s:Fire(); task.wait()
		assert(count == 11, "count " .. count)
		s:Destroy(); s:Fire(); task.wait(); assert(count == 11)
		assert(not pcall(function() s:Connect(function() end) end))
	end)
	test("signal wait returns fired values", function()
		local s = Signal.new()
		task.delay(0, function() s:Fire("x", 7) end)
		local a, b = s:Wait()
		assert(a == "x" and b == 7)
	end)

	test("scope releases all kinds in reverse, isolates failures, repeat-safe", function()
		local scope, order = Scope.new(), {}
		local folder = Instance.new("Folder")
		local bindable = Instance.new("BindableEvent")
		scope:connect(bindable.Event, function() end)
		scope:add(function() table.insert(order, "first") end)
		scope:add(function() error("cleanup failure") end)
		scope:add({ destroy = function() table.insert(order, "object") end })
		scope:add(folder)
		local thread = scope:task(function() task.wait(10) end)
		scope:destroy(); scope:destroy()
		assert(order[1] == "object" and order[2] == "first", table.concat(order, ","))
		assert(folder.Parent == nil and coroutine.status(thread) == "dead")
		assert(not pcall(function() scope:add(function() end) end))
		bindable:Destroy()
	end)

	test("config number preserves valid values and bounds", function()
		local folder = Instance.new("Folder")
		local v = Instance.new("NumberValue"); v.Name = "Speed"; v.Value = 50; v.Parent = folder
		assert(Config.Number(folder, "Speed", 1, 0, 100) == 50)
		assert(Config.Number(folder, "Missing", 7, 0, 100) == 7)
		v.Value = 500; assert(Config.Number(folder, "Speed", 1, 0, 100) == 100)
		v.Value = 0 / 0; assert(Config.Number(folder, "Speed", 3, 0, 100) == 3)
		v.Value = math.huge; assert(Config.Number(folder, "Speed", 4) == 4)
		folder:Destroy()
	end)
	test("config wrong class falls back", function()
		local folder = Instance.new("Folder")
		local s = Instance.new("StringValue"); s.Name = "Speed"; s.Parent = folder
		assert(Config.Number(folder, "Speed", 9) == 9)
		assert(Config.Color(folder, "Speed", Color3.new(1, 0, 0)) == Color3.new(1, 0, 0))
		folder:Destroy()
	end)
	test("config attributes typed and bounded", function()
		local folder = Instance.new("Folder")
		folder:SetAttribute("N", 12); folder:SetAttribute("B", true); folder:SetAttribute("S", "text"); folder:SetAttribute("Bad", 0 / 0)
		assert(Config.NumberAttribute(folder, "N", 1, 0, 10) == 10)
		assert(Config.NumberAttribute(folder, "S", 5) == 5)
		assert(Config.NumberAttribute(folder, "Bad", 6) == 6)
		assert(Config.NumberAttribute(folder, "Missing", 2) == 2)
		assert(Config.BoolAttribute(folder, "B", false) == true)
		assert(Config.BoolAttribute(folder, "S", false) == false)
		assert(Config.Attribute(folder, "S", nil) == "text")
		assert(Config.IsFinite(1) and not Config.IsFinite(0 / 0) and not Config.IsFinite("1"))
		folder:Destroy()
	end)
	test("tags api shape", function()
		assert(type(Tags.watch) == "function" and type(Tags.first) == "function")
		local w = Tags.watch("ArchitectureProgrammeUnusedTag_" .. tostring(os.clock()), function() end)
		w:destroy(); w:destroy()
	end)
	return { failures = failures, results = results }
end
