-- GENERATED by scripts/ui_restyle/phase2/tools/gen_routes.py for "shell". Do not edit.
-- Part 1: the Phase 1 Routes test, unchanged, run against the Phase 1 data (Compose and Resolve are the same code).
-- Part 2: the generated data tables against the ClientBase entry list, for every prefix of Routes.Families.
local phase1Test = (function()
-- Pure tests for UIPulse.Routes (API.md 5 and 13; CONTRACT E4 and E5). No yield, no instance, nothing parented.
-- The entry table below is generated from classic/contracts/_clientbase_entries.json by phase1/check_spec.py
-- (--fix-entries); check_spec.py fails when the two differ. Do not edit it by hand.
-- BEGIN ENTRIES
local ENTRY_COUNT = 46
local ENTRIES = {
	{ name = "ActivityClient", path = "ReplicatedStorage.Modules.Game.Activities.ActivityClient", dependencies = { "SharedTopNotificationUI" } },
	{ name = "LightingClient", path = "ReplicatedStorage.Modules.Game.World.LightingClient", dependencies = {} },
	{ name = "DriveSessionClient", path = "ReplicatedStorage.Modules.Game.Vehicles.DriveSessionClient", dependencies = {} },
	{ name = "AcousticsRuntimeClient", path = "ReplicatedStorage.Modules.Game.Audio.AcousticsRuntimeClient", dependencies = {} },
	{ name = "AudioRuntimeClient", path = "ReplicatedStorage.Modules.Game.Audio.AudioRuntimeClient", dependencies = {} },
	{ name = "ContextAudioRuntimeClient", path = "ReplicatedStorage.Modules.Game.Audio.ContextAudioRuntimeClient", dependencies = {} },
	{ name = "PresentationAudioRuntimeClient", path = "ReplicatedStorage.Modules.Game.Audio.PresentationAudioRuntimeClient", dependencies = {} },
	{ name = "DriveToEarnCashTelemetryClient", path = "ReplicatedStorage.Modules.Game.Development.DriveToEarnCashTelemetryClient", dependencies = {} },
	{ name = "StudioCashGrantClient", path = "ReplicatedStorage.Modules.Game.Development.StudioCashGrantClient", dependencies = {} },
	{ name = "DealershipIntroClient", path = "ReplicatedStorage.Modules.Game.Dealership.DealershipIntroClient", dependencies = { "GarageUI" } },
	{ name = "GarageEntranceClient", path = "ReplicatedStorage.Modules.Game.Dealership.GarageEntranceClient", dependencies = { "LoadingTransitionUI", "GarageUI" } },
	{ name = "GaragePreviewPresentationClient", path = "ReplicatedStorage.Modules.Game.Garage.GaragePreviewPresentationClient", dependencies = { "LightingClient" } },
	{ name = "ThrustPreviewClient", path = "ReplicatedStorage.Modules.Game.Garage.ThrustPreviewClient", dependencies = {} },
	{ name = "RaceBrowserClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceBrowserClient", dependencies = {} },
	{ name = "RaceCountdownPresentationClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceCountdownPresentationClient", dependencies = {} },
	{ name = "RaceEntryMenuClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceEntryMenuClient", dependencies = {} },
	{ name = "RaceEntryPresentationClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceEntryPresentationClient", dependencies = { "LoadingTransitionUI" } },
	{ name = "RaceLifecyclePresentationClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceLifecyclePresentationClient", dependencies = {} },
	{ name = "RaceParticipantVisibilityClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceParticipantVisibilityClient", dependencies = {} },
	{ name = "RaceQueueClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceQueueClient", dependencies = {} },
	{ name = "RaceRouteGuideClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceRouteGuideClient", dependencies = {} },
	{ name = "RaceSessionAssetsClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceSessionAssetsClient", dependencies = {} },
	{ name = "RaceSessionPresentationClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceSessionPresentationClient", dependencies = {} },
	{ name = "RaceTimeTrialResultCoachClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceTimeTrialResultCoachClient", dependencies = {} },
	{ name = "RaceTransitionClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceTransitionClient", dependencies = {} },
	{ name = "CharacterSprintClient", path = "ReplicatedStorage.Modules.Game.Vehicles.CharacterSprintClient", dependencies = {} },
	{ name = "FreeRoamParkedHoverClient", path = "ReplicatedStorage.Modules.Game.Vehicles.FreeRoamParkedHoverClient", dependencies = {} },
	{ name = "MobileDriveControlsClient", path = "ReplicatedStorage.Modules.Game.Vehicles.MobileDriveControlsClient", dependencies = {} },
	{ name = "RuntimeVFXClient", path = "ReplicatedStorage.Modules.Game.Vehicles.RuntimeVFXClient", dependencies = {} },
	{ name = "DesktopFreeRoamHudUI", path = "ReplicatedStorage.Modules.Game.UI.DesktopFreeRoamHudUI", dependencies = {} },
	{ name = "FreeRoamVehicleExitButtonClient", path = "ReplicatedStorage.Modules.Game.UI.FreeRoamVehicleExitButtonClient", dependencies = {} },
	{ name = "LoadingTransitionUI", path = "ReplicatedStorage.Modules.Game.UI.LoadingTransitionUI", dependencies = {} },
	{ name = "MobileFreeRoamHudUI", path = "ReplicatedStorage.Modules.Game.UI.MobileFreeRoamHudUI", dependencies = {} },
	{ name = "FullMapUI", path = "ReplicatedStorage.Modules.Game.UI.FullMapUI", dependencies = {} },
	{ name = "OnboardingClient", path = "ReplicatedStorage.Modules.Game.UI.OnboardingClient", dependencies = {} },
	{ name = "OwnedGarageClient", path = "ReplicatedStorage.Modules.Game.UI.OwnedGarageClient", dependencies = { "LoadingTransitionUI" } },
	{ name = "SharedTopNotificationUI", path = "ReplicatedStorage.Modules.Game.UI.SharedTopNotificationUI", dependencies = {} },
	{ name = "LODClient", path = "ReplicatedStorage.Modules.Game.World.LODClient", dependencies = {} },
	{ name = "NightLamppostLightClient", path = "ReplicatedStorage.Modules.Game.World.NightLamppostLightClient", dependencies = {} },
	{ name = "OwnedGarageEnvironmentLightingClient", path = "ReplicatedStorage.Modules.Game.World.OwnedGarageEnvironmentLightingClient", dependencies = { "LightingClient" } },
	{ name = "WindowMaterialClient", path = "ReplicatedStorage.Modules.Game.World.WindowMaterialClient", dependencies = {} },
	{ name = "GarageUI", path = "ReplicatedStorage.Modules.Game.Garage.GarageUI", dependencies = { "DriveSessionClient", "LoadingTransitionUI", "SharedTopNotificationUI" } },
	{ name = "TrailerVehicleCameraClient", path = "ReplicatedStorage.Modules.Game.Development.TrailerVehicleCameraClient", dependencies = {}, tool = "TrailerVehicleCameraEnabled" },
	{ name = "LightingPreviewClient", path = "ReplicatedStorage.Modules.Game.Development.LightingPreviewClient", dependencies = { "LightingClient" }, tool = "LightingPreviewEnabled" },
	{ name = "TrailerModeClient", path = "ReplicatedStorage.Modules.Game.Development.TrailerModeClient", dependencies = {}, tool = "TrailerModeEnabled" },
	{ name = "TrailerShotClient", path = "ReplicatedStorage.Modules.Game.Development.TrailerShotClient", dependencies = {}, tool = "TrailerShotEnabled" },
}
-- END ENTRIES

local TOAST_PATH = "ReplicatedStorage.Modules.Game.UIPulse.Toasts.ToastClient"
local GALLERY_PATH = "ReplicatedStorage.Modules.Game.UIPulse.Dev.Gallery"

-- A copy of Core.ClientLifecycle.validate (classic source lines 3 to 16).
local function lifecycleValidate(entries)
	local index, visiting, visited = {}, {}, {}
	for _, entry in ipairs(entries) do
		assert(not index[entry.name], "Duplicate client " .. entry.name)
		index[entry.name] = entry
	end
	local function visit(name)
		assert(index[name], "Missing dependency " .. name)
		assert(not visiting[name], "Dependency cycle at " .. name)
		if visited[name] then
			return
		end
		visiting[name] = true
		for _, dependency in ipairs(index[name].dependencies or {}) do
			visit(dependency)
		end
		visiting[name] = nil
		visited[name] = true
	end
	for name in pairs(index) do
		visit(name)
	end
	return index
end

return function(M, env)
	local results = {}
	local function case(name, body)
		local ok, detail = pcall(body)
		results[#results + 1] = { name = name, ok = ok, detail = (not ok) and tostring(detail) or nil }
	end
	local function expect(condition, message)
		if not condition then
			error(message or "expectation failed", 0)
		end
	end

	-- A fresh, independent copy of the recorded entry list for each case.
	local function classicEntries()
		local list = {}
		for index, entry in ipairs(ENTRIES) do
			list[index] = { name = entry.name, path = entry.path, dependencies = table.clone(entry.dependencies), tool = entry.tool }
		end
		return list
	end
	local function snapshot(list)
		local lines = {}
		for index, entry in ipairs(list) do
			lines[index] = tostring(entry.name) .. "|" .. tostring(entry.path) .. "|" .. table.concat(entry.dependencies or {}, ",") .. "|" .. tostring(entry.tool)
		end
		return table.concat(lines, "\n")
	end
	local function fakeSwitch(style, dev)
		local switch = { Style = style, Commits = {} }
		local devSet = nil
		if dev then
			devSet = {}
			for _, family in ipairs(dev) do
				devSet[family] = true
			end
		end
		function switch.Active(family)
			return switch.Style == "Pulse" and (devSet == nil or devSet[family] == true)
		end
		function switch.Commit(report)
			switch.Commits[#switch.Commits + 1] = report
		end
		function switch.Report()
			return { Style = switch.Style, DevFamilies = dev }
		end
		return switch
	end
	-- Runs Compose expecting an error whose message contains `needle`; checks E5's two side conditions.
	local function expectError(entries, switch, needle)
		local before = snapshot(entries)
		local count = #entries
		local ok, message = pcall(M.Compose, entries, switch)
		expect(not ok, "Compose did not error (wanted: " .. needle .. ")")
		expect(string.find(tostring(message), needle, 1, true) ~= nil, "wrong error: " .. tostring(message))
		expect(#switch.Commits == 0, "Commit was called on a failed Compose")
		expect(snapshot(entries) == before and #entries == count, "the input list was changed")
	end
	-- Replaces the route data for one case and always puts it back.
	local function withData(families, swap, add, body)
		local savedFamilies, savedSwap, savedAdd = M.Families, M.Swap, M.Add
		M.Families, M.Swap, M.Add = families or savedFamilies, swap or savedSwap, add or savedAdd
		local ok, detail = pcall(body)
		M.Families, M.Swap, M.Add = savedFamilies, savedSwap, savedAdd
		if not ok then
			error(detail, 0)
		end
	end

	M._reset()

	case("data: Phase 1 routes one family and the gallery tool entry", function()
		expect(#M.Families == 1 and M.Families[1] == "Toasts", "Families")
		local swapCount = 0
		for _ in pairs(M.Swap) do
			swapCount += 1
		end
		expect(swapCount == 1, "Swap has " .. swapCount .. " rows")
		local swap = M.Swap.SharedTopNotificationUI
		expect(swap and swap.Family == "Toasts" and swap.Path == TOAST_PATH, "toast swap")
		expect(#M.Add == 1, "Add rows")
		local add = M.Add[1]
		expect(add.name == "PulseGallery" and add.path == GALLERY_PATH and add.tool == "PulseGalleryEnabled", "gallery entry")
		expect(type(add.dependencies) == "table" and #add.dependencies == 0 and add.Family == nil, "gallery dependencies or family")
	end)
	case("Resolve errors before Compose has succeeded", function()
		local ok, message = pcall(M.Resolve, "SharedTopNotificationUI")
		expect(not ok and string.find(tostring(message), "Compose has not succeeded", 1, true) ~= nil, tostring(message))
	end)
	case("recorded entry table is the ClientBase list", function()
		expect(#ENTRIES == ENTRY_COUNT, "entry count " .. #ENTRIES)
		lifecycleValidate(classicEntries())
	end)

	case("E4: same names, order, dependencies and tools; one path differs; PulseGallery appended", function()
		local entries = classicEntries()
		local before = snapshot(entries)
		local switch = fakeSwitch("Pulse")
		local composed = M.Compose(entries, switch)
		expect(type(composed) == "table" and composed ~= entries, "a new list is required")
		expect(#composed == #entries + 1, "length " .. #composed)
		local differing = {}
		for index, entry in ipairs(entries) do
			local made = composed[index]
			expect(made ~= entry, "entry " .. entry.name .. " was not copied")
			expect(made.name == entry.name, "name or order changed at " .. index)
			expect(made.tool == entry.tool, "tool changed for " .. entry.name)
			expect(table.concat(made.dependencies, ",") == table.concat(entry.dependencies, ","), "dependencies changed for " .. entry.name)
			if made.path ~= entry.path then
				differing[#differing + 1] = made.name
			end
		end
		expect(#differing == 1 and differing[1] == "SharedTopNotificationUI", "paths differing: " .. table.concat(differing, ","))
		local last = composed[#composed]
		expect(last.name == "PulseGallery" and last.path == GALLERY_PATH and last.tool == "PulseGalleryEnabled", "last entry")
		expect(#last.dependencies == 0 and last.Family == nil, "gallery entry shape")
		expect(last ~= M.Add[1], "the Add row itself was handed out")
		local index = lifecycleValidate(composed)
		expect(index.SharedTopNotificationUI.path == TOAST_PATH, "toast path")
		expect(snapshot(entries) == before, "the input list was changed")
		expect(#switch.Commits == 1, "Commit calls: " .. #switch.Commits)
		local families = switch.Commits[1].Families
		expect(type(families) == "table" and #families == 1 and families[1] == "Toasts", "committed families")
	end)
	case("Resolve after Compose: unknown name errors, downgraded latch errors", function()
		M._reset()
		local switch = fakeSwitch("Pulse")
		M.Compose(classicEntries(), switch)
		local ok, message = pcall(M.Resolve, "NoSuchEntry")
		expect(not ok and string.find(tostring(message), "unknown entry", 1, true) ~= nil, tostring(message))
		switch.Style = "Classic"
		local okDowngraded, downgradedMessage = pcall(M.Resolve, "SharedTopNotificationUI")
		expect(not okDowngraded and string.find(tostring(downgradedMessage), "style is Classic", 1, true) ~= nil, tostring(downgradedMessage))
		M._reset()
	end)
	case("Classic is absolute: Compose refuses a Classic latch", function()
		expectError(classicEntries(), fakeSwitch("Classic"), "style is Classic")
	end)
	case("Compose refuses a missing latch", function()
		expect(not pcall(M.Compose, classicEntries(), nil), "nil latch accepted")
		expect(not pcall(M.Compose, nil, fakeSwitch("Pulse")), "nil entries accepted")
	end)
	case("E5: unknown dev family (UIStyleDevFamilies = Nope)", function()
		expectError(classicEntries(), fakeSwitch("Pulse", { "Nope" }), "Unknown dev family Nope")
		expectError(classicEntries(), fakeSwitch("Pulse", { "Toasts", "Nope" }), "Unknown dev family Nope")
	end)
	case("dev list naming the family composes as normal", function()
		local switch = fakeSwitch("Pulse", { "Toasts" })
		local composed = M.Compose(classicEntries(), switch)
		expect(lifecycleValidate(composed).SharedTopNotificationUI.path == TOAST_PATH, "toast path")
		expect(#switch.Commits == 1 and switch.Commits[1].Families[1] == "Toasts", "commit")
	end)
	case("E5: missing swap target", function()
		local entries = {}
		for _, entry in ipairs(classicEntries()) do
			if entry.name ~= "SharedTopNotificationUI" then
				entries[#entries + 1] = entry
			end
		end
		expectError(entries, fakeSwitch("Pulse"), "Swap target missing")
	end)
	case("E5: duplicate name", function()
		local entries = classicEntries()
		entries[#entries + 1] = { name = "LightingClient", path = "ReplicatedStorage.Modules.Game.World.LightingClient", dependencies = {} }
		expectError(entries, fakeSwitch("Pulse"), "Duplicate client LightingClient")
		local clash = classicEntries()
		clash[#clash + 1] = { name = "PulseGallery", path = "ReplicatedStorage.Modules.Game.UIPulse.Dev.Other", dependencies = {} }
		expectError(clash, fakeSwitch("Pulse"), "Duplicate client PulseGallery")
	end)
	case("E5: missing dependency", function()
		local entries = classicEntries()
		entries[#entries + 1] = { name = "Lonely", path = "ReplicatedStorage.Modules.Game.World.Lonely", dependencies = { "Ghost" } }
		expectError(entries, fakeSwitch("Pulse"), "Missing dependency Ghost")
	end)
	case("E5: dependency cycle", function()
		local entries = classicEntries()
		entries[#entries + 1] = { name = "CycleA", path = "ReplicatedStorage.Modules.Game.World.CycleA", dependencies = { "CycleB" } }
		entries[#entries + 1] = { name = "CycleB", path = "ReplicatedStorage.Modules.Game.World.CycleB", dependencies = { "CycleA" } }
		expectError(entries, fakeSwitch("Pulse"), "Dependency cycle at ")
		local own = classicEntries()
		own[#own + 1] = { name = "Self", path = "ReplicatedStorage.Modules.Game.World.Self", dependencies = { "Self" } }
		expectError(own, fakeSwitch("Pulse"), "Dependency cycle at Self")
	end)
	case("bad entry shapes are refused", function()
		for _, path in ipairs({ "ReplicatedStorage", "", "ReplicatedStorage..Modules", ".ReplicatedStorage.Modules", "ReplicatedStorage.Modules.", "ReplicatedStorage.Mod ules", "ReplicatedStorage/Modules" }) do
			local entries = classicEntries()
			entries[#entries + 1] = { name = "BadPath", path = path, dependencies = {} }
			expectError(entries, fakeSwitch("Pulse"), "Bad path for BadPath")
		end
		local unnamed = classicEntries()
		unnamed[#unnamed + 1] = { path = "ReplicatedStorage.Modules.X", dependencies = {} }
		expectError(unnamed, fakeSwitch("Pulse"), "has no name")
		local badTool = classicEntries()
		badTool[#badTool + 1] = { name = "BadTool", path = "ReplicatedStorage.Modules.X", dependencies = {}, tool = true }
		expectError(badTool, fakeSwitch("Pulse"), "Bad tool flag")
	end)
	case("a swapped or added path outside UIPulse is refused", function()
		withData(nil, { SharedTopNotificationUI = { Family = "Toasts", Path = "ReplicatedStorage.Modules.Game.Elsewhere.ToastClient" } }, nil, function()
			expectError(classicEntries(), fakeSwitch("Pulse"), "Pulse path outside UIPulse")
		end)
		withData(nil, nil, { { name = "PulseGallery", path = "ReplicatedStorage.Modules.Game.Elsewhere.Gallery", dependencies = {} } }, function()
			expectError(classicEntries(), fakeSwitch("Pulse"), "Pulse path outside UIPulse")
		end)
	end)
	case("a swap naming an unknown family is refused", function()
		withData(nil, { SharedTopNotificationUI = { Family = "Ghosts", Path = TOAST_PATH } }, nil, function()
			expectError(classicEntries(), fakeSwitch("Pulse"), "unknown family")
		end)
	end)
	case("active families must be a prefix of Families", function()
		withData({ "Toasts", "Hud" }, nil, nil, function()
			expectError(classicEntries(), fakeSwitch("Pulse", { "Hud" }), "must be a prefix")
		end)
	end)
	case("an inactive later family is not swapped or added", function()
		local swap = {
			SharedTopNotificationUI = { Family = "Toasts", Path = TOAST_PATH },
			FullMapUI = { Family = "Hud", Path = "ReplicatedStorage.Modules.Game.UIPulse.Hud.MapClient" },
		}
		local add = {
			{ name = "PulseGallery", path = GALLERY_PATH, dependencies = {}, tool = "PulseGalleryEnabled" },
			{ name = "PulseHudExtra", path = "ReplicatedStorage.Modules.Game.UIPulse.Hud.Extra", dependencies = {}, Family = "Hud" },
		}
		withData({ "Toasts", "Hud" }, swap, add, function()
			local entries = classicEntries()
			local switch = fakeSwitch("Pulse", { "Toasts" })
			local composed = M.Compose(entries, switch)
			local index = lifecycleValidate(composed)
			expect(index.SharedTopNotificationUI.path == TOAST_PATH, "toast not swapped")
			expect(index.FullMapUI.path == "ReplicatedStorage.Modules.Game.UI.FullMapUI", "an inactive family was swapped")
			expect(index.PulseGallery ~= nil and index.PulseHudExtra == nil, "added entries")
			expect(#switch.Commits == 1 and #switch.Commits[1].Families == 1 and switch.Commits[1].Families[1] == "Toasts", "commit")
			local both = fakeSwitch("Pulse")
			local all = lifecycleValidate(M.Compose(classicEntries(), both))
			expect(all.FullMapUI.path == "ReplicatedStorage.Modules.Game.UIPulse.Hud.MapClient" and all.PulseHudExtra ~= nil, "both families")
			expect(all.PulseHudExtra.Family == nil, "Family left on a composed entry")
			expect(#both.Commits[1].Families == 2, "both committed")
		end)
	end)
	case("with the real latch: commit, then a forced failure downgrades cleanly", function()
		local Switch = env.Load("ReplicatedFirst.UIStyleSwitch")
		local function quiet() end
		local good = Switch._new("Pulse", "", true, quiet)
		local composed = M.Compose(classicEntries(), good)
		expect(#composed == ENTRY_COUNT + 1, "length")
		local report = good.Report()
		expect(report.Committed == true and #report.Families == 1 and report.Families[1] == "Toasts", "latch not committed")
		good.Claim("Toasts")
		local bad = Switch._new("Pulse", "Nope", true, quiet)
		local ok, message = pcall(M.Compose, classicEntries(), bad)
		expect(not ok and string.find(tostring(message), "Unknown dev family Nope", 1, true) ~= nil, tostring(message))
		expect(bad.Report().Committed == false, "committed on failure")
		bad.Downgrade("Routes: " .. tostring(message))
		expect(bad.Style == "Classic" and bad.Active("Toasts") == false and not pcall(bad.Claim, "Toasts"), "downgrade")
		local classic = Switch._new("Classic", "", true, quiet)
		expect(not pcall(M.Compose, classicEntries(), classic) and classic.Report().Committed == false, "Classic latch composed")
	end)

	M._reset()
	return results
end
end)()

local P1_FAMILIES = { "Toasts" }
local P1_SWAP = {
	SharedTopNotificationUI = { Family = "Toasts", Path = "ReplicatedStorage.Modules.Game.UIPulse.Toasts.ToastClient" },
}
local P1_ADD = {
	{ name = "PulseGallery", path = "ReplicatedStorage.Modules.Game.UIPulse.Dev.Gallery", dependencies = {}, tool = "PulseGalleryEnabled" },
}
local EXPECT_FAMILIES = { "Toasts", "RaceMenu", "FreeRoam", "WorldMap", "RaceSession", "RaceEntry", "Garage", "Shell" }
local EXPECT_SWAP = {
	SharedTopNotificationUI = { Family = "Toasts", Path = "ReplicatedStorage.Modules.Game.UIPulse.Toasts.ToastClient" },
	RaceBrowserClient = { Family = "RaceMenu", Path = "ReplicatedStorage.Modules.Game.UIPulse.RaceMenu.RaceMenuClient" },
	DesktopFreeRoamHudUI = { Family = "FreeRoam", Path = "ReplicatedStorage.Modules.Game.UIPulse.FreeRoam.HudClient" },
	MobileFreeRoamHudUI = { Family = "FreeRoam", Path = "ReplicatedStorage.Modules.Game.UIPulse.NoOp" },
	MobileDriveControlsClient = { Family = "FreeRoam", Path = "ReplicatedStorage.Modules.Game.UIPulse.FreeRoam.TouchControlsClient" },
	ActivityClient = { Family = "FreeRoam", Path = "ReplicatedStorage.Modules.Game.UIPulse.FreeRoam.ActivityHudClient" },
	FullMapUI = { Family = "WorldMap", Path = "ReplicatedStorage.Modules.Game.UIPulse.WorldMap.FullMapClient" },
	RaceSessionPresentationClient = { Family = "RaceSession", Path = "ReplicatedStorage.Modules.Game.UIPulse.RaceSession.RaceHudClient" },
	RaceCountdownPresentationClient = { Family = "RaceSession", Path = "ReplicatedStorage.Modules.Game.UIPulse.RaceSession.CountdownClient" },
	RaceQueueClient = { Family = "RaceSession", Path = "ReplicatedStorage.Modules.Game.UIPulse.RaceSession.QueueClient" },
	RaceRouteGuideClient = { Family = "RaceSession", Path = "ReplicatedStorage.Modules.Game.UIPulse.RaceSession.RouteGuideClient" },
	RaceTimeTrialResultCoachClient = { Family = "RaceSession", Path = "ReplicatedStorage.Modules.Game.UIPulse.RaceSession.ResultsClient" },
	RaceEntryPresentationClient = { Family = "RaceEntry", Path = "ReplicatedStorage.Modules.Game.UIPulse.RaceEntry.RaceEntryClient" },
	GarageUI = { Family = "Garage", Path = "ReplicatedStorage.Modules.Game.UIPulse.Garage.GarageClient" },
	OwnedGarageClient = { Family = "Garage", Path = "ReplicatedStorage.Modules.Game.UIPulse.Garage.OwnedGarageClient" },
	GarageEntranceClient = { Family = "Garage", Path = "ReplicatedStorage.Modules.Game.UIPulse.Garage.GarageEntranceClient" },
	OnboardingClient = { Family = "Shell", Path = "ReplicatedStorage.Modules.Game.UIPulse.Shell.OnboardingClient" },
}
local EXPECT_ADD = {
	{ name = "PulseGallery", path = "ReplicatedStorage.Modules.Game.UIPulse.Dev.Gallery", dependencies = {}, tool = "PulseGalleryEnabled" },
	{ name = "PulseCoreUiPolicy", path = "ReplicatedStorage.Modules.Game.UIPulse.Shell.CoreUiPolicy", dependencies = {}, Family = "FreeRoam" },
	{ name = "PulseWorldPrompts", path = "ReplicatedStorage.Modules.Game.UIPulse.World.WorldPromptView", dependencies = { "SharedTopNotificationUI" }, Family = "WorldMap" },
}
local CLASSIC_ENTRIES = {
	{ name = "ActivityClient", path = "ReplicatedStorage.Modules.Game.Activities.ActivityClient", dependencies = { "SharedTopNotificationUI" } },
	{ name = "LightingClient", path = "ReplicatedStorage.Modules.Game.World.LightingClient", dependencies = {} },
	{ name = "DriveSessionClient", path = "ReplicatedStorage.Modules.Game.Vehicles.DriveSessionClient", dependencies = {} },
	{ name = "AcousticsRuntimeClient", path = "ReplicatedStorage.Modules.Game.Audio.AcousticsRuntimeClient", dependencies = {} },
	{ name = "AudioRuntimeClient", path = "ReplicatedStorage.Modules.Game.Audio.AudioRuntimeClient", dependencies = {} },
	{ name = "ContextAudioRuntimeClient", path = "ReplicatedStorage.Modules.Game.Audio.ContextAudioRuntimeClient", dependencies = {} },
	{ name = "PresentationAudioRuntimeClient", path = "ReplicatedStorage.Modules.Game.Audio.PresentationAudioRuntimeClient", dependencies = {} },
	{ name = "DriveToEarnCashTelemetryClient", path = "ReplicatedStorage.Modules.Game.Development.DriveToEarnCashTelemetryClient", dependencies = {} },
	{ name = "StudioCashGrantClient", path = "ReplicatedStorage.Modules.Game.Development.StudioCashGrantClient", dependencies = {} },
	{ name = "DealershipIntroClient", path = "ReplicatedStorage.Modules.Game.Dealership.DealershipIntroClient", dependencies = { "GarageUI" } },
	{ name = "GarageEntranceClient", path = "ReplicatedStorage.Modules.Game.Dealership.GarageEntranceClient", dependencies = { "LoadingTransitionUI", "GarageUI" } },
	{ name = "GaragePreviewPresentationClient", path = "ReplicatedStorage.Modules.Game.Garage.GaragePreviewPresentationClient", dependencies = { "LightingClient" } },
	{ name = "ThrustPreviewClient", path = "ReplicatedStorage.Modules.Game.Garage.ThrustPreviewClient", dependencies = {} },
	{ name = "RaceBrowserClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceBrowserClient", dependencies = {} },
	{ name = "RaceCountdownPresentationClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceCountdownPresentationClient", dependencies = {} },
	{ name = "RaceEntryMenuClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceEntryMenuClient", dependencies = {} },
	{ name = "RaceEntryPresentationClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceEntryPresentationClient", dependencies = { "LoadingTransitionUI" } },
	{ name = "RaceLifecyclePresentationClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceLifecyclePresentationClient", dependencies = {} },
	{ name = "RaceParticipantVisibilityClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceParticipantVisibilityClient", dependencies = {} },
	{ name = "RaceQueueClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceQueueClient", dependencies = {} },
	{ name = "RaceRouteGuideClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceRouteGuideClient", dependencies = {} },
	{ name = "RaceSessionAssetsClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceSessionAssetsClient", dependencies = {} },
	{ name = "RaceSessionPresentationClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceSessionPresentationClient", dependencies = {} },
	{ name = "RaceTimeTrialResultCoachClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceTimeTrialResultCoachClient", dependencies = {} },
	{ name = "RaceTransitionClient", path = "ReplicatedStorage.Modules.Game.Racing.RaceTransitionClient", dependencies = {} },
	{ name = "CharacterSprintClient", path = "ReplicatedStorage.Modules.Game.Vehicles.CharacterSprintClient", dependencies = {} },
	{ name = "FreeRoamParkedHoverClient", path = "ReplicatedStorage.Modules.Game.Vehicles.FreeRoamParkedHoverClient", dependencies = {} },
	{ name = "MobileDriveControlsClient", path = "ReplicatedStorage.Modules.Game.Vehicles.MobileDriveControlsClient", dependencies = {} },
	{ name = "RuntimeVFXClient", path = "ReplicatedStorage.Modules.Game.Vehicles.RuntimeVFXClient", dependencies = {} },
	{ name = "DesktopFreeRoamHudUI", path = "ReplicatedStorage.Modules.Game.UI.DesktopFreeRoamHudUI", dependencies = {} },
	{ name = "FreeRoamVehicleExitButtonClient", path = "ReplicatedStorage.Modules.Game.UI.FreeRoamVehicleExitButtonClient", dependencies = {} },
	{ name = "LoadingTransitionUI", path = "ReplicatedStorage.Modules.Game.UI.LoadingTransitionUI", dependencies = {} },
	{ name = "MobileFreeRoamHudUI", path = "ReplicatedStorage.Modules.Game.UI.MobileFreeRoamHudUI", dependencies = {} },
	{ name = "FullMapUI", path = "ReplicatedStorage.Modules.Game.UI.FullMapUI", dependencies = {} },
	{ name = "OnboardingClient", path = "ReplicatedStorage.Modules.Game.UI.OnboardingClient", dependencies = {} },
	{ name = "OwnedGarageClient", path = "ReplicatedStorage.Modules.Game.UI.OwnedGarageClient", dependencies = { "LoadingTransitionUI" } },
	{ name = "SharedTopNotificationUI", path = "ReplicatedStorage.Modules.Game.UI.SharedTopNotificationUI", dependencies = {} },
	{ name = "LODClient", path = "ReplicatedStorage.Modules.Game.World.LODClient", dependencies = {} },
	{ name = "NightLamppostLightClient", path = "ReplicatedStorage.Modules.Game.World.NightLamppostLightClient", dependencies = {} },
	{ name = "OwnedGarageEnvironmentLightingClient", path = "ReplicatedStorage.Modules.Game.World.OwnedGarageEnvironmentLightingClient", dependencies = { "LightingClient" } },
	{ name = "WindowMaterialClient", path = "ReplicatedStorage.Modules.Game.World.WindowMaterialClient", dependencies = {} },
	{ name = "GarageUI", path = "ReplicatedStorage.Modules.Game.Garage.GarageUI", dependencies = { "DriveSessionClient", "LoadingTransitionUI", "SharedTopNotificationUI" } },
	{ name = "TrailerVehicleCameraClient", path = "ReplicatedStorage.Modules.Game.Development.TrailerVehicleCameraClient", dependencies = {}, tool = "TrailerVehicleCameraEnabled" },
	{ name = "LightingPreviewClient", path = "ReplicatedStorage.Modules.Game.Development.LightingPreviewClient", dependencies = { "LightingClient" }, tool = "LightingPreviewEnabled" },
	{ name = "TrailerModeClient", path = "ReplicatedStorage.Modules.Game.Development.TrailerModeClient", dependencies = {}, tool = "TrailerModeEnabled" },
	{ name = "TrailerShotClient", path = "ReplicatedStorage.Modules.Game.Development.TrailerShotClient", dependencies = {}, tool = "TrailerShotEnabled" },
}

return function(M, env)
	local results = {}
	local function case(name, body)
		local ok, detail = pcall(body)
		results[#results + 1] = { name = name, ok = ok, detail = if ok then nil else tostring(detail) }
	end
	local function expect(condition, message)
		if not condition then
			error(message, 0)
		end
	end
	local function classicEntries()
		local list = {}
		for index, entry in ipairs(CLASSIC_ENTRIES) do
			list[index] = { name = entry.name, path = entry.path, dependencies = table.clone(entry.dependencies), tool = entry.tool }
		end
		return list
	end

	-- Part 1 ------------------------------------------------------------------------------------------------------
	local savedFamilies, savedSwap, savedAdd = M.Families, M.Swap, M.Add
	M.Families, M.Swap, M.Add = P1_FAMILIES, P1_SWAP, P1_ADD
	local okPhase1, phase1Cases = pcall(phase1Test, M, env)
	M.Families, M.Swap, M.Add = savedFamilies, savedSwap, savedAdd
	M._reset()
	if okPhase1 and type(phase1Cases) == "table" then
		for position, row in ipairs(phase1Cases) do
			results[#results + 1] = { name = "phase1: " .. tostring(row.name or position), ok = row.ok == true, detail = row.detail }
		end
		results[#results + 1] = { name = "phase1: the test returned cases", ok = #phase1Cases > 0 }
	else
		results[#results + 1] = { name = "phase1: test run", ok = false, detail = tostring(phase1Cases) }
	end

	-- Part 2 ------------------------------------------------------------------------------------------------------
	case("data: Families, Swap and Add equal the generated tables", function()
		expect(#M.Families == #EXPECT_FAMILIES, "Families has " .. #M.Families .. " names")
		for index, family in ipairs(EXPECT_FAMILIES) do
			expect(M.Families[index] == family, "Families[" .. index .. "] is " .. tostring(M.Families[index]))
		end
		local count = 0
		for name, swap in pairs(M.Swap) do
			count += 1
			local want = EXPECT_SWAP[name]
			expect(want ~= nil, "unexpected swap " .. tostring(name))
			expect(swap.Family == want.Family and swap.Path == want.Path, "swap " .. name .. " differs")
		end
		for name in pairs(EXPECT_SWAP) do
			expect(M.Swap[name] ~= nil, "swap " .. name .. " is missing")
		end
		expect(count > 0, "Swap is empty")
		expect(#M.Add == #EXPECT_ADD, "Add has " .. #M.Add .. " rows")
		for index, want in ipairs(EXPECT_ADD) do
			local row = M.Add[index]
			expect(row.name == want.name and row.path == want.path and row.tool == want.tool and row.Family == want.Family, "Add row " .. index .. " differs")
			expect(table.concat(row.dependencies or {}, ",") == table.concat(want.dependencies, ","), "Add row " .. index .. " dependencies differ")
		end
	end)
	case("every swap names a ClientBase entry and every added dependency exists", function()
		local names = {}
		for _, entry in ipairs(CLASSIC_ENTRIES) do
			names[entry.name] = true
		end
		for name in pairs(M.Swap) do
			expect(names[name], "swap " .. name .. " is not a ClientBase entry")
		end
		for _, row in ipairs(M.Add) do
			expect(not names[row.name], "added entry " .. row.name .. " shadows a ClientBase entry")
			names[row.name] = true
		end
		for _, row in ipairs(M.Add) do
			for _, dependency in ipairs(row.dependencies or {}) do
				expect(names[dependency], "added entry " .. row.name .. " depends on unknown " .. dependency)
			end
		end
	end)
	for count = 1, #EXPECT_FAMILIES do
		case("prefix of " .. count .. " families composes: only its swaps and adds, same names, order, dependencies, tools", function()
			M._reset()
			local prefix, active = {}, {}
			for index = 1, count do
				prefix[index] = EXPECT_FAMILIES[index]
				active[EXPECT_FAMILIES[index]] = true
			end
			local switch = env.FakeSwitch("Pulse")
			if count < #EXPECT_FAMILIES then
				switch.DevFamilies = prefix
			end
			local entries = classicEntries()
			local composed = M.Compose(entries, switch)
			expect(type(composed) == "table" and composed ~= entries, "a new list is required")
			for index, entry in ipairs(entries) do
				local made = composed[index]
				expect(made ~= nil and made ~= entry, "entry " .. entry.name .. " was not copied")
				expect(made.name == entry.name, "name or order changed at " .. index)
				expect(made.tool == entry.tool, "tool changed for " .. entry.name)
				expect(table.concat(made.dependencies, ",") == table.concat(entry.dependencies, ","), "dependencies changed for " .. entry.name)
				local swap = EXPECT_SWAP[entry.name]
				local wanted = if swap and active[swap.Family] then swap.Path else entry.path
				expect(made.path == wanted, entry.name .. " path is " .. tostring(made.path) .. ", expected " .. wanted)
			end
			local position = #entries
			for _, want in ipairs(EXPECT_ADD) do
				if want.Family == nil or active[want.Family] then
					position += 1
					local made = composed[position]
					expect(made ~= nil and made.name == want.name and made.path == want.path and made.tool == want.tool, "added entry " .. want.name .. " is missing or out of order")
					expect(made.Family == nil, "Family left on the composed entry " .. want.name)
				end
			end
			expect(#composed == position, "composed list has " .. #composed .. " entries, expected " .. position)
			local committed = switch.Report().Families
			expect(#committed == count, "committed " .. #committed .. " families")
			for index = 1, count do
				expect(committed[index] == prefix[index], "committed family " .. index .. " is " .. tostring(committed[index]))
			end
			M._reset()
		end)
	end
	return results
end
