"""Generates out_verify_classic.lua: the read-only "Classic is unchanged" check (plan section 1.8).

Reads   manifest.json, config.json (run build_manifest.py first), optionally --declared declared.json
Writes  out_verify_classic.lua   self-contained, ASCII only, run in Studio Edit through execute_luau

Run: py -3 build_verify.py [--declared declared.json] [--out out_verify_classic.lua]

declared.json (all keys optional; paths as in manifest.json / config.json):
  {
    "scripts":      {"<script path>": {"file": "relative/after.lua"}            edited Classic scripts and their
                                   or {"length": n, "djb2": n, "fnv1a32": n}},   recorded after-hashes
    "addedScripts": {"<script path>": {} or the same hash forms, optional "class"},
    "configNodes":  ["UI.Pulse"],              added instances under Config (the node and everything below it)
    "configAttrs":  ["UI.Some.Folder@Attr"],   added attributes on recorded nodes
    "services":     {"StarterGuiChildren": 1}  declared new values of the recorded service settings
  }
"""
import argparse
import io
import json
import os

from build_manifest import HERE, PLACE_ID, djb2, fnv1a32, load_json

SIZE_LIMIT = 190000
SERVICE_KEYS = ("StarterGuiChildren", "ShowDevelopmentGui", "ScreenOrientation")

# The exact Luau arithmetic. test_manifest.py ports these lines one for one.
# fnv1a32: f * 16777619 = f * 2^24 + f * 403. lshift keeps the first term under 2^32, f * 403 is under 2^41,
# so every intermediate is an exact integer in a double. djb2: d * 33 + b is under 2^38.
LUA_HASH = """local function hashes(s)
	local d = 5381
	local f = 2166136261
	for i = 1, #s do
		local b = string.byte(s, i)
		d = (d * 33 + b) % 4294967296
		f = bit32.bxor(f, b)
		f = (bit32.lshift(f, 24) + f * 403) % 4294967296
	end
	return d, f
end"""

TEMPLATE = r'''-- out_verify_classic.lua  GENERATED by scripts/ui_restyle/classic/build_verify.py. Do not edit.
-- READ-ONLY. Run in Studio Edit (execute_luau). Writes nothing to the DataModel. Returns one JSON string.
-- Baseline: @@PLACE_NAME@@ (@@PLACE_ID@@), @@TAKEN@@, Edit, @@COUNT@@ scripts. Hashes: djb2 + fnv1a32 over source bytes.
local PLACE_ID = @@PLACE_ID@@
local ROOTS = { "ReplicatedStorage", "ServerStorage", "ReplicatedFirst", "Workspace", "ServerScriptService", "StarterPlayer", "StarterGui", "StarterPack" }
local CONFIG_ROOTS = { @@CONFIG_ROOTS@@ }
local TOLERANCE = 1e-6
local YIELD_EVERY = 20
local LIST_CAP = 300
-- { path, class, bytes, djb2, fnv1a32, disabled }
local EXPECT_SCRIPTS = {
@@SCRIPTS@@
}
-- { path under ReplicatedStorage.Config, class, attributes { name = { type, value } } or false, value { type, value } or false }
local EXPECT_CONFIG = {
@@CONFIG@@
}
local EXPECT_SERVICES = @@SERVICES@@
-- Declared changes from later phases (build_verify.py --declared). Listed separately, never counted as failures.
local DECLARED = {
	scripts = @@DECLARED_SCRIPTS@@,
	addedScripts = @@DECLARED_ADDED@@,
	configNodes = @@DECLARED_NODES@@,
	configAttrs = @@DECLARED_ATTRS@@,
	services = @@DECLARED_SERVICES@@,
}

assert(game.PlaceId == PLACE_ID, string.format("out_verify_classic: wrong place %.0f, expected %.0f", game.PlaceId, PLACE_ID))
assert(not game:GetService("RunService"):IsRunning(), "out_verify_classic: run in Edit, not Play")
local started = os.clock()

@@LUA_HASH@@

local ARRAY = setmetatable({}, { __mode = "k" })
local totals = {}
local function arr(t)
	ARRAY[t] = true
	return t
end
local function push(list, item)
	totals[list] = (totals[list] or 0) + 1
	if #list < LIST_CAP then
		list[#list + 1] = item
	end
end
local function total(list)
	return totals[list] or 0
end

local ESCAPES = { ['"'] = '\\"', ["\\"] = "\\\\", ["\n"] = "\\n", ["\r"] = "\\r", ["\t"] = "\\t" }
local function escapeChar(c)
	return ESCAPES[c] or string.format("\\u%04x", string.byte(c))
end
local function encode(v)
	local t = type(v)
	if t == "nil" then
		return "null"
	elseif t == "boolean" then
		return v and "true" or "false"
	elseif t == "number" then
		if v ~= v or v == math.huge or v == -math.huge then
			return '"' .. tostring(v) .. '"'
		end
		if v == math.floor(v) and math.abs(v) < 9007199254740992 then
			return string.format("%.0f", v)
		end
		return string.format("%.17g", v)
	elseif t == "string" then
		return '"' .. string.gsub(v, '[%c"\\]', escapeChar) .. '"'
	elseif t == "table" then
		local parts = {}
		if ARRAY[v] then
			for i = 1, #v do
				parts[i] = encode(v[i])
			end
			return "[" .. table.concat(parts, ",") .. "]"
		end
		local keys = {}
		for k in pairs(v) do
			keys[#keys + 1] = tostring(k)
		end
		table.sort(keys)
		for i, k in ipairs(keys) do
			parts[i] = encode(k) .. ":" .. encode(v[k])
		end
		return "{" .. table.concat(parts, ",") .. "}"
	end
	return encode(tostring(v))
end

---------------------------------------------------------------------------------------------------- scripts
local scripts = { same = 0, changed = arr({}), missing = arr({}), added = arr({}) }
local declared = { scripts = arr({}), addedScripts = arr({}), config = arr({}), services = arr({}) }
local expected, seen, scanned = {}, {}, 0
for _, row in ipairs(EXPECT_SCRIPTS) do
	expected[row[1]] = row
end
local function describe(row)
	return { class = row[2] or nil, len = row[3], djb2 = row[4], fnv1a32 = row[5], disabled = row[6] }
end
local function matches(row, now)
	return (not row[2] or row[2] == now[2]) and row[3] == now[3] and row[4] == now[4] and row[5] == now[5] and row[6] == now[6]
end

for _, rootName in ipairs(ROOTS) do
	local root = game:GetService(rootName)
	for _, inst in ipairs(root:GetDescendants()) do
		if inst:IsA("LuaSourceContainer") then
			local parts, node = {}, inst
			while node and node ~= root do
				table.insert(parts, 1, node.Name)
				node = node.Parent
			end
			local path = rootName .. "." .. table.concat(parts, ".")
			local len, d, f = -1, -1, -1
			local okSource, source = pcall(function()
				return inst.Source
			end)
			if okSource and type(source) == "string" then
				len = #source
				d, f = hashes(source)
			end
			local disabled = false
			if inst:IsA("BaseScript") then
				local okDisabled, value = pcall(function()
					return inst.Disabled
				end)
				disabled = okDisabled and value == true
			end
			local now = { path, inst.ClassName, len, d, f, disabled }
			local row = expected[path]
			if seen[path] then
				push(scripts.added, { path = path .. " (another instance with the same path)", now = describe(now) })
			elseif row then
				seen[path] = true
				local dec = DECLARED.scripts[path]
				if matches(row, now) then
					scripts.same += 1
					if dec then
						push(declared.scripts, { path = path, state = "before (declared edit not applied)" })
					end
				elseif dec and matches(dec, now) then
					push(declared.scripts, { path = path, state = "after", was = describe(row), now = describe(now) })
				else
					push(scripts.changed, { path = path, was = describe(row), now = describe(now), declaredAfter = dec and describe(dec) or nil })
				end
			else
				seen[path] = true
				local dec = DECLARED.addedScripts[path]
				if dec == nil then
					push(scripts.added, { path = path, now = describe(now) })
				elseif dec == true or matches(dec, now) then
					push(declared.addedScripts, { path = path, state = "present", now = describe(now) })
				else
					push(scripts.changed, { path = path, was = describe(dec), now = describe(now), declaredAdded = true })
				end
			end
			scanned += 1
			if scanned % YIELD_EVERY == 0 then
				task.wait()
			end
		end
	end
end
for _, row in ipairs(EXPECT_SCRIPTS) do
	if not seen[row[1]] then
		push(scripts.missing, row[1])
	end
end
for path in pairs(DECLARED.addedScripts) do
	if not seen[path] then
		push(declared.addedScripts, { path = path, state = "not present" })
	end
end
task.wait()

---------------------------------------------------------------------------------------------------- config
local config = { same = 0, nodes = 0, diffs = arr({}), added = arr({}), removed = arr({}) }
local expNodes, visited = {}, {}
for _, row in ipairs(EXPECT_CONFIG) do
	expNodes[row[1]] = row
end
local function typed(v)
	local t = typeof(v)
	if t == "number" or t == "boolean" or t == "string" then
		return t, v
	elseif t == "Color3" then
		return t, { v.R, v.G, v.B }
	elseif t == "Vector3" then
		return t, { v.X, v.Y, v.Z }
	end
	return t, tostring(v)
end
local function close(a, b)
	return a == b or (a ~= a and b ~= b) or math.abs(a - b) <= TOLERANCE
end
local function sameValue(exp, t, v)
	if exp[1] ~= t then
		return false
	end
	if t == "number" then
		return close(exp[2], v)
	end
	if type(v) == "table" then
		if type(exp[2]) ~= "table" or #exp[2] ~= #v then
			return false
		end
		for i = 1, #v do
			if not close(exp[2][i], v[i]) then
				return false
			end
		end
		return true
	end
	return exp[2] == v
end
local function show(t, v)
	return { t = t, v = type(v) == "table" and arr(v) or v }
end
local function compare(path, attr, exp, value)
	local t, v = typed(value)
	if sameValue(exp, t, v) then
		config.same += 1
	else
		push(config.diffs, { path = path, attr = attr, was = show(exp[1], exp[2]), now = show(t, v) })
	end
end
local function walk(inst, path)
	local row = expNodes[path]
	if visited[path] then
		push(config.added, path .. " (another instance with the same path)")
		return
	end
	if not row then
		if DECLARED.configNodes[path] then
			push(declared.config, path)
		else
			push(config.added, path)
		end
		return
	end
	visited[path] = true
	config.nodes += 1
	if inst.ClassName ~= row[2] then
		push(config.diffs, { path = path, attr = "@Class", was = row[2], now = inst.ClassName })
	end
	local expAttrs = row[3] or {}
	local live = inst:GetAttributes()
	for name, exp in pairs(expAttrs) do
		if live[name] == nil then
			push(config.removed, path .. "@" .. name)
		else
			compare(path, name, exp, live[name])
		end
	end
	for name in pairs(live) do
		if expAttrs[name] == nil then
			local key = path .. "@" .. name
			if DECLARED.configAttrs[key] then
				push(declared.config, key)
			else
				push(config.added, key)
			end
		end
	end
	if row[4] then
		local okValue, value = pcall(function()
			return inst.Value
		end)
		if okValue then
			compare(path, "@Value", row[4], value)
		else
			push(config.removed, path .. "@Value")
		end
	end
	for _, child in ipairs(inst:GetChildren()) do
		walk(child, path .. "." .. child.Name)
	end
end
local configFolder = game:GetService("ReplicatedStorage"):FindFirstChild("Config")
for _, name in ipairs(CONFIG_ROOTS) do
	local root = configFolder and configFolder:FindFirstChild(name)
	if root then
		walk(root, name)
	end
end
for _, row in ipairs(EXPECT_CONFIG) do
	if not visited[row[1]] then
		push(config.removed, row[1])
	end
end

local StarterGui = game:GetService("StarterGui")
local readers = {
	StarterGuiChildren = function()
		return #StarterGui:GetChildren()
	end,
	ShowDevelopmentGui = function()
		return StarterGui.ShowDevelopmentGui
	end,
	ScreenOrientation = function()
		return tostring(StarterGui.ScreenOrientation)
	end,
}
for key, was in pairs(EXPECT_SERVICES) do
	local okRead, now = pcall(readers[key])
	if not okRead then
		now = "unreadable: " .. tostring(now)
	end
	if now == was then
		config.same += 1
	elseif DECLARED.services[key] ~= nil and DECLARED.services[key] == now then
		push(declared.services, { key = key, was = was, now = now })
	else
		push(config.diffs, { path = "Services.StarterGui", attr = key, was = was, now = now })
	end
end

---------------------------------------------------------------------------------------------------- result
local function byPath(a, b)
	if a.path ~= b.path then
		return a.path < b.path
	end
	return tostring(a.attr or a.state or "") < tostring(b.attr or b.state or "")
end
table.sort(scripts.changed, byPath)
table.sort(scripts.added, byPath)
table.sort(scripts.missing)
table.sort(config.diffs, byPath)
table.sort(config.added)
table.sort(config.removed)
table.sort(declared.scripts, byPath)
table.sort(declared.addedScripts, byPath)
table.sort(declared.config)

local failures = total(scripts.changed) + total(scripts.missing) + total(scripts.added)
	+ total(config.diffs) + total(config.added) + total(config.removed)
local truncated = false
for _, count in pairs(totals) do
	if count > LIST_CAP then
		truncated = true
	end
end
return encode({
	ok = failures == 0,
	failures = failures,
	truncated = truncated,
	placeId = game.PlaceId,
	baseline = "@@TAKEN@@",
	expectedScripts = #EXPECT_SCRIPTS,
	scannedScripts = scanned,
	seconds = math.floor((os.clock() - started) * 100 + 0.5) / 100,
	scripts = scripts,
	config = config,
	declared = declared,
})
'''


def lua_string(text):
    out = ['"']
    for b in text.encode("utf-8"):
        if b == 0x22:
            out.append('\\"')
        elif b == 0x5C:
            out.append("\\\\")
        elif 0x20 <= b < 0x7F:
            out.append(chr(b))
        else:
            out.append("\\%03d" % b)
    out.append('"')
    return "".join(out)


def lua_value(value):
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        return lua_string(value)
    if isinstance(value, list):
        return "{" + ",".join(lua_value(item) for item in value) + "}"
    raise TypeError(repr(value))


def lua_typed(typed):
    return "{%s,%s}" % (lua_string(typed["t"]), lua_value(typed["v"]))


def script_row(path, klass, length, d, f, disabled):
    return "{%s,%s,%d,%d,%d,%s}" % (
        lua_string(path), lua_string(klass) if klass else "false", length, d, f, "true" if disabled else "false")


def lua_map(pairs):
    if not pairs:
        return "{}"
    return "{\n" + "".join("\t\t[%s] = %s,\n" % (lua_string(key), value) for key, value in pairs) + "\t}"


def declared_tables(path, baseline):
    declared = {}
    if path:
        with io.open(path, encoding="utf-8") as handle:
            declared = json.load(handle)
    base_dir = os.path.dirname(os.path.abspath(path)) if path else HERE
    known = {"scripts", "addedScripts", "configNodes", "configAttrs", "services"}
    unknown = set(declared) - known
    if unknown:
        raise SystemExit("declared: unknown keys %s" % sorted(unknown))

    def hashed(entry, where):
        if "file" in entry:
            with open(os.path.join(base_dir, entry["file"]), "rb") as handle:
                data = handle.read()
            return len(data), djb2(data), fnv1a32(data)
        try:
            return int(entry["length"]), int(entry["djb2"]), int(entry["fnv1a32"])
        except KeyError:
            raise SystemExit("declared %s: give file, or length + djb2 + fnv1a32" % where)

    scripts = []
    for script_path, entry in sorted((declared.get("scripts") or {}).items()):
        base = baseline.get(script_path)
        if base is None:
            raise SystemExit("declared.scripts: %s is not in manifest.json (use addedScripts)" % script_path)
        length, d, f = hashed(entry, script_path)
        scripts.append((script_path, script_row(
            script_path, entry.get("class", base["class"]), length, d, f,
            entry.get("disabled", base.get("disabled", False)))))
    added = []
    for script_path, entry in sorted((declared.get("addedScripts") or {}).items()):
        if script_path in baseline:
            raise SystemExit("declared.addedScripts: %s is already in manifest.json (use scripts)" % script_path)
        if not entry or not ({"file", "length"} & set(entry)):
            added.append((script_path, "true"))
        else:
            length, d, f = hashed(entry, script_path)
            added.append((script_path, script_row(
                script_path, entry.get("class"), length, d, f, entry.get("disabled", False))))
    services = declared.get("services") or {}
    for key in services:
        if key not in SERVICE_KEYS:
            raise SystemExit("declared.services: unknown key " + key)
    return {
        "@@DECLARED_SCRIPTS@@": lua_map(scripts),
        "@@DECLARED_ADDED@@": lua_map(added),
        "@@DECLARED_NODES@@": lua_map((key, "true") for key in sorted(declared.get("configNodes") or [])) if declared.get("configNodes") else "{}",
        "@@DECLARED_ATTRS@@": lua_map((key, "true") for key in sorted(declared.get("configAttrs") or [])) if declared.get("configAttrs") else "{}",
        "@@DECLARED_SERVICES@@": lua_map((key, lua_value(services[key])) for key in sorted(services)) if services else "{}",
    }


def build(declared_path=None):
    manifest = load_json("manifest.json")
    config = load_json("config.json")
    rows = manifest["scripts"]
    script_lines = "\n".join(
        "\t" + script_row(r["path"], r["class"], r["length"], r["djb2"], r["fnv1a32"], r.get("disabled", False)) + ","
        for r in rows)
    config_lines = []
    for root_name in sorted(config["roots"]):
        nodes = config["roots"][root_name]["nodes"]
        for path in sorted(nodes):
            node = nodes[path]
            attrs = "false"
            if node["attributes"]:
                attrs = "{" + ",".join(
                    "[%s]=%s" % (lua_string(name), lua_typed(node["attributes"][name]))
                    for name in sorted(node["attributes"])) + "}"
            value = lua_typed(node["value"]) if "value" in node else "false"
            config_lines.append("\t{%s,%s,%s,%s}," % (lua_string(path), lua_string(node["class"]), attrs, value))
    services = config["services"]["values"]
    for key in services:
        if key not in SERVICE_KEYS:
            raise SystemExit("config.json services: no reader for %s; add one to TEMPLATE and SERVICE_KEYS" % key)
    replacements = {
        "@@PLACE_ID@@": str(PLACE_ID),
        "@@PLACE_NAME@@": manifest["record"]["place"],
        "@@TAKEN@@": manifest["record"]["taken"],
        "@@COUNT@@": str(len(rows)),
        "@@CONFIG_ROOTS@@": ", ".join(lua_string(name) for name in sorted(config["roots"])),
        "@@SCRIPTS@@": script_lines,
        "@@CONFIG@@": "\n".join(config_lines),
        "@@SERVICES@@": "{ " + ", ".join("%s = %s" % (key, lua_value(services[key])) for key in sorted(services)) + " }",
        "@@LUA_HASH@@": LUA_HASH,
    }
    replacements.update(declared_tables(declared_path, {r["path"]: r for r in rows}))
    text = TEMPLATE
    for key, value in replacements.items():
        text = text.replace(key, value)
    if "@@" in text:
        raise SystemExit("unreplaced placeholder in the generated script")
    text.encode("ascii")  # the generated script must be pure ASCII
    if len(text) >= SIZE_LIMIT:
        raise SystemExit("generated script is %d characters; the limit is %d" % (len(text), SIZE_LIMIT))
    return text


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--declared", default=None)
    parser.add_argument("--out", default=os.path.join(HERE, "out_verify_classic.lua"))
    args = parser.parse_args()
    text = build(args.declared)
    with io.open(args.out, "w", encoding="ascii", newline="\n") as handle:
        handle.write(text)
    print("%s: %d characters (limit %d)" % (os.path.basename(args.out), len(text), SIZE_LIMIT))


if __name__ == "__main__":
    main()
