-- NTR_OWNED_GARAGE_MANAGEMENT_RUNTIME_V1
-- NTR_OWNED_GARAGE_MANAGEMENT_RUNTIME_V2_NAMESPACED_RESET
-- NTR_OWNED_GARAGE_MANAGEMENT_RUNTIME_V3_REUSABLE_FRAMEWORK
-- NTR_OWNED_GARAGE_MANAGEMENT_RUNTIME_V4_VERTICAL_SLICE
-- NTR_OWNED_GARAGE_MANAGEMENT_RUNTIME_V5_AUTHORITATIVE_MUTATION_STATE
-- NTR_OWNED_GARAGE_MANAGEMENT_RUNTIME_V6_PROFILE_COMMAND_BOUNDARY
-- NTR_OWNED_GARAGE_MANAGEMENT_RUNTIME_V7_VERIFIED_TRANSITIONS
-- NTR_OWNED_GARAGE_STRUCTURE_MANAGEMENT_V1
-- NTR_OWNED_GARAGE_STRUCTURE_ASSET_RUNTIME_V1
-- NTR_OWNED_GARAGE_DECORATION_MANAGEMENT_V1
-- NTR_OWNED_GARAGE_LIGHTING_MANAGEMENT_V1
-- NTR_OWNED_GARAGE_ACCESS_INVITATIONS_MANAGEMENT_V1
local Players=game:GetService("Players")
local ReplicatedStorage=game:GetService("ReplicatedStorage")
local ServerScriptService=game:GetService("ServerScriptService")
local ServerStorage=game:GetService("ServerStorage")
local Workspace=game:GetService("Workspace")
local Runtime={}; local started=false
function Runtime.ChooseSlot(displaySpaces,requestedSlotId,orderedSlotIds)
	displaySpaces=type(displaySpaces)=="table" and displaySpaces or {}; requestedSlotId=tostring(requestedSlotId or ""); orderedSlotIds=type(orderedSlotIds)=="table" and orderedSlotIds or {"Space01","Space02"}
	if requestedSlotId~="" then if displaySpaces[requestedSlotId]~=nil then return requestedSlotId,"Requested" end; return nil,"Invalid" end
	for _,slotId in ipairs(orderedSlotIds) do if displaySpaces[slotId]==false or displaySpaces[slotId]==nil or tostring(displaySpaces[slotId])=="" then return slotId,"Empty" end end
	return nil,"Full"
end
function Runtime.Start()
	if started then return true,"AlreadyStarted" end
	local kit=ReplicatedStorage:WaitForChild("NeoTokyoRacers"); local remotes=kit.Shared.Remotes.Garage; local invoke=remotes:WaitForChild("OwnedGarageInvoke"); local push=remotes:WaitForChild("OwnedGarageEvent"); local catalog=require(kit.Shared.Modules.Data:WaitForChild("OwnedGaragePropertyCatalog")); local styleCatalog=require(kit.Shared.Modules.Data:WaitForChild("OwnedGarageInteriorStyleCatalog")); local decorationCatalog=require(kit.Shared.Modules.Data:WaitForChild("OwnedGarageDecorationCatalog")); local lightingCatalog=require(kit.Shared.Modules.Data:WaitForChild("OwnedGarageLightingCatalog"))
	local services=ServerScriptService.NeoTokyoRacers.Services; local garage=services.Garage; local Profile=require(garage:WaitForChild("OwnedGarageProfileRuntime")); local Assignment=require(garage:WaitForChild("OwnedGarageDisplayAssignmentRuntime")); local Interior=require(garage:WaitForChild("OwnedGarageInteriorRuntime")); local Display=require(garage:WaitForChild("OwnedGarageDisplayRuntime")); local lifecycle=garage:WaitForChild("OwnedGarageVehicleLifecycleBridge")
	local bindings=services.Player:WaitForChild("ProfileServiceBindings"); local getProfile=bindings:WaitForChild("GetProfile"); local executeOwnedGarageCommand=bindings:WaitForChild("ExecuteOwnedGarageCommand"); local saveNow=bindings:WaitForChild("SaveNow"); local settings=kit.Config.Runtime:WaitForChild("OwnedGarage_EditAttributes")
	local world=Workspace:WaitForChild("NeoTokyoRacersWorld"); local exteriorRoot=world:WaitForChild("OwnedGarageExteriors"); local interiors=world:FindFirstChild("Interiors") or Instance.new("Folder"); interiors.Name="Interiors"; interiors.Parent=world; local pool=interiors:FindFirstChild("OwnedGarageInstances") or Instance.new("Folder"); pool.Name="OwnedGarageInstances"; pool:SetAttribute("OwnedGarageRuntimePool",true); pool.Parent=interiors
	local sessions={}; local slotByUserId={}; local promptConnections={}; local locks={}; local lastRequest={}; local stateCache=setmetatable({},{__mode="k"}); local requestWindows=setmetatable({},{__mode="k"}); local stateFor; local driveOut,exitOnFoot
	local function profileFor(player)
		local initial=getProfile:Invoke(player); if type(initial)~="table" then return nil,"Profile is not loaded." end
		local resetToken=tostring(settings:GetAttribute("TesterResetToken") or ""); local resetUserId=math.floor(tonumber(settings:GetAttribute("TesterResetUserId")) or 0); local existing=type(initial.OwnedGarage)=="table" and initial.OwnedGarage or nil; local shouldReset=player.UserId==resetUserId and resetToken~="" and tostring(existing and existing.TesterResetToken or "")~=resetToken
		local ensured=executeOwnedGarageCommand:Invoke(player,{Operation="Ensure",Reset=shouldReset,ResetToken=resetToken}); if type(ensured)~="table" or not ensured.Success then return nil,tostring(ensured and ensured.Message or "Owned garage state is unavailable.") end
		if ensured.ResetApplied then local saved,saveMessage=saveNow:Invoke(player); if not saved then warn("[NTR Owned Garage] Tester reset save deferred: "..tostring(saveMessage)) end end
		local profile=getProfile:Invoke(player); if type(profile)~="table" then return nil,"Profile is not loaded." end; return profile
	end
	local function command(player,operation,args,reason,requestId,baseRevision)
		return executeOwnedGarageCommand:Invoke(player,{Operation=operation,Args=args,Reason=reason,RequestId=requestId or Profile.NewRequestId(),BaseRevision=baseRevision})
	end
	local function compensate(player,snapshot,baseRevision,reason)
		local result=executeOwnedGarageCommand:Invoke(player,{Operation="Restore",State=snapshot,Reason=reason,RequestId=Profile.NewRequestId(),BaseRevision=baseRevision}); if type(result)~="table" or not result.Success then warn("[NTR Owned Garage] compensation failed: "..tostring(result and result.Message or "unavailable")); return false end; return true
	end
	local function lifecycleCall(action,player,payload)
		payload=type(payload)=="table" and payload or {}; payload.Player=player; local ok,result=pcall(function() return lifecycle:Invoke(action,payload) end)
		if not ok then return {Success=false,Message="Vehicle lifecycle unavailable: "..tostring(result)} end; return type(result)=="table" and result or {Success=false,Message="Invalid vehicle lifecycle response."}
	end
	local function characterRoot(player)
		local character=player.Character; return character and character:FindFirstChild("HumanoidRootPart")
	end
	local function teleportCharacter(player,cframe)
		if typeof(cframe)~="CFrame" then return false,"Destination missing." end
		local attempts=math.clamp(math.floor(tonumber(settings:GetAttribute("GarageTeleportAttempts")) or 2),1,4); local tolerance=math.max(4,tonumber(settings:GetAttribute("GarageTeleportVerifyDistanceStuds")) or 12)
		for _=1,attempts do local character=player.Character; local root=characterRoot(player); if not (character and root) then return false,"Character is not ready." end; character:PivotTo(cframe); root.AssemblyLinearVelocity=Vector3.zero; root.AssemblyAngularVelocity=Vector3.zero; task.wait(); root=characterRoot(player); if root and (root.Position-cframe.Position).Magnitude<=tolerance then return true end end
		return false,"Character teleport could not be verified."
	end
	local function exteriorCFrame(propertyId,markerName)
		local definition=catalog.ById(propertyId); local exteriorId=definition and tostring(definition.ExteriorSpawnId or "") or ""; local folder=exteriorId~="" and exteriorRoot:FindFirstChild(exteriorId); local marker=folder and folder:FindFirstChild(markerName)
		if not (marker and marker:IsA("BasePart")) then return nil,"Exterior spawn missing for "..tostring(propertyId).."/"..tostring(markerName) end; return marker.CFrame
	end
	local function slotIndex(player)
		if slotByUserId[player.UserId] then return slotByUserId[player.UserId] end; local used={}; for _,index in pairs(slotByUserId) do used[index]=true end; local index=1; while used[index] do index+=1 end; slotByUserId[player.UserId]=index; return index
	end
	local function disconnectPrompts(interior)
		for _,connection in ipairs(promptConnections[interior] or {}) do connection:Disconnect() end; promptConnections[interior]=nil
	end
	local function scheduleUnload(interior,player)
		task.delay(math.max(0,tonumber(settings:GetAttribute("InteriorUnloadDelaySeconds")) or 20),function() if interior and interior.Parent and not sessions[player] then disconnectPrompts(interior); interior:Destroy() end end)
	end
	local function setInside(player,session)
		player:SetAttribute("NTR_OwnedGarageInside",session~=nil); player:SetAttribute("NTR_OwnedGaragePropertyId",session and session.PropertyId or nil); player:SetAttribute("NTR_OwnedGarageOwnerUserId",session and player.UserId or nil)
	end
	local function featureEnabled(name,default) local value=settings:GetAttribute("Enable"..name); if value==nil then return default end; return value==true end
	local function capabilities(propertyId) local result=catalog.Capabilities(propertyId); for name,value in pairs(result) do result[name]=value==true and featureEnabled(name,name=="DisplayCars") end; return result end
	local function applyPromptPolicy(session)
		if not (session and session.Interior) then return end; local blocked=session.ManagementOpen==true or session.Transition~=nil
		for _,prompt in ipairs(session.Interior:GetDescendants()) do if prompt:IsA("ProximityPrompt") and (prompt.Name=="DriveOutPrompt" or prompt.Name=="FootExitPrompt" or prompt.Name=="ManageGaragePrompt") then prompt.HoldDuration=0; prompt.Enabled=not blocked and prompt:GetAttribute("OwnedGarageAvailable")~=false end end
	end
	local function allowRequest(player,action)
		local now=os.clock(); local window=requestWindows[player]; if not window or now-window.Start>=1 then window={Start=now,Count=0}; requestWindows[player]=window end; window.Count+=1; local maximum=(action=="GetState" or action=="GetManagementState") and (tonumber(settings:GetAttribute("ReadRequestsPerSecond")) or 20) or (tonumber(settings:GetAttribute("MutationRequestsPerSecond")) or 12); return window.Count<=maximum
	end
	local function vehicleName(profile,vehicleId)
		local vehicle=profile.Vehicles and profile.Vehicles[tostring(vehicleId or "")]; return type(vehicle)=="table" and tostring(vehicle.DisplayName or vehicle.CockpitId or vehicleId) or tostring(vehicleId or "")
	end
	local function applyInteriorStyles(profile,session)
		local property=profile.OwnedGarage.Properties[session.PropertyId]; local definition=catalog.ById(session.PropertyId); local sections=definition and definition.StructureSections or {}; local structure=styleCatalog.NormalizeStructure(property and property.Customisation and property.Customisation.Structure,sections); local preview=session.StructurePreview
		local storageRoot=ServerStorage:FindFirstChild("NeoTokyoRacers"); storageRoot=storageRoot and storageRoot:FindFirstChild("OwnedGarage"); storageRoot=storageRoot and storageRoot:FindFirstChild("StructureAssets"); local templateRoot=storageRoot and storageRoot:FindFirstChild(tostring(definition and definition.TemplateId or "")); local slots=session.Interior:FindFirstChild("StructureSlots"); if not (templateRoot and slots) then return false,"Structure asset contract is missing." end
		local runtime=session.Interior:FindFirstChild("StructureRuntime"); if not runtime then runtime=Instance.new("Folder"); runtime.Name="StructureRuntime"; runtime.Parent=session.Interior end
		for _,base in ipairs(session.Interior:GetDescendants()) do if base:IsA("BasePart") and base:GetAttribute("StructureSection") and not base:IsDescendantOf(runtime) and not base:IsDescendantOf(slots) then base.Transparency=1; base.CanCollide=false; base.CanTouch=false; base.CanQuery=false end end
		for _,section in ipairs(sections) do
			local item=structure.Sections[section]; if preview and preview.SectionId==section then item=preview end; local style=item and styleCatalog.ById(section,item.StyleId); local slot=slots:FindFirstChild(section); local sectionRoot=templateRoot:FindFirstChild(section); local asset=style and sectionRoot and sectionRoot:FindFirstChild(style.AssetOption)
			if not (style and slot and slot:IsA("BasePart") and asset and asset:IsA("Model")) then return false,"Structure asset missing: "..tostring(section).."/"..tostring(style and style.AssetOption or "") end
			local oldModel=runtime:FindFirstChild(section); if oldModel then oldModel:Destroy() end; local clone=asset:Clone(); clone.Name=section
			for _,object in ipairs(clone:GetDescendants()) do if object:IsA("LuaSourceContainer") or object:IsA("ProximityPrompt") or object:IsA("Seat") or object:IsA("VehicleSeat") then object:Destroy() elseif object:IsA("BasePart") then local localCFrame=object.CFrame; object.CFrame=slot.CFrame*localCFrame; object.Anchored=true; object.CanTouch=false; object.CanQuery=false; object.CastShadow=false; local channel=tostring(object:GetAttribute("StructureChannel") or "Primary"); object.Color=styleCatalog.DecodeColor(item.Colors[channel] or item.Colors.Primary); local material=Enum.Material[item.Materials[channel] or item.Materials.Primary]; if material then object.Material=material end end end
			clone:SetAttribute("StructureSection",section); clone:SetAttribute("StructureStyleId",style.StyleId); clone:SetAttribute("StructurePreview",preview and preview.SectionId==section or false); clone.Parent=runtime
		end
		return true
	end
	local function applyDecorations(profile,session)
		local property=profile.OwnedGarage.Properties[session.PropertyId]; local definition=catalog.ById(session.PropertyId); local anchorIds=definition and definition.DecorationAnchorIds or {}; local decorations=decorationCatalog.Normalize(property and property.Customisation and property.Customisation.Decorations,anchorIds); local anchorRoot=session.Interior:FindFirstChild("DecorationAnchors"); if not anchorRoot then return false,"Decoration anchors are missing." end
		local assets=ServerStorage:FindFirstChild("NeoTokyoRacers"); assets=assets and assets:FindFirstChild("OwnedGarage"); assets=assets and assets:FindFirstChild("DecorationAssets"); if not assets then return false,"Decoration assets are missing." end
		local runtime=session.Interior:FindFirstChild("DecorationRuntime"); if not runtime then runtime=Instance.new("Folder"); runtime.Name="DecorationRuntime"; runtime.Parent=session.Interior end; runtime:ClearAllChildren()
		for _,anchorId in ipairs(anchorIds) do local itemId=decorations.Placements[anchorId]; if session.DecorationPreview and session.DecorationPreview.AnchorId==anchorId then itemId=session.DecorationPreview.ItemId end; if itemId then local item=decorationCatalog.ById(itemId); local anchor=anchorRoot:FindFirstChild(anchorId); local category= item and assets:FindFirstChild(item.CategoryId); local asset=category and category:FindFirstChild(item.AssetName); if not (item and anchor and anchor:IsA("BasePart") and asset and asset:IsA("Model")) then return false,"Decoration asset missing: "..tostring(itemId).."/"..tostring(anchorId) end; local clone=asset:Clone(); clone.Name=anchorId; for _,object in ipairs(clone:GetDescendants()) do if object:IsA("LuaSourceContainer") or object:IsA("ProximityPrompt") or object:IsA("Seat") or object:IsA("VehicleSeat") then object:Destroy() elseif object:IsA("BasePart") then local localCFrame=object.CFrame; object.CFrame=anchor.CFrame*localCFrame; object.Anchored=true; object.CanTouch=false; object.CanQuery=false; object.CanCollide=false; object.CastShadow=false end end; clone:SetAttribute("DecorationAnchorId",anchorId); clone:SetAttribute("DecorationItemId",itemId); clone:SetAttribute("DecorationPreview",session.DecorationPreview and session.DecorationPreview.AnchorId==anchorId or false); clone.Parent=runtime end end
		return true
	end
	local function applyLighting(profile,session)
		local property=profile.OwnedGarage.Properties[session.PropertyId]; local definition=catalog.ById(session.PropertyId); local lighting=lightingCatalog.Normalize(property and property.Customisation and property.Customisation.Lighting); if session.LightingPreview then lighting=session.LightingPreview end; local preset=lightingCatalog.ById(lighting.PresetId); local slots=session.Interior:FindFirstChild("LightingSlots"); if not (preset and slots) then return false,"Garage lighting contract is missing." end
		local assets=ServerStorage:FindFirstChild("NeoTokyoRacers"); assets=assets and assets:FindFirstChild("OwnedGarage"); assets=assets and assets:FindFirstChild("LightingAssets"); assets=assets and assets:FindFirstChild(tostring(definition and definition.TemplateId or "")); local asset=assets and assets:FindFirstChild(preset.AssetName); if not (asset and asset:IsA("Model")) then return false,"Garage lighting asset is missing." end
		local runtime=session.Interior:FindFirstChild("LightingRuntime"); if not runtime then runtime=Instance.new("Folder"); runtime.Name="LightingRuntime"; runtime.Parent=session.Interior end; runtime:ClearAllChildren(); local primary=lightingCatalog.DecodeColor(preset.PrimaryColor); local accent=lightingCatalog.DecodeColor(preset.AccentColor)
		for _,slotId in ipairs(definition and definition.LightingSlotIds or {}) do local slot=slots:FindFirstChild(slotId); if not (slot and slot:IsA("BasePart")) then return false,"Garage lighting slot missing: "..tostring(slotId) end; local clone=asset:Clone(); clone.Name=slotId; for _,object in ipairs(clone:GetDescendants()) do if object:IsA("LuaSourceContainer") or object:IsA("ProximityPrompt") or object:IsA("Seat") or object:IsA("VehicleSeat") then object:Destroy() elseif object:IsA("BasePart") then local localCFrame=object.CFrame; object.CFrame=slot.CFrame*localCFrame; object.Anchored=true; object.CanCollide=false; object.CanTouch=false; object.CanQuery=false; object.CastShadow=false; local channel=tostring(object:GetAttribute("LightingChannel") or "Primary"); object.Color=channel=="Accent" and accent or primary elseif object:IsA("PointLight") or object:IsA("SpotLight") or object:IsA("SurfaceLight") then object.Color=primary; object.Brightness=math.max(0,tonumber(preset.Brightness) or 1)*math.clamp(tonumber(lighting.Intensity) or 1,.5,1.5); object.Range=math.min(36,math.max(8,tonumber(preset.Range) or 28)); object.Shadows=false; object.Enabled=true end end; clone:SetAttribute("LightingPresetId",preset.PresetId); clone:SetAttribute("LightingPreview",session.LightingPreview~=nil); clone.Parent=runtime end
		return true
	end
	local function renderDisplays(player,profile,session)
		local property=profile.OwnedGarage.Properties[session.PropertyId]; local markers=session.Interior:FindFirstChild("DisplaySpaceMarkers"); if not markers then return false,"Display markers missing." end
		local definition=catalog.ById(session.PropertyId); for _,slotId in ipairs(definition and definition.DisplaySpaceIds or {}) do
			Display.Clear(session.Interior,slotId); local marker=markers:FindFirstChild(slotId); local prompt=marker and marker:FindFirstChild("DriveOutPrompt")
			if not prompt and marker then prompt=Instance.new("ProximityPrompt"); prompt.Name="DriveOutPrompt"; prompt.ActionText="Drive Out"; prompt.KeyboardKeyCode=Enum.KeyCode.E; prompt.GamepadKeyCode=Enum.KeyCode.ButtonX; prompt.HoldDuration=0; prompt.MaxActivationDistance=12; prompt.RequiresLineOfSight=false; prompt.ClickablePrompt=true; prompt.Parent=marker; table.insert(promptConnections[session.Interior],prompt.Triggered:Connect(function(triggeringPlayer) if triggeringPlayer==player then local result=driveOut(player,slotId); push:FireClient(player,{Type="DriveOutResult",Success=result.Success==true,Message=result.Message}) end end)) end
			local vehicleId=property.DisplaySpaces[slotId]; local available=vehicleId~=false and vehicleId~=nil and tostring(vehicleId)~=""; prompt:SetAttribute("OwnedGarageAvailable",available); prompt.ObjectText=available and vehicleName(profile,vehicleId) or "Empty Display Space"
			if available then local model,message=Display.Build(profile,tostring(vehicleId),marker,session.Interior); if not model then return false,message end end
		end; applyPromptPolicy(session); return true
	end
	local function configurePrompts(player,profile,session)
		promptConnections[session.Interior]=promptConnections[session.Interior] or {}; local list=promptConnections[session.Interior]
		-- NTR_LOADING_SYSTEM_PHASE3_OWNED_GARAGE_FOOT_EXIT_RESULT_V1
		local foot=session.Interior:FindFirstChild("FootExitPrompt",true)
		if foot then
			foot.HoldDuration=0; foot:SetAttribute("OwnedGarageAvailable",true)
			table.insert(list,foot.Triggered:Connect(function(triggeringPlayer)
				if triggeringPlayer==player then local result=exitOnFoot(player); push:FireClient(player,{Type="FootExitResult",Success=result.Success==true,Message=result.Message}) end
			end))
		end
		local desk=session.Interior:FindFirstChild("ManageGaragePrompt",true); if desk then desk.HoldDuration=0; desk:SetAttribute("OwnedGarageAvailable",true); table.insert(list,desk.Triggered:Connect(function(triggeringPlayer) if triggeringPlayer==player then push:FireClient(player,{Type="OpenManagement",PropertyId=session.PropertyId}) end end)) end
		return renderDisplays(player,profile,session)
	end
	local function ensureSession(player,profile,propertyId)
		if sessions[player] then return sessions[player] end; local definition=catalog.ById(propertyId); local property=profile.OwnedGarage.Properties[propertyId]; if not (definition and property and property.Owned) then return nil,"Garage is not owned." end
		if #pool:GetChildren()>=(tonumber(settings:GetAttribute("MaxActiveInteriorsPerServer")) or 24) then return nil,"Garage interiors are currently at capacity." end; local interior,message=Interior.Create(pool,player.UserId,propertyId,definition.TemplateId,slotIndex(player)); if not interior then return nil,message end; if tonumber(interior:GetAttribute("OwnedGarageTemplateVersion"))~=tonumber(definition.TemplateContractVersion) then interior:Destroy(); return nil,"Garage template version is incompatible." end; disconnectPrompts(interior)
		local session={Interior=interior,PropertyId=propertyId}; sessions[player]=session
		local styled,styleMessage=applyInteriorStyles(profile,session); if not styled then sessions[player]=nil; scheduleUnload(interior,player); return nil,styleMessage end; local decorated,decorationMessage=applyDecorations(profile,session); if not decorated then sessions[player]=nil; scheduleUnload(interior,player); return nil,decorationMessage end; local lit,lightingMessage=applyLighting(profile,session); if not lit then sessions[player]=nil; scheduleUnload(interior,player); return nil,lightingMessage end; local configured,configureMessage=configurePrompts(player,profile,session); if not configured then sessions[player]=nil; setInside(player,nil); scheduleUnload(interior,player); return nil,configureMessage end
		return session
	end
	local function abandonSession(player,session)
		if sessions[player]==session then sessions[player]=nil end; setInside(player,nil); if session and session.Interior then scheduleUnload(session.Interior,player) end
	end
	exitOnFoot=function(player)
		local session=sessions[player]; if not session then return {Success=false,Message="You are not inside an owned garage."} end; if session.Transition then return {Success=false,Message="Garage transition already in progress."} end; session.Transition="FootExit"; applyPromptPolicy(session)
		local destination,destinationMessage=exteriorCFrame(session.PropertyId,"FootExitSpawn"); if not destination then session.Transition=nil; applyPromptPolicy(session); return {Success=false,Message=destinationMessage} end
		local ok,message=teleportCharacter(player,destination); if not ok then session.Transition=nil; applyPromptPolicy(session); return {Success=false,Message=message} end; sessions[player]=nil; setInside(player,nil); scheduleUnload(session.Interior,player); return {Success=true,Message="Returned to the city."}
	end
	local function enterOnFoot(player,profile,propertyId)
		local driven=lifecycleCall("GetDrivenVehicle",player,{}); if driven.Success then return {Success=false,Message="Use Drive In while seated in your vehicle."} end
		local session,message=ensureSession(player,profile,propertyId); if not session then return {Success=false,Message=message} end; local spawn=session.Interior:FindFirstChild("CharacterSpawn",true); local ok,teleportMessage=teleportCharacter(player,spawn and spawn.CFrame); if not ok then abandonSession(player,session); return {Success=false,Message=teleportMessage} end
		setInside(player,session); return {Success=true,Message="Entered garage.",PropertyId=propertyId}
	end
	local function replacementSlots(profile,propertyId)
		local result={}; local display=profile.OwnedGarage.Properties[propertyId].DisplaySpaces; local definition=catalog.ById(propertyId); for _,slotId in ipairs(definition and definition.DisplaySpaceIds or {}) do local vehicleId=display[slotId]; table.insert(result,{SlotId=slotId,VehicleId=vehicleId,DisplayName=vehicleName(profile,vehicleId)}) end; return result
	end
	local function enterWithVehicle(player,profile,propertyId,replacementSlotId)
		local driven=lifecycleCall("GetDrivenVehicle",player,{}); if not driven.Success then return {Success=false,Message=driven.Message or "Drive a vehicle into the garage."} end
		if tonumber(driven.SpeedMph) and driven.SpeedMph>(tonumber(settings:GetAttribute("DriveInMaxSpeedMph")) or 5) then return {Success=false,Message="Slow below "..tostring(settings:GetAttribute("DriveInMaxSpeedMph") or 5).." MPH."} end
		local property=profile.OwnedGarage.Properties[propertyId]; if not (property and property.Owned) then return {Success=false,Message="Garage is not owned."} end
		local existingSlot; for candidate,assigned in pairs(property.DisplaySpaces or {}) do if tostring(assigned or "")==tostring(driven.VehicleId) then existingSlot=tostring(candidate); break end end
		local definition=catalog.ById(propertyId); local slotId,reason=existingSlot,"Existing"; if not slotId then slotId,reason=Runtime.ChooseSlot(property.DisplaySpaces,replacementSlotId,definition and definition.DisplaySpaceIds) end; if reason=="Invalid" then return {Success=false,Message="That display space is not part of this garage."} end; if not slotId then return {Success=false,NeedsReplacement=true,Message="Garage display spaces are full.",Slots=replacementSlots(profile,propertyId)} end
		local session,message=ensureSession(player,profile,propertyId); if not session then return {Success=false,Message=message} end; if not characterRoot(player) then abandonSession(player,session); return {Success=false,Message="Character is not ready."} end; session.Transition="DriveIn"; applyPromptPolicy(session)
		local before=Profile.Snapshot(profile); local despawn=lifecycleCall("DespawnForGarage",player,{VehicleId=driven.VehicleId,PreserveCharacterPosition=true,WaitForDetach=true,DetachTimeoutSeconds=settings:GetAttribute("GarageSeatDetachTimeoutSeconds")}); if not despawn.Success then if despawn.VehicleRemoved then lifecycleCall("SpawnFromGarage",player,{VehicleId=driven.VehicleId,SpawnCFrame=driven.VehicleCFrame}) end; abandonSession(player,session); return {Success=false,Message=despawn.Message or "Vehicle could not enter the garage."} end
		local result={Success=true,Revision=profile.OwnedGarage.Revision}; local changed=existingSlot==nil
		if changed then result=command(player,"Assign",{GarageId=propertyId,SlotId=slotId,VehicleId=driven.VehicleId},"OwnedGarageDriveIn",tostring(driven.RequestId or Profile.NewRequestId()),profile.OwnedGarage.Revision) end
		if type(result)~="table" or not result.Success then lifecycleCall("SpawnFromGarage",player,{VehicleId=driven.VehicleId,SpawnCFrame=driven.VehicleCFrame}); abandonSession(player,session); return type(result)=="table" and result or {Success=false,Message="Owned garage command unavailable."} end
		local spawn=session.Interior:FindFirstChild("CharacterSpawn",true); local moved,moveMessage=teleportCharacter(player,spawn and spawn.CFrame); if not moved then local restored=not changed or compensate(player,before,result.Revision,"OwnedGarageDriveInTeleportRollback"); if restored then lifecycleCall("SpawnFromGarage",player,{VehicleId=driven.VehicleId,SpawnCFrame=driven.VehicleCFrame}) end; abandonSession(player,session); return {Success=false,Message=restored and moveMessage or (moveMessage.." Saved assignment recovery also failed; vehicle remains stored.")} end
		session.Transition=nil; setInside(player,session); local committed=getProfile:Invoke(player); local rendered,renderMessage=false,"Committed profile unavailable."; if type(committed)=="table" then rendered,renderMessage=renderDisplays(player,committed,session) end; return {Success=true,Message=existingSlot and "Vehicle returned to its display space." or (reason=="Requested" and "Display vehicle replaced." or "Vehicle placed in garage."),PropertyId=propertyId,SlotId=slotId,Revision=result.Revision,PresentationWarning=rendered and nil or renderMessage}
	end
	driveOut=function(player,slotId)
		local session=sessions[player]; if not session then return {Success=false,Message="You are not inside an owned garage."} end; if session.Transition then return {Success=false,Message="Garage transition already in progress."} end; local profile,message=profileFor(player); if not profile then return {Success=false,Message=message} end; session.Transition="DriveOut"; applyPromptPolicy(session); local property=profile.OwnedGarage.Properties[session.PropertyId]; local vehicleId=property and property.DisplaySpaces[slotId]; if vehicleId==false or vehicleId==nil or tostring(vehicleId)=="" then session.Transition=nil; applyPromptPolicy(session); return {Success=false,Message="Display space is empty."} end
		local spawnCFrame,spawnMessage=exteriorCFrame(session.PropertyId,"VehicleExitSpawn"); if not spawnCFrame then session.Transition=nil; applyPromptPolicy(session); return {Success=false,Message=spawnMessage} end
		local before=Profile.Snapshot(profile); local result=command(player,"Clear",{GarageId=session.PropertyId,SlotId=slotId},"OwnedGarageDriveOut",Profile.NewRequestId(),profile.OwnedGarage.Revision); if type(result)~="table" or not result.Success then session.Transition=nil; applyPromptPolicy(session); return type(result)=="table" and result or {Success=false,Message="Owned garage command unavailable."} end
		local spawned=lifecycleCall("SpawnFromGarage",player,{VehicleId=tostring(vehicleId),SpawnCFrame=spawnCFrame}); if not spawned.Success then compensate(player,before,result.Revision,"OwnedGarageDriveOutSpawnRollback"); session.Transition=nil; applyPromptPolicy(session); local restored=getProfile:Invoke(player); if type(restored)=="table" then renderDisplays(player,restored,session) end; return {Success=false,Message=spawned.Message or "Vehicle could not leave the garage."} end
		sessions[player]=nil; setInside(player,nil); scheduleUnload(session.Interior,player); push:FireClient(player,{Type="DriveOut",VehicleId=tostring(vehicleId)}); return {Success=true,Message="Vehicle spawned from garage.",VehicleId=tostring(vehicleId),Revision=result.Revision}
	end
	local function managedOperation(player,profile,operation,args)
		local session=sessions[player]; if not session then return {Success=false,Message="Enter your garage before managing it."} end; args=type(args)=="table" and args or {}; args.GarageId=session.PropertyId; local required=(operation=="Assign" or operation=="Clear") and "DisplayCars" or ((operation=="SetSurfaceStyle" or operation=="ConfigureStructure") and "Structure" or (operation=="ConfigureDecoration" and "Decorations" or (operation=="ConfigureLighting" and "Lighting" or (operation=="SetAccessMode" and "Access" or (operation=="SetInvitation" and "Invitations"))))); if required and capabilities(session.PropertyId)[required]~=true then return {Success=false,Message=required.." is not enabled for this garage."} end
		local result=command(player,operation,args,"OwnedGarageManagement:"..operation,tostring(args.RequestId or Profile.NewRequestId()),args.BaseRevision); local committed=getProfile:Invoke(player); if type(committed)~="table" then return {Success=false,Message="Committed profile could not be read."} end
		if type(result)~="table" then return {Success=false,Message="Owned garage command unavailable."} elseif not result.Success then if operation=="Assign" or operation=="Clear" then renderDisplays(player,committed,session) elseif operation=="SetSurfaceStyle" or operation=="ConfigureStructure" then applyInteriorStyles(committed,session) elseif operation=="ConfigureDecoration" then applyDecorations(committed,session) elseif operation=="ConfigureLighting" then applyLighting(committed,session) end; return result end
		local presented,presentationMessage=true,nil; if operation=="Assign" or operation=="Clear" then presented,presentationMessage=renderDisplays(player,committed,session) elseif operation=="SetSurfaceStyle" or operation=="ConfigureStructure" then session.StructurePreview=nil; presented=applyInteriorStyles(committed,session) elseif operation=="ConfigureDecoration" then session.DecorationPreview=nil; presented=applyDecorations(committed,session) elseif operation=="ConfigureLighting" then session.LightingPreview=nil; presented=applyLighting(committed,session) end; if not presented then result.PresentationWarning=presentationMessage or "Saved state committed; physical presentation will retry." end
		stateCache[player]=nil; result.ManagementState=stateFor(player,committed); push:FireClient(player,{Type="ManagementUpdated",Operation=operation,Revision=result.Revision}); return result
	end
	local function clone(value) if type(value)~="table" then return value end; local copy={}; for key,child in pairs(value) do copy[key]=clone(child) end; return copy end
	local function vehicleSignature(profile)
		local parts={}; for vehicleId,vehicle in pairs(profile.Vehicles or {}) do if type(vehicle)=="table" then local cockpit=profile.OwnedCockpitInstances and profile.OwnedCockpitInstances[vehicle.CockpitInstanceId]; table.insert(parts,tostring(vehicleId)..":"..tostring((cockpit and cockpit.TemplateId) or vehicle.CockpitId or "")..":"..tostring(vehicle.DisplayName or "")) end end; table.sort(parts); return table.concat(parts,"|")
	end
	local function playerSignature()
		local ids={}; for _,candidate in ipairs(Players:GetPlayers()) do table.insert(ids,candidate.UserId) end; table.sort(ids); local parts={}; for _,id in ipairs(ids) do table.insert(parts,tostring(id)) end; return table.concat(parts,"|")
	end
	local function invitationRows(owner,property)
		local rows={}; local online={}; local invited={}; for _,id in ipairs(property and property.InvitedUserIds or {}) do invited[tonumber(id)]=true end
		for _,candidate in ipairs(Players:GetPlayers()) do if candidate~=owner then online[candidate.UserId]=true; table.insert(rows,{UserId=candidate.UserId,DisplayName=candidate.DisplayName,Username=candidate.Name,Online=true,Invited=invited[candidate.UserId]==true}) end end
		for userId in pairs(invited) do if not online[userId] then table.insert(rows,{UserId=userId,DisplayName="User "..userId,Username="OFFLINE",Online=false,Invited=true}) end end
		table.sort(rows,function(a,b) if a.Invited~=b.Invited then return a.Invited end; if a.Online~=b.Online then return a.Online end; return string.lower(a.DisplayName)<string.lower(b.DisplayName) end); return rows
	end
	stateFor=function(player,profile)
		local session=sessions[player]; local sessionPropertyId=session and session.PropertyId or ""; local revision=math.max(0,math.floor(tonumber(profile.OwnedGarage.Revision) or 0)); local cash=tonumber(profile.Cash or profile.Money or profile.Credits) or 0; local signature=vehicleSignature(profile); local playersSignature=playerSignature(); local cached=stateCache[player]
		if cached and cached.Revision==revision and cached.SessionPropertyId==sessionPropertyId and cached.VehicleSignature==signature and cached.PlayerSignature==playersSignature and cached.Cash==cash then local result=clone(cached.State); result.CacheHit=true; return result end
		local properties={}; for _,definition in ipairs(catalog.List()) do local property=profile.OwnedGarage.Properties[definition.PropertyId]; if property and property.Owned then local filled=0; for _,vehicleId in pairs(property.DisplaySpaces) do if vehicleId~=false and vehicleId~=nil and tostring(vehicleId)~="" then filled+=1 end end; table.insert(properties,{PropertyId=definition.PropertyId,DisplayName=definition.DisplayName,District=definition.District,Description=definition.Description,Image=definition.Image,TemplateId=definition.TemplateId,Capacity=#definition.DisplaySpaceIds,Filled=filled,Capabilities=definition.Capabilities,UI=definition.UI,Definition=catalog.ClientDefinition(definition.PropertyId)}) end end
		local currentProperty=session and profile.OwnedGarage.Properties[session.PropertyId]; local slots={}; local vehicles={}; local surfaceStyles={}
		if currentProperty then local definition=catalog.ById(session.PropertyId); for _,slotId in ipairs(definition and definition.DisplaySpaceIds or {}) do local vehicleId=currentProperty.DisplaySpaces[slotId]; table.insert(slots,{SlotId=slotId,VehicleId=vehicleId,DisplayName=(vehicleId and vehicleId~=false) and vehicleName(profile,vehicleId) or "Empty Display Space"}) end; for surfaceGroup,styleId in pairs(currentProperty.Customisation.SurfaceStyles or {}) do surfaceStyles[surfaceGroup]=styleId end end
		local presentation=lifecycleCall("GetOwnedGarageVehicleCards",player,{}); if presentation.Success then vehicles=presentation.Vehicles or {} else for vehicleId,vehicle in pairs(profile.Vehicles or {}) do if type(vehicle)=="table" then table.insert(vehicles,{VehicleId=tostring(vehicleId),DisplayName=vehicleName(profile,vehicleId),CockpitId=tostring(vehicle.CockpitId or ""),CategoryId=tostring(vehicle.CategoryId or profile.CurrentCategory or ""),Tier="E",Rating=0,Image=""}) end end end; local propertyNames={}; for _,definition in ipairs(catalog.List()) do propertyNames[definition.PropertyId]=definition.DisplayName end; for _,vehicle in ipairs(vehicles) do vehicle.UsedInOtherGarage=vehicle.DisplayedGarageId~=nil and vehicle.DisplayedGarageId~=sessionPropertyId; vehicle.DisplayedGarageName=vehicle.DisplayedGarageId and propertyNames[vehicle.DisplayedGarageId] or nil end
		table.sort(vehicles,function(a,b) if a.UsedInOtherGarage~=b.UsedInOtherGarage then return not a.UsedInOtherGarage end; if a.Rating~=b.Rating then return a.Rating>b.Rating end; return a.DisplayName<b.DisplayName end)
		local state={Success=true,ApiVersion=catalog.StateApiVersion,DefinitionVersion=catalog.DefinitionVersion,Revision=revision,Properties=properties,ActiveGarageId=profile.OwnedGarage.ActiveGarageId,InGarage=session~=nil,CurrentPropertyId=session and session.PropertyId or nil,Slots=slots,Vehicles=vehicles,SurfaceStyles=surfaceStyles,InteriorStyles=styleCatalog.List(),AccessModes=catalog.AccessModes(),DecorationCategories=catalog.DecorationCategories(),Decorations=currentProperty and decorationCatalog.ClientState(currentProperty.Customisation.Decorations,(catalog.ById(session.PropertyId) or {}).DecorationAnchorIds or {}) or nil,Lighting=currentProperty and lightingCatalog.ClientState(currentProperty.Customisation.Lighting) or nil,Structure= currentProperty and styleCatalog.ClientState(currentProperty.Customisation.Structure,(catalog.ById(session.PropertyId) or {}).StructureSections or {}) or nil,Capabilities=session and capabilities(session.PropertyId) or {},AccessMode=currentProperty and currentProperty.AccessMode or "Private",InvitationRows=currentProperty and invitationRows(player,currentProperty) or {},InvitationsEnabled=session and capabilities(session.PropertyId).Invitations==true,VisitorsEnabled=false,Cash=cash,CacheHit=false}
		stateCache[player]={Revision=revision,SessionPropertyId=sessionPropertyId,VehicleSignature=signature,PlayerSignature=playersSignature,Cash=cash,State=clone(state)}; return state
	end
	invoke.OnServerInvoke=function(player,action,args)
		args=type(args)=="table" and args or {}; if not allowRequest(player,action) then return {Success=false,Message="Garage requests are arriving too quickly.",RateLimited=true} end; if locks[player] then return {Success=false,Message="Garage transition already in progress."} end; local now=os.clock(); local controlAction=action=="GetState" or action=="GetManagementState" or action=="SetManagementOpen" or action=="PreviewDisplay" or action=="CancelDisplayPreview" or action=="PreviewStructure" or action=="CancelStructurePreview" or action=="PreviewDecoration" or action=="CancelDecorationPreview" or action=="PreviewLighting" or action=="CancelLightingPreview"; if not controlAction and now-(lastRequest[player] or 0)<(tonumber(settings:GetAttribute("TransitionCooldownSeconds")) or 1) then return {Success=false,Message="Garage transition is cooling down."} end
		locks[player]=true; local ok,result=pcall(function()
			local profile,message=profileFor(player); if not profile then return {Success=false,Message=message} end; local propertyId=tostring(args.PropertyId or profile.OwnedGarage.ActiveGarageId or "STARTER_TWO_BAY")
			if action=="GetState" or action=="GetManagementState" then return stateFor(player,profile)
			elseif action=="SetManagementOpen" then local session=sessions[player]; if not session then return {Success=false,Message="Garage session is not active."} end; session.ManagementOpen=args.Open==true; applyPromptPolicy(session); return {Success=true,Message="Management prompt policy updated."}
			elseif action=="PreviewDisplay" then local session=sessions[player]; if not session or capabilities(session.PropertyId).DisplayCars~=true then return {Success=false,Message="Display preview is unavailable."} end; local slotId=tostring(args.SlotId or ""); local vehicleId=tostring(args.VehicleId or ""); if not catalog.IsSpace(session.PropertyId,slotId) or not (profile.Vehicles and profile.Vehicles[vehicleId]) then return {Success=false,Message="Display preview is invalid."} end; local marker=session.Interior:FindFirstChild("DisplaySpaceMarkers") and session.Interior.DisplaySpaceMarkers:FindFirstChild(slotId); if not marker then return {Success=false,Message="Display marker missing."} end; local property=profile.OwnedGarage.Properties[session.PropertyId]; for otherSlot,displayedId in pairs(property and property.DisplaySpaces or {}) do if tostring(displayedId or "")==vehicleId and tostring(otherSlot)~=slotId then Display.Clear(session.Interior,tostring(otherSlot)) end end; Display.Clear(session.Interior,slotId); local model,previewMessage=Display.Build(profile,vehicleId,marker,session.Interior); if not model then renderDisplays(player,profile,session); return {Success=false,Message=previewMessage} end; session.PreviewSlotId=slotId; return {Success=true,Message="Preview ready."}
			elseif action=="CancelDisplayPreview" then local session=sessions[player]; if not session then return {Success=false,Message="Garage session is not active."} end; session.PreviewSlotId=nil; local rendered,renderMessage=renderDisplays(player,profile,session); return {Success=rendered==true,Message=renderMessage or "Display preview cleared."}
			elseif action=="PreviewStructure" then local session=sessions[player]; local definition=session and catalog.ById(session.PropertyId); local section=tostring(args.SectionId or ""); local style=definition and styleCatalog.ById(section,args.StyleId); if not (session and style) then return {Success=false,Message="Structure preview is invalid."} end; session.StructurePreview={SectionId=section,StyleId=style.StyleId,Colors=style.Colors,Materials=style.Materials}; applyInteriorStyles(profile,session); return {Success=true,Message="Structure preview ready."}
			elseif action=="CancelStructurePreview" then local session=sessions[player]; if not session then return {Success=false,Message="Garage session is not active."} end; session.StructurePreview=nil; applyInteriorStyles(profile,session); return {Success=true,Message="Structure preview cleared."}
			elseif action=="PreviewDecoration" then local session=sessions[player]; local definition=session and catalog.ById(session.PropertyId); local anchorId=tostring(args.AnchorId or ""); local item=decorationCatalog.ById(args.ItemId); if not (session and item and decorationCatalog.IsAnchor(anchorId,definition and definition.DecorationAnchorIds)) then return {Success=false,Message="Decoration preview is invalid."} end; session.DecorationPreview={AnchorId=anchorId,ItemId=item.ItemId}; local rendered,message=applyDecorations(profile,session); return {Success=rendered==true,Message=message or "Decoration preview ready."}
			elseif action=="CancelDecorationPreview" then local session=sessions[player]; if not session then return {Success=false,Message="Garage session is not active."} end; session.DecorationPreview=nil; local rendered,message=applyDecorations(profile,session); return {Success=rendered==true,Message=message or "Decoration preview cleared."}
			elseif action=="PreviewLighting" then local session=sessions[player]; if not session then return {Success=false,Message="Garage session is not active."} end; local property=profile.OwnedGarage.Properties[session.PropertyId]; local lighting=lightingCatalog.Normalize(property.Customisation.Lighting); local preset=lightingCatalog.ById(args.PresetId or lighting.PresetId); if not preset then return {Success=false,Message="Lighting preview is invalid."} end; session.LightingPreview={PresetId=preset.PresetId,OwnedPresets=lighting.OwnedPresets,Intensity=lightingCatalog.Level(args.Intensity or lighting.Intensity).Value}; local rendered,message=applyLighting(profile,session); return {Success=rendered==true,Message=message or "Lighting preview ready."}
			elseif action=="CancelLightingPreview" then local session=sessions[player]; if not session then return {Success=false,Message="Garage session is not active."} end; session.LightingPreview=nil; local rendered,message=applyLighting(profile,session); return {Success=rendered==true,Message=message or "Lighting preview cleared."}
			elseif action=="EnterSelectedGarage" then local driven=lifecycleCall("GetDrivenVehicle",player,{}); if driven.Success then return enterWithVehicle(player,profile,propertyId,args.ReplacementSlotId) end; return enterOnFoot(player,profile,propertyId)
			elseif action=="EnterOnFoot" then return enterOnFoot(player,profile,propertyId)
			elseif action=="EnterWithVehicle" then return enterWithVehicle(player,profile,propertyId,args.ReplacementSlotId)
			elseif action=="ExitOnFoot" then return exitOnFoot(player)
			elseif action=="DriveOut" then return driveOut(player,tostring(args.SlotId or ""))
			elseif action=="AssignDisplay" then return managedOperation(player,profile,"Assign",{SlotId=tostring(args.SlotId or ""),VehicleId=tostring(args.VehicleId or ""),RequestId=args.RequestId,BaseRevision=args.BaseRevision})
			elseif action=="ClearDisplay" then return managedOperation(player,profile,"Clear",{SlotId=tostring(args.SlotId or ""),RequestId=args.RequestId,BaseRevision=args.BaseRevision})
			elseif action=="SetInteriorStyle" then return managedOperation(player,profile,"SetSurfaceStyle",{SurfaceGroup=tostring(args.SurfaceGroup or ""),StyleId=tostring(args.StyleId or ""),RequestId=args.RequestId,BaseRevision=args.BaseRevision})
			elseif action=="ConfigureStructure" then return managedOperation(player,profile,"ConfigureStructure",{SectionId=tostring(args.SectionId or ""),Action=tostring(args.Action or ""),StyleId=tostring(args.StyleId or ""),Channel=tostring(args.Channel or ""),Material=tostring(args.Material or ""),Color=args.Color,RequestId=args.RequestId,BaseRevision=args.BaseRevision})
			elseif action=="ConfigureDecoration" then return managedOperation(player,profile,"ConfigureDecoration",{AnchorId=tostring(args.AnchorId or ""),ItemId=tostring(args.ItemId or ""),Action=tostring(args.Action or ""),RequestId=args.RequestId,BaseRevision=args.BaseRevision})
			elseif action=="ConfigureLighting" then return managedOperation(player,profile,"ConfigureLighting",{Action=tostring(args.Action or ""),PresetId=tostring(args.PresetId or ""),Intensity=args.Intensity,RequestId=args.RequestId,BaseRevision=args.BaseRevision})
			elseif action=="SetInvitation" then return managedOperation(player,profile,"SetInvitation",{Action=tostring(args.Action or ""),TargetUserId=tonumber(args.TargetUserId),OwnerUserId=player.UserId,MaxInvites=settings:GetAttribute("MaxGarageInvitations"),RequestId=args.RequestId,BaseRevision=args.BaseRevision})
			elseif action=="SetAccessMode" then return managedOperation(player,profile,"SetAccessMode",{AccessMode=tostring(args.AccessMode or ""),RequestId=args.RequestId,BaseRevision=args.BaseRevision}) end
			return {Success=false,Message="Unknown owned garage action."}
		end)
		locks[player]=nil; if not controlAction then lastRequest[player]=now end; if ok and type(result)=="table" then return result end; warn("[NTR Owned Garage] "..tostring(result)); return {Success=false,Message="Owned garage request failed."}
	end
	-- NTR_OWNED_GARAGE_PHASE6_CHARACTER_CLEANUP_V1
	local function watchCharacter(player,character) local humanoid=character:FindFirstChildOfClass("Humanoid") or character:WaitForChild("Humanoid",10); if humanoid then humanoid.Died:Connect(function() local session=sessions[player]; if session then abandonSession(player,session) end end) end end
	Players.PlayerAdded:Connect(function(player) player.CharacterAdded:Connect(function(character) watchCharacter(player,character) end); if player.Character then task.spawn(watchCharacter,player,player.Character) end end); for _,player in ipairs(Players:GetPlayers()) do player.CharacterAdded:Connect(function(character) watchCharacter(player,character) end); if player.Character then task.spawn(watchCharacter,player,player.Character) end end
	Players.PlayerRemoving:Connect(function(player) local session=sessions[player]; sessions[player]=nil; locks[player]=nil; lastRequest[player]=nil; stateCache[player]=nil; requestWindows[player]=nil; Assignment.ForgetPlayer(player); slotByUserId[player.UserId]=nil; setInside(player,nil); if session and session.Interior then disconnectPrompts(session.Interior); session.Interior:Destroy() end end)
	started=true; print("[NTR Owned Garage] Management runtime active."); return true,"Started"
end
return Runtime
