"""Guarded installer for the realism retune of the Continuous looks in Space Racers v3.
Before values come from backup/before.json (the fallback); after values from looks.json.
Reuses the continuous-lighting installer engine. Modes: AUDIT, APPLY, ROLLBACK."""
import json
from pathlib import Path
HERE = Path(__file__).resolve().parent
before = json.loads((HERE / 'backup/before.json').read_text(encoding='utf8'))
looks = json.loads((HERE / 'looks.json').read_text(encoding='utf8'))
assert before['place_id'] == 93959280828322 and before['mode'] == 'Edit'
CFG = ['ReplicatedStorage', 'Config', 'World', 'Lighting']
def child(node, name):
    found = [c for c in node['children'] if c['name'] == name]
    assert len(found) == 1, name
    return found[0]
presets = child(before['config'], 'ContinuousPresets')
def lua(v):
    if type(v) is bool: return str(v).lower()
    if type(v) in (int, float): return repr(v)
    if isinstance(v, str): return json.dumps(v)
    if isinstance(v, list): return '{' + ','.join(lua(x) for x in v) + '}'
    if v.get('Type') == 'Color3': return 'Color3.new(%r,%r,%r)' % (v['R'], v['G'], v['B'])
    return '{' + ','.join('[%s]=%s' % (lua(k), lua(x)) for k, x in v.items()) + '}'
ops, summary = [], {}
for look, sections in looks.items():
    if look.startswith('_'): continue
    for section, values in sections.items():
        old = child(child(presets, look), section)['attributes']
        for key, value in values.items():
            assert key in old, (look, section, key)
            prev = old[key]
            if isinstance(value, list):
                assert isinstance(prev, dict) and prev['Type'] == 'Color3' and len(value) == 3 and all(0 <= c <= 255 for c in value)
                after = dict(Type='Color3', R=value[0] / 255, G=value[1] / 255, B=value[2] / 255)
                changed = any(abs(after[c] - prev[c]) > 1e-4 for c in 'RGB')
                shown = [[round(prev[c] * 255) for c in 'RGB'], value]
            else:
                assert type(prev) in (int, float) and type(value) in (int, float), (look, section, key)
                after = value; changed = abs(prev - value) > 1e-7; shown = [round(prev, 4), value]
            if changed:
                ops.append(dict(kind='attribute', path=CFG + ['ContinuousPresets', look, section], class_name='Folder', key=key, before=prev, after=after))
                summary['%s.%s.%s' % (look, section, key)] = shown
bundle = dict(placeId=before['place_id'], beforeCapture='scripts/lighting_realism/backup/before.json @ ' + before['taken_utc'], operations=ops, guards=[])
engine = (HERE.parent / 'continuous_lighting/installer_engine.lua').read_text(encoding='utf8')
text = '-- Generated by scripts/lighting_realism/build.py. Attribute-only; ROLLBACK restores backup/before.json values.\nlocal bundle=' + lua(bundle) + '\nlocal run=(function()\n' + engine + '\nend)()\nreturn function(mode) assert(mode=="AUDIT" or mode=="APPLY" or mode=="ROLLBACK","Use AUDIT, APPLY or ROLLBACK") return run(mode) end\n'
(HERE / 'install.lua').write_text(text, encoding='utf8', newline='\n')
(HERE / 'changes.json').write_text(json.dumps(summary, indent=1) + '\n', encoding='utf8', newline='\n')
print(json.dumps(dict(operations=len(ops), installer_bytes=len(text))))
