-- NTR_SHARED_RESPONSIVE_UI_FOUNDATION_V1_1
-- NTR_OWNED_GARAGE_WORKSPACE_CONTROLLER_V4_CANONICAL_VERTICAL_SLICE
-- NTR_PRESENTATION_AUDIO_OWNED_GARAGE_OUTCOMES_V1
-- NTR_PRESENTATION_AUDIO_OWNED_GARAGE_SEMANTIC_CUES_V1_3
-- NTR_OWNED_GARAGE_WORKSPACE_CONTROLLER_V5_REFRESH_OWNER
-- NTR_OWNED_GARAGE_WORKSPACE_CONTROLLER_V6_EXPLICIT_DISPLAY_COMMIT
-- NTR_OWNED_GARAGE_WORKSPACE_CONTROLLER_V7_AUTHORITATIVE_SELECTED_ACTION
-- NTR_OWNED_GARAGE_STRUCTURE_UI_V1
-- NTR_OWNED_GARAGE_STRUCTURE_UI_V1_1_CAPABILITY_ASSETS
-- NTR_OWNED_GARAGE_DECORATION_UI_V1
-- NTR_OWNED_GARAGE_LIGHTING_UI_V1
-- NTR_OWNED_GARAGE_ACCESS_INVITATIONS_UI_V1
-- NTR_OWNED_GARAGE_SHARED_FINISH_UI_V1
-- NTR_OWNED_GARAGE_PHASE13_V1_1_ATTRIBUTE_PLATFORM_UI
-- NTR_OWNED_GARAGE_PHASE13_V1_3_AUTHORED_DEFAULTS_MATERIAL_TABS
-- NTR_OWNED_GARAGE_PHASE14_V1_LIGHTING_STATE_FOUNDATION
-- NTR_OWNED_GARAGE_PHASE14_V2_SHARED_BUILD_STYLE_FLOW
-- NTR_OWNED_GARAGE_PHASE14_V2_1_SHARED_CATEGORY_CARD_PARITY
-- NTR_OWNED_GARAGE_PHASE14_V2_2_RESPONSIVE_NAVIGATION_CLOSURE
-- NTR_OWNED_GARAGE_ICON_CONFIG_V1
-- NTR_OWNED_GARAGE_ICON_CONFIG_V1_1_LOCATION_SCALE
-- NTR_OWNED_GARAGE_STYLE_UX_V1_BATCH_STABLE_PREVIEW
-- NTR_OWNED_GARAGE_MATERIAL_ICON_SIZE_V1
-- NTR_OWNED_GARAGE_LIGHTING_CHANNELS_DECORATION_FLOW_V1
local Controller={}; local started=false; local closeCurrent=function() end; local isOpenCurrent=function() return false end
function Controller.Close(reason) closeCurrent(reason) end
function Controller.IsOpen() return isOpenCurrent() end
function Controller.Start()
	if started then return true,"AlreadyStarted" end
	local Players=game:GetService("Players"); local ReplicatedStorage=game:GetService("ReplicatedStorage"); local HttpService=game:GetService("HttpService"); local player=Players.LocalPlayer; local playerGui=player:WaitForChild("PlayerGui")
	local kit=ReplicatedStorage:WaitForChild("NeoTokyoRacers"); local AudioBridge=require(kit.Shared.Modules.Client.Audio:WaitForChild("PresentationAudioBridge")); local uiFolder=script.Parent; local WorkspaceUI=require(uiFolder:WaitForChild("GarageWorkspaceController")); local Shared=require(uiFolder:WaitForChild("GarageReplacementComponents")); local UI=require(kit.Shared.Modules.UI:WaitForChild("RacingUIComponents")); local remote=kit.Shared.Remotes.Garage:WaitForChild("OwnedGarageInvoke"); local push=kit.Shared.Remotes.Garage:WaitForChild("OwnedGarageEvent"); local openEvent=uiFolder:WaitForChild("OpenOwnedGarageWorkspace"); local cfg=kit.Config.Runtime:WaitForChild("OwnedGarage_EditAttributes"); local replacement=kit.Config.UI:WaitForChild("GarageReplacement"); local navIcons=replacement:WaitForChild("NavigationIcons"); local icons=replacement:WaitForChild("OwnedGarageIcons")
	local workspace=WorkspaceUI.new(); workspace.Root.Name="OwnedGarageCanonicalWorkspace"
	local state; local page="Home"; local selectedSlot; local selectedVehicle; local selectedSection="FrontWall"; local selectedStyle; local selectedChannel="Primary"; local selectedDecorationCategory; local selectedDecorationAnchor; local selectedDecorationItem; local pendingStructureColors; local pendingStructureMaterials; local pendingDecorationColors; local pendingLightingColors; local selectedLightingPreset; local selectedLightingIntensity; local selectedInviteUserId; local previewReady=false; local previewGeneration=0; local busy=false; local refreshRunning=false; local queuedRevision; local generation=0; local modal
	local tierColours={E=Color3.fromRGB(132,142,145),D=Color3.fromRGB(105,190,129),C=Color3.fromRGB(74,204,211),B=Color3.fromRGB(82,137,235),A=Color3.fromRGB(244,188,65),S=Color3.fromRGB(236,92,168)}
	local function asset(value) return UI.Asset(value or "") end
	local function copy(value) if type(value)~="table" then return value end; local result={}; for key,child in pairs(value) do result[key]=copy(child) end; return result end
	local function first(list,fallback) return type(list)=="table" and list[1] or fallback end
	local function subset(values,channels) local result={}; for _,channel in ipairs(channels or {}) do if values and values[channel]~=nil then result[channel]=values[channel] end end; return result end
	local function union(list,key) local result,seen={},{}; for _,entry in ipairs(list or {}) do for _,channel in ipairs(entry and entry[key] or {}) do if not seen[channel] then seen[channel]=true; table.insert(result,channel) end end end; return result end
	local function aggregate(list,key,channels) local values,mixed={},{}; for _,channel in ipairs(channels or {}) do local value; local set=false; for _,entry in ipairs(list or {}) do if table.find(entry and entry[key=="Colors" and "ColourChannels" or "MaterialChannels"] or {},channel) then local candidate=entry[key] and entry[key][channel]; if not set then value=candidate; set=true elseif value~=candidate then mixed[channel]=true end end end; if set and not mixed[channel] then values[channel]=value end end; return values,mixed end
	local iconContract={ModeDisplayCars={"Modes","DisplayCars","OwnedModulesIcon"},ModeBuildGarage={"Modes","BuildGarage","BuildModulesIcon"},ModeStyleGarage={"Modes","StyleGarage","CustomiseModulesIcon"},FamilyStructure={"Families","Structure","BuildModulesIcon"},FamilyDecorations={"Families","Decorations","CustomiseModulesIcon"},FamilyLighting={"Families","Lighting","BuyModulesIcon"},NavigationBack={"Navigation","Back","BackIcon"},NavigationExit={"Navigation","Exit","ExitIcon"},NavigationSave={"Navigation","Save"},ActionColour={"Actions","Colour"},ActionMaterial={"Actions","Material"},StateLocked={"States","Locked","ModuleLockIcon"},EconomyCapacity={"Economy","Capacity"}}
	local function folderIcon(group,key) local folder=icons:FindFirstChild(group); local value=folder and folder:GetAttribute(key); return type(value)=="string" and value~="" and asset(value) or "" end
	local function namedIcon(name) local definition=iconContract[name]; if not definition then return "" end; local value=folderIcon(definition[1],definition[2]); if value~="" then return value end; local legacy=definition[3]; return legacy and asset(navIcons:GetAttribute(legacy)) or "" end
	local function scopedIcon(group,key,fallback) local value=folderIcon(group,key); return value~="" and value or namedIcon(fallback) end
	local function navIcon(name) return namedIcon("Navigation"..name) end
	local function categoryCardImageZoom() return math.clamp(tonumber(cfg:GetAttribute("OwnedGarageCategoryCardImageZoom")) or .5,.2,1.2) end	local iconSizing=icons:WaitForChild("Sizing")
	local function locationIconZoom(name) return math.clamp(tonumber(iconSizing:GetAttribute(name)) or categoryCardImageZoom()*2,.2,1.5) end
	local function materialIconZoom() return math.clamp(tonumber(iconSizing:GetAttribute("MaterialImageZoom")) or 1,.2,1.5) end
	local function request(action,args) local startedAt=os.clock(); local ok,result=pcall(function() return remote:InvokeServer(action,args or {}) end); if cfg:GetAttribute("DebugTimingEnabled")==true then print("[NTR Owned Garage Timing] action="..action.." remoteMs="..math.floor((os.clock()-startedAt)*1000+.5)) end; if ok and type(result)=="table" then local economy=Shared.ProjectEconomy(result,state and {Cash=state.Cash} or nil); result.ProjectedEconomy=economy; if state and economy.Cash then state.Cash=economy.Cash end; return result end; return {Success=false,Message="Garage management is unavailable."} end
	local function property() for _,item in ipairs(state and state.Properties or {}) do if item.PropertyId==state.CurrentPropertyId then return item end end; return state and state.Properties and state.Properties[1] end
	local function vehicle(id) for _,item in ipairs(state and state.Vehicles or {}) do if item.VehicleId==tostring(id or "") then return item end end end
	local function slot(id) for _,item in ipairs(state and state.Slots or {}) do if item.SlotId==tostring(id or "") then return item end end end
	local function closeModal() if modal then modal:Destroy(); modal=nil end end
	local function setManagementOpen(open) playerGui:SetAttribute("NTR_OwnedGarageManagementOpen",open==true) end
	local function cancelPreview() previewGeneration+=1; previewReady=false; selectedVehicle=nil; if state and state.InGarage then task.spawn(function() request("CancelAllPreviews",{}) end) end end
	local function close() generation+=1; closeModal(); setManagementOpen(false); workspace:Hide(); if state and state.InGarage then task.spawn(function() request("CancelAllPreviews",{}); request("SetManagementOpen",{Open=false}) end) end end
	closeCurrent=close; isOpenCurrent=function() return workspace.Root.Visible end
	local function refresh(token)
		if refreshRunning then return false end
		refreshRunning=true; local result=request("GetManagementState",{}); refreshRunning=false
		if token~=generation then return false end
		if not result.Success then workspace:Message(result.Message or "Garage state could not be refreshed. Please try again."); return false end
		if not result.InGarage then workspace:Message(result.Message or "Management requires an active garage interior."); close(); return false end
		state=result
		if queuedRevision and tonumber(queuedRevision) and tonumber(queuedRevision)<=tonumber(state.Revision or 0) then queuedRevision=nil end
		return true
	end
	local render
	local function operate(action,args,nextPage,expectedSlotId,expectedVehicleId,successMessage,quietSuccess)
		if busy then return end; args=type(args)=="table" and args or {}; args.BaseRevision=state and state.Revision or nil; args.RequestId=HttpService:GenerateGUID(false); busy=true; workspace:Message("SAVING GARAGE..."); local result=request(action,args); busy=false
		local audioKind
		if action=="AssignDisplay" then audioKind=result.Success==true and "VehiclePurchase" or "Equip"
		elseif action=="ConfigureStructure" then audioKind=args.Action=="Purchase" and "StructurePurchase" or (args.Action=="Equip" and "StructureEquip" or nil)
		elseif action=="ConfigureDecoration" then audioKind=args.Action=="Purchase" and "DecorationPurchase" or (args.Action=="Place" and "DecorationEquip" or nil) end
		if audioKind then AudioBridge.Result(audioKind,result,{Action=action}) end
		if not result.Success then if result.Conflict then local token=generation; if refresh(token) then render(true) end end; workspace:Message(result.Message or "Garage update failed."); return end
		local committedState=type(result.ManagementState)=="table" and result.ManagementState or nil
		if expectedSlotId and expectedVehicleId then
			local committed=false
			if committedState then for _,space in ipairs(committedState.Slots or {}) do if tostring(space.SlotId or "")==tostring(expectedSlotId) and tostring(space.VehicleId or "")==tostring(expectedVehicleId) then committed=true; break end end
			else local raw=result.State; local propertyState=raw and raw.Properties and raw.Properties[state and state.CurrentPropertyId]; committed=propertyState and propertyState.DisplaySpaces and tostring(propertyState.DisplaySpaces[expectedSlotId] or "")==tostring(expectedVehicleId) end
			if not committed then workspace:Message("Display was not committed. Your saved garage was left unchanged."); return end
		end
		if committedState and committedState.Success then state=committedState; queuedRevision=nil; page=nextPage or page; previewReady=false; selectedVehicle=nil; render(true); if not quietSuccess then workspace:Message(successMessage or "VEHICLE DISPLAYED") end
		else local token=generation; if refresh(token) then queuedRevision=nil; page=nextPage or page; previewReady=false; selectedVehicle=nil; render(true); if not quietSuccess then workspace:Message(successMessage or "VEHICLE DISPLAYED") end end end
	end
	local function preview(vehicleId)
		if busy or not selectedSlot then return end
		previewGeneration+=1; local previewToken=previewGeneration; local token=generation; local requestedVehicle=tostring(vehicleId or ""); local requestedSlot=selectedSlot; previewReady=false; selectedVehicle=nil; workspace:Message("LOADING VEHICLE PREVIEW...")
		task.spawn(function()
			local result=request("PreviewDisplay",{SlotId=requestedSlot,VehicleId=requestedVehicle})
			if token~=generation or previewToken~=previewGeneration or page~="DisplayVehicles" then return end
			if not result.Success then workspace:Message(result.Message or "Vehicle preview failed."); render(false); return end
			selectedVehicle=requestedVehicle; previewReady=true; render(false)
		end)
	end
	local function confirmUsedElsewhere(item,onYes)
		closeModal(); modal=Shared.ConfirmationModal(workspace.Root,{Title="VEHICLE ALREADY DISPLAYED",Body="This vehicle is displayed in "..tostring(item.DisplayedGarageName or "another garage")..". Move it here?",ConfirmText="CONTINUE",CancelText="CANCEL",OnConfirm=function() modal=nil; onYes() end,OnCancel=function() modal=nil end})
	end
	local function modeForPage()
		if page=="Home" then return "Home" elseif page=="DisplaySpaces" or page=="DisplayVehicles" then return "DisplayCars" elseif string.sub(page,1,5)=="Build" then return "BuildGarage" elseif string.sub(page,1,5)=="Style" then return "StyleGarage" end; return "DisplayCars"
	end
	local function setMode(mode)
		cancelPreview(); selectedStyle=nil; selectedDecorationItem=nil; pendingStructureColors=nil; pendingStructureMaterials=nil; pendingDecorationColors=nil; pendingLightingColors=nil
		if mode=="DisplayCars" then page="DisplaySpaces" elseif mode=="BuildGarage" then page="Build" elseif mode=="StyleGarage" then page="Style" else page="Home" end; render(true)
	end
	local function modeTabs()
		local active=modeForPage(); local definitions={{Id="DisplayCars",Text="Display Cars",Image=namedIcon("ModeDisplayCars")},{Id="BuildGarage",Text="Build Garage",Image=namedIcon("ModeBuildGarage")},{Id="StyleGarage",Text="Style Garage",Image=namedIcon("ModeStyleGarage")}}; local result={}
		for _,definition in ipairs(definitions) do local item=definition; table.insert(result,{Id=item.Id,Text=item.Text,Image=item.Image,ImageZoom=categoryCardImageZoom(),Selected=active==item.Id,OnSelect=function() setMode(item.Id) end}) end; return result
	end
	local function beginDecorationStyle(anchor)
		selectedDecorationAnchor=anchor
		selectedDecorationItem=nil
		pendingDecorationColors=nil
		local decorations=state and state.Decorations or {}
		local all=anchor=="__ALL_DECORATIONS"
		local placement=not all and decorations.Placements and decorations.Placements[anchor]
		local placements={}
		if all then for _,entry in pairs(decorations.Placements or {}) do if entry then table.insert(placements,entry) end end else placements={placement} end
		local channels=all and union(placements,"ColourChannels") or (placement and placement.ColourChannels or {})
		if (all or placement) and #channels>0 then
			selectedChannel=first(channels,"Primary")
			if all then pendingDecorationColors=aggregate(placements,"Colors",channels) else pendingDecorationColors=copy(placement.Colors or {}) end
			page="StyleDecorationsColour"
		else
			page="StyleDecorations"
		end
	end
	local function locationTabs()
		local result={}; local structure=state and state.Structure or {}; local decorations=state and state.Decorations or {}
		if string.sub(page,1,14)=="BuildStructure" or string.sub(page,1,14)=="StyleStructure" then
			local styleMode=string.sub(page,1,5)=="Style"; if styleMode then table.insert(result,{Id="__ALL_STRUCTURE",Text="All Structure",Image=scopedIcon("StructureLocations","AllStructure","FamilyStructure"),ImageZoom=locationIconZoom("StructureLocationImageZoom"),Selected=selectedSection=="__ALL_STRUCTURE",OnSelect=function() request("CancelStructurePreview",{}); selectedSection="__ALL_STRUCTURE"; pendingStructureColors=nil; pendingStructureMaterials=nil; page="StyleStructure"; render(true) end}) end; for _,entry in ipairs(structure.Sections or {}) do local section=entry; table.insert(result,{Id=section.Id,Text=section.Name,Image=scopedIcon("StructureLocations",section.Id,"FamilyStructure"),ImageZoom=locationIconZoom("StructureLocationImageZoom"),Selected=selectedSection==section.Id,OnSelect=function() request("CancelStructurePreview",{}); selectedSection=section.Id; selectedStyle=nil; pendingStructureColors=nil; pendingStructureMaterials=nil; page=styleMode and "StyleStructure" or "BuildStructure"; render(true) end}) end
		elseif string.sub(page,1,16)=="BuildDecorations" or string.sub(page,1,16)=="StyleDecorations" then
			local styleMode=string.sub(page,1,5)=="Style"; if styleMode then table.insert(result,{Id="__ALL_DECORATIONS",Text="All Decorations",Image=scopedIcon("DecorationLocations","AllDecorations","FamilyDecorations"),ImageZoom=locationIconZoom("DecorationLocationImageZoom"),Selected=selectedDecorationAnchor=="__ALL_DECORATIONS",OnSelect=function() request("CancelDecorationPreview",{}); beginDecorationStyle("__ALL_DECORATIONS"); render(true) end}) end; for _,entry in ipairs(decorations.Zones or {}) do local zone=entry; table.insert(result,{Id=zone.SlotId,Text=zone.DisplayName,Image=scopedIcon("DecorationLocations",zone.SlotId,"FamilyDecorations"),ImageZoom=locationIconZoom("DecorationLocationImageZoom"),Selected=selectedDecorationAnchor==zone.SlotId,OnSelect=function() request("CancelDecorationPreview",{}); if styleMode then beginDecorationStyle(zone.SlotId) else selectedDecorationAnchor=zone.SlotId; selectedDecorationItem=nil; pendingDecorationColors=nil; page="BuildDecorations" end; render(true) end}) end
		end; return #result>0 and result or nil
	end
	local function tabs() return locationTabs() or modeTabs() end
	local function railScrollKey()
		if string.sub(page,1,14)=="BuildStructure" or string.sub(page,1,14)=="StyleStructure" then return "OwnedGarageRail:Structure" end
		if string.sub(page,1,16)=="BuildDecorations" or string.sub(page,1,16)=="StyleDecorations" then return "OwnedGarageRail:Decorations" end
		return "OwnedGarageRail:Modes"
	end
	local function context(subtitle,cards)
		local sharedZoom=categoryCardImageZoom(); for _,card in ipairs(cards or {}) do if card.CardKind==nil and card.Image and card.ImageZoom==nil then card.ImageZoom=sharedZoom end end
		local item=property(); local home=page=="Home"; local tutorialPage=page=="Home" and "GarageHome" or page=="DisplaySpaces" and "DisplayCars" or (page=="Build" or page=="Style") and "GarageAssetFamilies" or page=="BuildStructure" and "BuildStructure" or page=="BuildDecorations" and "BuildDecorations" or ""; return {TutorialPageId=tutorialPage,Title="GARAGE MANAGEMENT" --[[NTR_ONBOARDING_V1_3_OWNED_GARAGE_PAGE_SEMANTICS]],Subtitle=subtitle,ShowLeft=not home,LeftItems=home and {} or tabs(),LeftFloating=true,LeftCardMode=true,LeftSharedCardSize=true,LeftAlignCarouselBottom=true,Cards=cards,Cash=state and state.Cash or 0,CapacityText=tostring(item and item.Filled or 0).."/"..tostring(item and item.Capacity or 0).." DISPLAY SPACES",CapacityIcon=namedIcon("EconomyCapacity"),ShowStats=false,ShowCashPlus=true,ShowCapacityPlus=false,NextVisible=false,ExitVisible=true,ExitText="EXIT",ExitIcon=navIcon("Exit"),BackIcon=navIcon("Back"),OnExit=close,CarouselScrollKey="OwnedGarage:"..page,CategoryScrollKey=railScrollKey(),RuntimeAudit=false,ExitBelowEconomy=true}
	end
	render=function(full)
		if not state then return end; local cards={}; local view
		if page=="Home" then
			cards={{Id="DisplayCars",DisplayName="Display Cars",Image=namedIcon("ModeDisplayCars"),Footer="MANAGE DISPLAY SPACES",OnSelect=function() setMode("DisplayCars") end},{Id="BuildGarage",DisplayName="Build Garage",Image=namedIcon("ModeBuildGarage"),Footer="BUY / EQUIP ASSETS",OnSelect=function() setMode("BuildGarage") end},{Id="StyleGarage",DisplayName="Style Garage",Image=namedIcon("ModeStyleGarage"),Footer="COLOUR / MATERIAL",OnSelect=function() setMode("StyleGarage") end}}; view=context("Choose how to manage your garage.",cards)
		elseif page=="DisplaySpaces" then
			if not selectedSlot or not slot(selectedSlot) then selectedSlot=state.Slots and state.Slots[1] and state.Slots[1].SlotId end
			for _,space in ipairs(state.Slots or {}) do local spaceItem=space; local vehicleItem=vehicle(spaceItem.VehicleId); local row={Id=spaceItem.SlotId,CardKind="Vehicle",DisplayName=vehicleItem and vehicleItem.DisplayName or "EMPTY DISPLAY SPACE",Image=vehicleItem and asset(vehicleItem.Image) or "",Badge=vehicleItem and (tostring(vehicleItem.Tier).." "..tostring(vehicleItem.Rating)) or nil,BadgeColor=vehicleItem and tierColours[vehicleItem.Tier] or nil,Selected=spaceItem.SlotId==selectedSlot,Footer=vehicleItem and "DISPLAYED" or "ADD VEHICLE",EmptyPlus=vehicleItem==nil}; row.OnSelect=function() selectedSlot=spaceItem.SlotId; render(false) end; table.insert(cards,row) end
			view=context("Choose a display space to manage.",cards); view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() page="Home"; render(true) end; local selectedSpace=slot(selectedSlot); view.SelectedAction={RowId=selectedSlot,Text=(selectedSpace and selectedSpace.VehicleId and selectedSpace.VehicleId~=false) and "CHANGE VEHICLE" or "ADD VEHICLE",OnActivate=function() previewReady=false; selectedVehicle=nil; page="DisplayVehicles"; render(true) end}
		elseif page=="DisplayVehicles" then
			local currentSlot=slot(selectedSlot); local assigned=tostring(currentSlot and currentSlot.VehicleId or ""); if assigned=="false" then assigned="" end; local vehicles={}; for _,item in ipairs(state.Vehicles or {}) do table.insert(vehicles,item) end; table.sort(vehicles,function(a,b) if a.UsedInOtherGarage~=b.UsedInOtherGarage then return not a.UsedInOtherGarage end; if a.Rating~=b.Rating then return a.Rating>b.Rating end; return a.DisplayName<b.DisplayName end)
			for _,item in ipairs(vehicles) do local vehicleItem=item; local current=vehicleItem.VehicleId==assigned; local isReady=previewReady and vehicleItem.VehicleId==selectedVehicle; local row={Id=vehicleItem.VehicleId,CardKind="Vehicle",DisplayName=vehicleItem.DisplayName,Image=asset(vehicleItem.Image),Badge=tostring(vehicleItem.Tier).." "..tostring(vehicleItem.Rating),BadgeColor=tierColours[vehicleItem.Tier],Selected=isReady,Footer=current and "CURRENT DISPLAY" or (vehicleItem.UsedInOtherGarage and "USED IN "..string.upper(vehicleItem.DisplayedGarageName or "ANOTHER GARAGE") or "OWNED VEHICLE"),Muted=vehicleItem.UsedInOtherGarage}; row.OnSelect=function() preview(vehicleItem.VehicleId) end; table.insert(cards,row) end
			view=context(previewReady and "Preview ready. Press DISPLAY to save this vehicle." or "Choose a vehicle for this display space.",cards); view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() cancelPreview(); page="DisplaySpaces"; render(true) end; view.EmptyMessage="NO OWNED VEHICLES AVAILABLE"; local chosen=previewReady and vehicle(selectedVehicle) or nil; if chosen then local current=chosen.VehicleId==assigned; view.SelectedAction={RowId=chosen.VehicleId,Text=current and "DISPLAYED" or "DISPLAY",OnActivate=function() if current or busy or not previewReady then return end; local targetSlot=selectedSlot; local targetVehicle=chosen.VehicleId; local apply=function() operate("AssignDisplay",{SlotId=targetSlot,VehicleId=targetVehicle},"DisplaySpaces",targetSlot,targetVehicle) end; if chosen.UsedInOtherGarage then confirmUsedElsewhere(chosen,apply) else apply() end end} end
		elseif page=="Build" or page=="Style" then
			local build=page=="Build"; cards={{Id="Structure",DisplayName="Structure",Image=namedIcon("FamilyStructure"),Footer=build and "BUY / EQUIP STRUCTURE" or "COLOUR / MATERIAL",OnSelect=function() selectedStyle=nil; pendingStructureColors=nil; pendingStructureMaterials=nil; if not build then selectedSection="__ALL_STRUCTURE" end; page=build and "BuildStructure" or "StyleStructure"; render(true) end},{Id="Decorations",DisplayName="Decorations",Image=namedIcon("FamilyDecorations"),Footer=build and "BUY / EQUIP DECORATIONS" or "COLOUR EQUIPPED ASSETS",OnSelect=function() selectedDecorationItem=nil; pendingDecorationColors=nil; if build then local zones=state.Decorations and state.Decorations.Zones or {}; selectedDecorationAnchor=selectedDecorationAnchor or (zones[1] and zones[1].SlotId); page="BuildDecorations" else beginDecorationStyle("__ALL_DECORATIONS") end; render(true) end},{Id="Lighting",DisplayName="Lighting",Image=namedIcon("FamilyLighting"),Footer=build and "BUY / EQUIP LIGHTING" or "PRIMARY / SECONDARY",OnSelect=function() selectedLightingPreset=nil; pendingLightingColors=nil; if build then page="BuildLighting" else local selected=state.Lighting and state.Lighting.Selected or {}; local channels=selected.ColourChannels or {}; if #channels==0 then workspace:Message("THIS LIGHTING HAS NO COLOUR CHANNELS"); return end; pendingLightingColors=copy(selected.Colors or {}); selectedChannel=first(channels,"Primary"); page="StyleLighting" end; render(true) end}}; view=context(build and "Choose an asset family to build." or "Choose an equipped asset family to style.",cards); view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() page="Home"; render(true) end
		elseif page=="BuildStructure" then
			local structure=state.Structure or {}; local selectedData=structure.Selected and structure.Selected[selectedSection]; local sectionName=selectedSection; for _,entry in ipairs(structure.Sections or {}) do if entry.Id==selectedSection then sectionName=entry.Name end end; for _,item in ipairs((structure.Styles and structure.Styles[selectedSection]) or {}) do local style=item; local owned=structure.OwnedStyles and structure.OwnedStyles[style.StyleId]; local current=selectedData and selectedData.StyleId==style.StyleId; table.insert(cards,{Id=style.StyleId,CardKind="Listing",VehicleName=sectionName,DisplayName=style.DisplayName,Price=owned and nil or style.Price,Footer=current and "CURRENT" or (owned and "OWNED" or ""),SemanticState=current and "Equipped" or "Available",PriceColor=(not owned and (tonumber(state.Cash) or 0)<(tonumber(style.Price) or 0)) and (replacement:GetAttribute("OwnedGarageUnaffordablePriceColor") or Color3.fromRGB(255,75,85)) or nil,Selected=style.StyleId==selectedStyle,OnSelect=function() selectedStyle=style.StyleId; request("PreviewStructure",{SectionId=selectedSection,StyleId=style.StyleId}); render(false) end}) end; view=context("Choose a structure option for "..tostring(sectionName)..".",cards); local chosen; for _,entry in ipairs((structure.Styles and structure.Styles[selectedSection]) or {}) do if entry.StyleId==selectedStyle then chosen=entry end end; if chosen then local owned=structure.OwnedStyles and structure.OwnedStyles[chosen.StyleId]; local current=selectedData and selectedData.StyleId==chosen.StyleId; view.SelectedAction={RowId=chosen.StyleId,Text=current and "CURRENT" or (owned and "EQUIP" or "BUY"),OnActivate=function() if current then return elseif owned then operate("ConfigureStructure",{SectionId=selectedSection,Action="Equip",StyleId=chosen.StyleId},"BuildStructure",nil,nil,"STRUCTURE EQUIPPED") else operate("ConfigureStructure",{SectionId=selectedSection,Action="Purchase",StyleId=chosen.StyleId},"BuildStructure",nil,nil,"STRUCTURE PURCHASED AND EQUIPPED") end end} end; view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() request("CancelStructurePreview",{}); selectedStyle=nil; page="Build"; render(true) end
		elseif page=="BuildDecorations" then
			local decorations=state.Decorations or {}; local function itemById(id) for _,list in pairs(decorations.ItemsByZone or {}) do for _,item in ipairs(list) do if item.ItemId==id then return item end end end end; local placement=selectedDecorationAnchor and decorations.Placements and decorations.Placements[selectedDecorationAnchor]; local currentId=placement and placement.ItemId; for _,item in ipairs((decorations.ItemsByZone and decorations.ItemsByZone[selectedDecorationAnchor]) or {}) do local decoration=item; local owned=decorations.OwnedItems and decorations.OwnedItems[decoration.ItemId]; local current=currentId==decoration.ItemId; table.insert(cards,{Id=decoration.ItemId,CardKind="Listing",VehicleName=string.upper(selectedDecorationAnchor or "DECORATION"),DisplayName=decoration.DisplayName,Price=owned and nil or decoration.Price,Footer=current and "CURRENT" or (owned and "OWNED" or ""),SemanticState=current and "Equipped" or "Available",PriceColor=(not owned and (tonumber(state.Cash) or 0)<(tonumber(decoration.Price) or 0)) and (replacement:GetAttribute("OwnedGarageUnaffordablePriceColor") or Color3.fromRGB(255,75,85)) or nil,Selected=decoration.ItemId==selectedDecorationItem,OnSelect=function() selectedDecorationItem=decoration.ItemId; request("PreviewDecoration",{SlotId=selectedDecorationAnchor,ItemId=decoration.ItemId}); render(false) end}) end; local zone; for _,candidate in ipairs(decorations.Zones or {}) do if candidate.SlotId==selectedDecorationAnchor then zone=candidate end end; if zone and not zone.Required and currentId then table.insert(cards,{Id="__EMPTY",DisplayName="Empty Zone",Footer="REMOVE CURRENT DECORATION",OnSelect=function() operate("ConfigureDecoration",{SlotId=selectedDecorationAnchor,Action="Clear"},"BuildDecorations",nil,nil,"DECORATION REMOVED") end}) end; view=context("Choose an option for this decoration location.",cards); view.EmptyMessage="CHOOSE A DECORATION LOCATION"; local chosen=itemById(selectedDecorationItem); if chosen then local owned=decorations.OwnedItems and decorations.OwnedItems[chosen.ItemId]; local current=currentId==chosen.ItemId; view.SelectedAction={RowId=chosen.ItemId,Text=current and "CURRENT" or (owned and "EQUIP" or "BUY"),OnActivate=function() if current then return elseif owned then operate("ConfigureDecoration",{SlotId=selectedDecorationAnchor,ItemId=chosen.ItemId,Action="Place"},"BuildDecorations",nil,nil,"DECORATION EQUIPPED") else operate("ConfigureDecoration",{SlotId=selectedDecorationAnchor,ItemId=chosen.ItemId,Action="Purchase"},"BuildDecorations",nil,nil,"DECORATION PURCHASED AND EQUIPPED") end end} end; view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() request("CancelDecorationPreview",{}); selectedDecorationItem=nil; page="Build"; render(true) end
		elseif page=="BuildLighting" then
			local lighting=state.Lighting or {}; local function presetById(id) for _,item in ipairs(lighting.Presets or {}) do if item.PresetId==id then return item end end end; for _,item in ipairs(lighting.Presets or {}) do local preset=item; local owned=lighting.OwnedPresets and lighting.OwnedPresets[preset.PresetId]; local current=lighting.PresetId==preset.PresetId; table.insert(cards,{Id=preset.PresetId,CardKind="Listing",VehicleName="WHOLE GARAGE",DisplayName=preset.DisplayName,Price=owned and nil or preset.Price,Footer=current and "CURRENT" or (owned and "OWNED" or ""),SemanticState=current and "Equipped" or "Available",PriceColor=(not owned and (tonumber(state.Cash) or 0)<(tonumber(preset.Price) or 0)) and (replacement:GetAttribute("OwnedGarageUnaffordablePriceColor") or Color3.fromRGB(255,75,85)) or nil,Selected=preset.PresetId==selectedLightingPreset,OnSelect=function() selectedLightingPreset=preset.PresetId; request("PreviewLighting",{PresetId=preset.PresetId}); render(false) end}) end; view=context("Choose a whole-garage lighting option.",cards); local chosen=presetById(selectedLightingPreset); if chosen then local owned=lighting.OwnedPresets and lighting.OwnedPresets[chosen.PresetId]; local current=lighting.PresetId==chosen.PresetId; view.SelectedAction={RowId=chosen.PresetId,Text=current and "CURRENT" or (owned and "EQUIP" or "BUY"),OnActivate=function() if current then return elseif owned then operate("ConfigureLighting",{Action="Equip",PresetId=chosen.PresetId},"BuildLighting",nil,nil,"LIGHTING EQUIPPED") else operate("ConfigureLighting",{Action="Purchase",PresetId=chosen.PresetId},"BuildLighting",nil,nil,"LIGHTING PURCHASED AND EQUIPPED") end end} end; view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() request("CancelLightingPreview",{}); selectedLightingPreset=nil; page="Build"; render(true) end
		elseif string.sub(page,1,14)=="StyleStructure" then
			local structure=state.Structure or {}; local all=selectedSection=="__ALL_STRUCTURE"; local selectedData=not all and structure.Selected and structure.Selected[selectedSection]; local selectedList={}; if all then for _,entry in ipairs(structure.Sections or {}) do local item=structure.Selected and structure.Selected[entry.Id]; if item then table.insert(selectedList,item) end end else selectedList={selectedData} end; local colourChannels=all and union(selectedList,"ColourChannels") or (selectedData and selectedData.ColourChannels or {}); local materialChannels=all and union(selectedList,"MaterialChannels") or (selectedData and selectedData.MaterialChannels or {}); local sectionName=all and "All Structure" or selectedSection; for _,entry in ipairs(structure.Sections or {}) do if entry.Id==selectedSection then sectionName=entry.Name end end
			if page=="StyleStructure" then local function actionCard(id,label,channels,icon,reason,onSelect) if #channels==0 then return {Id=id,CardKind="Listing",VehicleName="GARAGE STYLE",DisplayName=label,Footer=reason,SemanticState="Locked",LockImage=namedIcon("StateLocked")} end; return {Id=id,DisplayName=label,Image=namedIcon(icon),Footer=table.concat(channels," / "),OnSelect=onSelect} end; cards={actionCard("Colour","Colour",colourChannels,"ActionColour","NO COLOUR CHANNELS",function() selectedChannel=first(colourChannels,"Primary"); if all then pendingStructureColors=aggregate(selectedList,"Colors",colourChannels) else pendingStructureColors=copy(selectedData.Colors or {}) end; page="StyleStructureColour"; render(true) end),actionCard("Material","Material",materialChannels,"ActionMaterial","NO MATERIAL CHANNELS",function() selectedChannel=first(materialChannels,"Primary"); if all then pendingStructureMaterials=aggregate(selectedList,"Materials",materialChannels) else pendingStructureMaterials=copy(selectedData.Materials or {}) end; page="StyleStructureMaterial"; render(true) end)}; view=context("Style the equipped "..tostring(sectionName)..".",cards)
			elseif page=="StyleStructureColour" then pendingStructureColors=pendingStructureColors or {}; view=context("Adjust structure colours.",{}); view.ColorChannels=colourChannels; view.SelectedChannel=selectedChannel; view.Colors=pendingStructureColors; view.OnChannel=function(channel) selectedChannel=channel; render(true) end; view.OnColor=function(channel,color,commit) pendingStructureColors[channel]=color; if commit then local result=request(all and "PreviewStructureFinishAll" or "PreviewStructureFinish",{SectionId=selectedSection,Colors=pendingStructureColors}); if not result.Success then workspace:Message(result.Message or "COLOUR PREVIEW FAILED") end; render(true) end end; view.NextVisible=true; view.NextText="SAVE"; view.NextIcon=namedIcon("NavigationSave"); view.OnNext=function() operate("ConfigureStructure",{SectionId=selectedSection,Action=all and "SetFinishAll" or "SetFinish",Colors=pendingStructureColors,Materials={}},"StyleStructureColour",nil,nil,nil,all) end
			else pendingStructureMaterials=pendingStructureMaterials or {}; for _,material in ipairs(structure.Materials or {}) do local definition=material; local materialId=tostring(definition.Id or ""); local selected=pendingStructureMaterials[selectedChannel]==materialId; table.insert(cards,{Id=materialId,DisplayName=tostring(definition.DisplayName or materialId),Image=scopedIcon("Materials",materialId,"ActionMaterial"),ImageZoom=materialIconZoom(),Footer=selected and "SELECTED" or "",Selected=selected,OnSelect=function() pendingStructureMaterials[selectedChannel]=materialId; local result=request(all and "PreviewStructureFinishAll" or "PreviewStructureFinish",{SectionId=selectedSection,Materials=pendingStructureMaterials}); if not result.Success then workspace:Message(result.Message or "MATERIAL PREVIEW FAILED") end; render(false) end}) end; view=context("Choose a material for "..selectedChannel..".",cards); view.MaterialChannels=materialChannels; view.SelectedChannel=selectedChannel; view.OnChannel=function(channel) selectedChannel=channel; render(false) end; view.NextVisible=true; view.NextText="SAVE"; view.NextIcon=namedIcon("NavigationSave"); view.OnNext=function() operate("ConfigureStructure",{SectionId=selectedSection,Action=all and "SetFinishAll" or "SetFinish",Colors={},Materials=pendingStructureMaterials},"StyleStructureMaterial",nil,nil,nil,all) end end
			view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() request("CancelStructurePreview",{}); if page=="StyleStructure" then page="Style" else page="StyleStructure" end; pendingStructureColors=nil; pendingStructureMaterials=nil; render(true) end
		elseif page=="StyleDecorations" or page=="StyleDecorationsColour" then
			local decorations=state.Decorations or {}; local all=selectedDecorationAnchor=="__ALL_DECORATIONS"; local placement=not all and decorations.Placements and decorations.Placements[selectedDecorationAnchor]; local placements={}; if all then for _,entry in pairs(decorations.Placements or {}) do if entry then table.insert(placements,entry) end end else placements={placement} end; local channels=all and union(placements,"ColourChannels") or (placement and placement.ColourChannels or {})
			if page=="StyleDecorationsColour" then pendingDecorationColors=pendingDecorationColors or {}; view=context("Adjust equipped decoration colours.",{}); view.ColorChannels=channels; view.SelectedChannel=selectedChannel; view.Colors=pendingDecorationColors; view.OnChannel=function(channel) selectedChannel=channel; render(true) end; view.OnColor=function(channel,color,commit) pendingDecorationColors[channel]=color; if commit then local result=request(all and "PreviewDecorationFinishAll" or "PreviewDecorationFinish",{SlotId=selectedDecorationAnchor,Colors=pendingDecorationColors}); if not result.Success then workspace:Message(result.Message or "COLOUR PREVIEW FAILED") end; render(true) end end; view.NextVisible=true; view.NextText="SAVE"; view.NextIcon=namedIcon("NavigationSave"); view.OnNext=function() operate("ConfigureDecoration",{SlotId=selectedDecorationAnchor,Action=all and "SetFinishAll" or "SetFinish",Colors=pendingDecorationColors},"StyleDecorationsColour",nil,nil,nil,all) end
			else local function openColour() if #channels==0 then return end; selectedChannel=first(channels,"Primary"); if all then pendingDecorationColors=aggregate(placements,"Colors",channels) else pendingDecorationColors=copy(placement.Colors or {}) end; page="StyleDecorationsColour"; render(true) end; if all or placement then if #channels>0 then cards={{Id="Colour",DisplayName="Colour",Image=namedIcon("ActionColour"),Footer=table.concat(channels," / "),OnSelect=openColour}} else cards={{Id="Colour",CardKind="Listing",VehicleName="GARAGE STYLE",DisplayName="Colour",Footer="NO COLOUR CHANNELS",SemanticState="Locked",LockImage=namedIcon("StateLocked")}} end elseif selectedDecorationAnchor then cards={{Id="InstallAsset",DisplayName="Install Asset",Image=scopedIcon("Actions","InstallAsset","FamilyDecorations"),Footer="OPEN BUILD GARAGE",OnSelect=function() selectedDecorationItem=nil; page="BuildDecorations"; render(true) end}} end; view=context(all and "Style all equipped decorations." or (placement and "Style this equipped decoration." or "Install an asset before styling this location."),cards) end; view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() request("CancelDecorationPreview",{}); pendingDecorationColors=nil; selectedDecorationAnchor="__ALL_DECORATIONS"; page="Style"; render(true) end
		elseif page=="StyleLighting" then
			local lighting=state.Lighting or {}; local selected=lighting.Selected or {}; local channels=selected.ColourChannels or {}; pendingLightingColors=pendingLightingColors or copy(selected.Colors or {}); view=context("Adjust whole-garage lighting colours.",{}); view.ColorChannels=channels; view.SelectedChannel=selectedChannel; view.Colors=pendingLightingColors; view.OnChannel=function(channel) selectedChannel=channel; render(true) end; view.OnColor=function(channel,color,commit) pendingLightingColors[channel]=color; if commit then local result=request("PreviewLighting",{PresetId=lighting.PresetId,Colors=subset(pendingLightingColors,channels)}); if not result.Success then workspace:Message(result.Message or "LIGHTING PREVIEW FAILED") end; render(true) end end; view.NextVisible=true; view.NextText="SAVE"; view.NextIcon=namedIcon("NavigationSave"); view.OnNext=function() operate("ConfigureLighting",{Action="SetFinish",PresetId=lighting.PresetId,Colors=subset(pendingLightingColors,channels)},"StyleLighting",nil,nil,"LIGHTING COLOURS SAVED") end; view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() request("CancelLightingPreview",{}); pendingLightingColors=nil; page="Style"; render(true) end
		elseif page=="Access" or page=="AccessInvites" then
			if page=="Access" then for _,mode in ipairs(state.AccessModes or {}) do local accessMode=mode; local current=state.AccessMode==accessMode; table.insert(cards,{Id=accessMode,CardKind="Listing",VehicleName="GARAGE ACCESS",DisplayName=(string.gsub(accessMode,"Only"," Only")),Footer=current and "CURRENT" or "SELECT ACCESS",SemanticState=current and "Equipped" or "Available",Selected=current,OnSelect=function() if not current then operate("SetAccessMode",{AccessMode=accessMode},"Access",nil,nil,"ACCESS MODE SAVED") end end}) end; table.insert(cards,{Id="InvitePlayers",DisplayName="Invitations",Footer=state.InvitationsEnabled and "MANAGE PLAYERS" or "COMING LATER",OnSelect=function() if state.InvitationsEnabled then page="AccessInvites"; selectedInviteUserId=nil; render(true) end end}); view=context("Choose who may access this garage.",cards); view.SelectedAction={RowId="InvitePlayers",Text="MANAGE INVITES",OnActivate=function() page="AccessInvites"; selectedInviteUserId=nil; render(true) end}
			else for _,item in ipairs(state.InvitationRows or {}) do local row=item; table.insert(cards,{Id=tostring(row.UserId),CardKind="Listing",VehicleName=row.Online and string.upper(row.Username or "ONLINE") or "OFFLINE INVITATION",DisplayName=row.DisplayName,Footer=row.Invited and "INVITED" or "AVAILABLE",SemanticState=row.Invited and "Equipped" or "Available",Selected=selectedInviteUserId==row.UserId,OnSelect=function() selectedInviteUserId=row.UserId; render(false) end}) end; view=context("Invite or revoke same-server players.",cards); view.EmptyMessage="NO OTHER PLAYERS IN THIS SERVER"; local chosen; for _,item in ipairs(state.InvitationRows or {}) do if item.UserId==selectedInviteUserId then chosen=item end end; if chosen then view.SelectedAction={RowId=tostring(chosen.UserId),Text=chosen.Invited and "REVOKE" or "INVITE",OnActivate=function() operate("SetInvitation",{Action=chosen.Invited and "Revoke" or "Invite",TargetUserId=chosen.UserId},"AccessInvites",nil,nil,chosen.Invited and "INVITATION REVOKED" or "PLAYER INVITED") end} end end
			view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() selectedInviteUserId=nil; if page=="AccessInvites" then page="Access" else page="DisplaySpaces" end; render(true) end
		else
			view=context(page.." is definition-ready and activates in its dedicated implementation phase.",{}); view.EmptyMessage=string.upper(page).." COMING NEXT"; view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() page="DisplaySpaces"; render(true) end
		end

		local startedAt=os.clock(); if full~=false or not workspace.Root.Visible then workspace:Show(view) else workspace:RefreshCards(view) end; if cfg:GetAttribute("DebugTimingEnabled")==true then print("[NTR Owned Garage Timing] page="..page.." renderMs="..math.floor((os.clock()-startedAt)*1000+.5)) end
	end
	local function open(requested)
		generation+=1; local token=generation; page=type(requested)=="table" and tostring(requested.Page or "Home") or "Home"; selectedVehicle=nil; setManagementOpen(true)
		if state and state.InGarage then render(true) else workspace:Show(context("Loading garage management...",{})); workspace:Message("LOADING GARAGE...") end
		task.spawn(function() request("SetManagementOpen",{Open=true}); if refresh(token) then selectedSlot=(state.Slots and state.Slots[1] and state.Slots[1].SlotId) or nil; render(true) end end)
	end
	openEvent.Event:Connect(function(requested) if workspace.Root.Visible then close() else open(requested) end end)
	push.OnClientEvent:Connect(function(message)
		if type(message)~="table" then return end
		if message.Type=="OpenManagement" then if not workspace.Root.Visible then open() end
		elseif message.Type=="DriveOut" then close()
		elseif message.Type=="ManagementUpdated" and workspace.Root.Visible then
			local revision=tonumber(message.Revision); if revision and state and revision<=tonumber(state.Revision or 0) then return end
			if busy or refreshRunning then queuedRevision=math.max(tonumber(queuedRevision) or 0,revision or 0); return end
			local token=generation; task.spawn(function() if refresh(token) then render(true) end end)
		elseif message.Type=="DriveOutResult" and message.Success==false then workspace:Message(message.Message or "Could not drive out.") end
	end)
	started=true; print("[NTR Owned Garage] Canonical Phase 8 workspace active."); return true,"Started"
end
return Controller
