-- NTR_OWNED_GARAGE_WORKSPACE_CONTROLLER_V1
-- NTR_OWNED_GARAGE_WORKSPACE_CONTROLLER_V2_HARDENED
local Controller={}; local started=false; local closeCurrent=function() end; local isOpenCurrent=function() return false end
function Controller.Close(reason) closeCurrent(reason) end
function Controller.IsOpen() return isOpenCurrent() end
function Controller.Start()
	if started then return true,"AlreadyStarted" end
	local ReplicatedStorage=game:GetService("ReplicatedStorage"); local kit=ReplicatedStorage:WaitForChild("NeoTokyoRacers"); local uiFolder=script.Parent; local Racing=require(kit.Shared.Modules.UI:WaitForChild("RacingUIComponents")); local WorkspaceUI=require(uiFolder:WaitForChild("GarageWorkspaceController")); local Shared=require(uiFolder:WaitForChild("GarageReplacementComponents")); local styleCatalog=require(kit.Shared.Modules.Data:WaitForChild("OwnedGarageInteriorStyleCatalog")); local remote=kit.Shared.Remotes.Garage:WaitForChild("OwnedGarageInvoke"); local push=kit.Shared.Remotes.Garage:WaitForChild("OwnedGarageEvent"); local openEvent=uiFolder:WaitForChild("OpenOwnedGarageWorkspace")
	local workspace=WorkspaceUI.new(); workspace.Root.Name="OwnedGarageCanonicalWorkspace"; workspace.Audit=function(self) Shared.AuditPresentation(self.Root,"Owned Garage Workspace") end
	local settings=kit.Config.Runtime:WaitForChild("OwnedGarage_EditAttributes"); local UserInputService=game:GetService("UserInputService")
	local function presentation(active) local event=uiFolder:FindFirstChild("FreeRoamHudPresentationMode"); if event and event:IsA("BindableEvent") then event:Fire({Owner="OwnedGarageWorkspace",Active=active==true,KeepTelemetry=false}) end end
	local function hardenTouch() if not UserInputService.TouchEnabled then return end; local scale=math.max(workspace.Scale and workspace.Scale.Scale or 1,.01); local minimum=math.ceil(math.max(32,tonumber(settings:GetAttribute("MinimumTouchTargetPixels")) or 44)/scale); for _,object in ipairs(workspace.Root:GetDescendants()) do if object:IsA("GuiButton") then local original=object:GetAttribute("NTR_OwnedGarageOriginalSize"); if typeof(original)~="UDim2" then original=object.Size; object:SetAttribute("NTR_OwnedGarageOriginalSize",original) end; if original.Y.Scale==0 then object.Size=UDim2.new(original.X.Scale,original.X.Offset,0,math.max(original.Y.Offset,minimum)) elseif object.Parent and object.Parent.Name=="CardActionPopup" then local popup=object.Parent; local popupOriginal=popup:GetAttribute("NTR_OwnedGarageOriginalSize") or popup.Size; popup:SetAttribute("NTR_OwnedGarageOriginalSize",popupOriginal); popup.Size=UDim2.new(popupOriginal.X.Scale,popupOriginal.X.Offset,0,math.max(popupOriginal.Y.Offset,minimum)) end end end end
	local state; local page="DisplaySlots"; local selectedSlot="Space01"; local selectedVehicle; local selectedStyle; local selectedAccess; local busy=false; local imageCache={}; local render
	local function request(action,args) local ok,result=pcall(function() return remote:InvokeServer(action,args or {}) end); if ok and type(result)=="table" then return result end; return {Success=false,Message="Garage management is unavailable."} end
	local function imageFor(cockpitId) cockpitId=tostring(cockpitId or ""); if imageCache[cockpitId]~=nil then return imageCache[cockpitId] end; local image=""; local categories=kit.Assets.Vehicles:FindFirstChild("Categories"); if categories then for _,candidate in ipairs(categories:GetDescendants()) do if candidate:IsA("Model") and tostring(candidate:GetAttribute("CockpitId") or "")==cockpitId then image=tostring(candidate:GetAttribute("PreviewImage") or candidate:GetAttribute("Image") or ""); break end end end; imageCache[cockpitId]=image; return image end
	local function vehicleById(id) for _,vehicle in ipairs(state and state.Vehicles or {}) do if vehicle.VehicleId==tostring(id or "") then return vehicle end end end
	local function property() for _,item in ipairs(state and state.Properties or {}) do if item.PropertyId==state.CurrentPropertyId then return item end end return state and state.Properties and state.Properties[1] end
	local function close() workspace:Hide(); presentation(false) end; closeCurrent=close; isOpenCurrent=function() return workspace.Root.Visible end
	local function refresh(nextPage) local result=request("GetManagementState",{}); if not result.Success or not result.InGarage then warn("[NTR Owned Garage] "..tostring(result.Message or "Management requires an active garage interior.")); close(); return false end; state=result; if nextPage then page=nextPage end; return true end
	local function operate(action,args,nextPage) if busy then return end; busy=true; local result=request(action,args); busy=false; if not result.Success then workspace:Message(result.Message or "Garage update failed."); return end; if refresh(nextPage) then render() end end
	local function tabs() return {{Id="Display",Text="DISPLAY CARS",Selected=page=="DisplaySlots" or page=="DisplayVehicles",OnSelect=function() page="DisplaySlots"; selectedVehicle=nil; render() end},{Id="Interior",Text="INTERIOR",Selected=page=="Interior",OnSelect=function() page="Interior"; selectedStyle=nil; render() end},{Id="Access",Text="ACCESS",Selected=page=="Access",OnSelect=function() page="Access"; selectedAccess=nil; render() end}} end
	local function info(title,body) return function(parent) local heading=Racing.Label(parent,{Text=string.upper(title),Size=UDim2.new(1,0,0,30),TextSize=16,Role="Heading",XAlignment=Enum.TextXAlignment.Center}); heading:SetAttribute("GeneratedGarageWorkspace",true); heading.LayoutOrder=1; local copy=Racing.Label(parent,{Text=body,Size=UDim2.new(1,0,0,78),TextSize=12,XAlignment=Enum.TextXAlignment.Center}); copy.TextWrapped=true; copy:SetAttribute("GeneratedGarageWorkspace",true); copy.LayoutOrder=2 end end
	local function context(subtitle,cards) local item=property(); return {Title="GARAGE MANAGEMENT",Subtitle=subtitle,ShowLeft=true,LeftItems=tabs(),Cards=cards,Cash=state.Cash or 0,CapacityText=tostring(item and item.Filled or 0).."/"..tostring(item and item.Capacity or 0).." DISPLAY SPACES",NextVisible=false,ExitVisible=true,ExitText="CLOSE",OnExit=close,OnCash=function() end,OnCapacity=function() end,CarouselScrollKey="OwnedGarage:"..page,CategoryScrollKey="OwnedGarageTabs",RenderStats=info("OWNER WORKSPACE","Choose display vehicles, edit the interior, or prepare property access. Changes are validated and saved.")} end
	local function hidePlus() for _,container in ipairs({workspace.Cash,workspace.Capacity}) do for _,child in ipairs(container:GetChildren()) do if child:IsA("GuiButton") and child.Text=="+" then child.Visible=false end end end end
	render=function()
		if not state then return end; local cards={}; local view
		if page=="DisplaySlots" then
			local found=false; for _,slot in ipairs(state.Slots or {}) do if slot.SlotId==selectedSlot then found=true end end; if not found and state.Slots and state.Slots[1] then selectedSlot=state.Slots[1].SlotId end
			for index,slot in ipairs(state.Slots or {}) do local vehicle=vehicleById(slot.VehicleId); local row={Id=slot.SlotId,DisplayName=slot.DisplayName,Badge="SPACE "..index,Image=vehicle and imageFor(vehicle.CockpitId) or "",Selected=slot.SlotId==selectedSlot,Footer=vehicle and "DISPLAYED" or "EMPTY",ActionText="CHOOSE VEHICLE"}; row.OnSelect=function() selectedSlot=slot.SlotId; render() end; row.OnAction=function() page="DisplayVehicles"; selectedVehicle=tostring(slot.VehicleId or ""); if selectedVehicle=="false" then selectedVehicle="" end; render() end; table.insert(cards,row) end
			view=context("Choose a display space to manage.",cards); view.RenderStats=info("DISPLAY CARS","Each saved vehicle can appear in only one display space. Reassigning it clears its former display reference without deleting it.")
		elseif page=="DisplayVehicles" then
			local assigned=""; for _,slot in ipairs(state.Slots or {}) do if slot.SlotId==selectedSlot and slot.VehicleId and slot.VehicleId~=false then assigned=tostring(slot.VehicleId) end end; if not selectedVehicle or selectedVehicle=="" then selectedVehicle=assigned~="" and assigned or (state.Vehicles and state.Vehicles[1] and state.Vehicles[1].VehicleId) end
			for _,vehicle in ipairs(state.Vehicles or {}) do local current=vehicle.VehicleId==assigned; local row={Id=vehicle.VehicleId,DisplayName=vehicle.DisplayName,Image=imageFor(vehicle.CockpitId),Badge=current and "DISPLAYED" or nil,Selected=vehicle.VehicleId==selectedVehicle,Footer=current and "CURRENT SPACE" or "OWNED VEHICLE",ActionText=current and "REMOVE FROM DISPLAY" or "DISPLAY HERE"}; row.OnSelect=function() selectedVehicle=vehicle.VehicleId; render() end; row.OnAction=function() if current then operate("ClearDisplay",{SlotId=selectedSlot},"DisplaySlots") else operate("AssignDisplay",{SlotId=selectedSlot,VehicleId=vehicle.VehicleId},"DisplaySlots") end end; table.insert(cards,row) end
			view=context("Choose the saved vehicle for "..selectedSlot..".",cards); view.BackVisible=true; view.BackText="DISPLAY SPACES"; view.OnBack=function() page="DisplaySlots"; render() end; view.EmptyMessage="NO OWNED VEHICLES AVAILABLE"
		elseif page=="Interior" then
			local styles=state.InteriorStyles or styleCatalog.List(); if not selectedStyle and styles[1] then selectedStyle=styles[1].StyleId end
			for _,style in ipairs(styles) do local current=state.SurfaceStyles and state.SurfaceStyles[style.SurfaceGroup]==style.StyleId; local row={Id=style.StyleId,DisplayName=style.DisplayName,Badge=string.upper(style.SurfaceGroup),Selected=style.StyleId==selectedStyle,Footer=current and "CURRENT" or string.upper(style.Material or "STYLE"),SemanticState=current and "Equipped" or "Shop",CardKind="Listing",ActionText=current and nil or "APPLY STYLE"}; row.OnSelect=function() selectedStyle=style.StyleId; render() end; row.OnAction=function() operate("SetInteriorStyle",{SurfaceGroup=style.SurfaceGroup,StyleId=style.StyleId},"Interior") end; table.insert(cards,row) end
			view=context("Choose editable surface styles for this property.",cards); view.RenderStats=info("INTERIOR","Surface presets are catalogue-driven and saved per garage property.")
		else
			local modes={{Id="Private",Text="PRIVATE",Body="Only the owner can enter."},{Id="FriendsOnly",Text="FRIENDS ONLY",Body="Reserved for friend access."},{Id="InviteOnly",Text="INVITE ONLY",Body="Reserved for invitations."},{Id="Public",Text="PUBLIC",Body="Reserved for public visits."}}; selectedAccess=selectedAccess or state.AccessMode
			for _,mode in ipairs(modes) do local current=mode.Id==state.AccessMode; local row={Id=mode.Id,DisplayName=mode.Text,Badge=current and "CURRENT" or "ACCESS",Selected=mode.Id==selectedAccess,Footer=mode.Body,SemanticState=current and "Equipped" or "Shop",CardKind="Listing",ActionText=current and nil or "SET ACCESS"}; row.OnSelect=function() selectedAccess=mode.Id; render() end; row.OnAction=function() operate("SetAccessMode",{AccessMode=mode.Id},"Access") end; table.insert(cards,row) end
			view=context("Choose the saved access policy for this garage.",cards); view.RenderStats=info("ACCESS","The policy is persistent. Visitor admission remains disabled until its later activation gate.")
		end
		workspace:Show(view); hidePlus(); presentation(true); task.defer(hardenTouch)
	end
	local function open() if refresh("DisplaySlots") then selectedSlot="Space01"; selectedVehicle=nil; selectedStyle=nil; selectedAccess=nil; render() end end
	if workspace.Scale then workspace.Scale:GetPropertyChangedSignal("Scale"):Connect(function() if workspace.Root.Visible then task.defer(hardenTouch) end end) end; openEvent.Event:Connect(function() if workspace.Root.Visible then close() else open() end end); push.OnClientEvent:Connect(function(message) if type(message)=="table" and message.Type=="OpenManagement" then open() elseif type(message)=="table" and message.Type=="DriveOut" then close() end end)
	started=true; print("[NTR Owned Garage] Workspace controller active."); return true,"Started"
end
return Controller
