-- NTR_OWNED_GARAGE_WORKSPACE_CONTROLLER_V4_CANONICAL_VERTICAL_SLICE
-- NTR_OWNED_GARAGE_WORKSPACE_CONTROLLER_V5_REFRESH_OWNER
-- NTR_OWNED_GARAGE_WORKSPACE_CONTROLLER_V6_EXPLICIT_DISPLAY_COMMIT
-- NTR_OWNED_GARAGE_WORKSPACE_CONTROLLER_V7_AUTHORITATIVE_SELECTED_ACTION
-- NTR_OWNED_GARAGE_STRUCTURE_UI_V1
-- NTR_OWNED_GARAGE_STRUCTURE_UI_V1_1_CAPABILITY_ASSETS
-- NTR_OWNED_GARAGE_DECORATION_UI_V1
-- NTR_OWNED_GARAGE_LIGHTING_UI_V1
-- NTR_OWNED_GARAGE_ACCESS_INVITATIONS_UI_V1
local Controller={}; local started=false; local closeCurrent=function() end; local isOpenCurrent=function() return false end
function Controller.Close(reason) closeCurrent(reason) end
function Controller.IsOpen() return isOpenCurrent() end
function Controller.Start()
	if started then return true,"AlreadyStarted" end
	local Players=game:GetService("Players"); local ReplicatedStorage=game:GetService("ReplicatedStorage"); local HttpService=game:GetService("HttpService"); local player=Players.LocalPlayer; local playerGui=player:WaitForChild("PlayerGui")
	local kit=ReplicatedStorage:WaitForChild("NeoTokyoRacers"); local uiFolder=script.Parent; local WorkspaceUI=require(uiFolder:WaitForChild("GarageWorkspaceController")); local Shared=require(uiFolder:WaitForChild("GarageReplacementComponents")); local UI=require(kit.Shared.Modules.UI:WaitForChild("RacingUIComponents")); local remote=kit.Shared.Remotes.Garage:WaitForChild("OwnedGarageInvoke"); local push=kit.Shared.Remotes.Garage:WaitForChild("OwnedGarageEvent"); local openEvent=uiFolder:WaitForChild("OpenOwnedGarageWorkspace"); local cfg=kit.Config.Runtime:WaitForChild("OwnedGarage_EditAttributes"); local replacement=kit.Config.UI:WaitForChild("GarageReplacement"); local navIcons=replacement:WaitForChild("NavigationIcons"); local icons=replacement:FindFirstChild("OwnedGarageIcons") or navIcons
	local workspace=WorkspaceUI.new(); workspace.Root.Name="OwnedGarageCanonicalWorkspace"
	local state; local page="DisplaySpaces"; local selectedSlot; local selectedVehicle; local selectedSection="FrontWall"; local selectedStyle; local selectedChannel="Primary"; local selectedDecorationCategory; local selectedDecorationAnchor; local selectedDecorationItem; local selectedLightingPreset; local selectedLightingIntensity; local selectedInviteUserId; local previewReady=false; local previewGeneration=0; local busy=false; local refreshRunning=false; local queuedRevision; local generation=0; local modal
	local tierColours={E=Color3.fromRGB(132,142,145),D=Color3.fromRGB(105,190,129),C=Color3.fromRGB(74,204,211),B=Color3.fromRGB(82,137,235),A=Color3.fromRGB(244,188,65),S=Color3.fromRGB(236,92,168)}
	local function asset(value) return UI.Asset(value or "") end
	local iconFallback={DisplayCars="OwnedModulesIcon",Structure="BuildModulesIcon",Decorations="CustomiseModulesIcon",Lighting="BuyModulesIcon"}
	local function icon(name) return asset(icons:GetAttribute(name) or navIcons:GetAttribute(iconFallback[name] or "")) end
	local function navIcon(name) return asset(navIcons:GetAttribute(name) or navIcons:GetAttribute(name.."Icon")) end
	local function request(action,args) local startedAt=os.clock(); local ok,result=pcall(function() return remote:InvokeServer(action,args or {}) end); if cfg:GetAttribute("DebugTimingEnabled")==true then print("[NTR Owned Garage Timing] action="..action.." remoteMs="..math.floor((os.clock()-startedAt)*1000+.5)) end; if ok and type(result)=="table" then return result end; return {Success=false,Message="Garage management is unavailable."} end
	local function property() for _,item in ipairs(state and state.Properties or {}) do if item.PropertyId==state.CurrentPropertyId then return item end end; return state and state.Properties and state.Properties[1] end
	local function vehicle(id) for _,item in ipairs(state and state.Vehicles or {}) do if item.VehicleId==tostring(id or "") then return item end end end
	local function slot(id) for _,item in ipairs(state and state.Slots or {}) do if item.SlotId==tostring(id or "") then return item end end end
	local function closeModal() if modal then modal:Destroy(); modal=nil end end
	local function setManagementOpen(open) playerGui:SetAttribute("NTR_OwnedGarageManagementOpen",open==true) end
	local function cancelPreview() previewGeneration+=1; previewReady=false; selectedVehicle=nil; if state and state.InGarage then task.spawn(function() request("CancelDisplayPreview",{}); request("CancelStructurePreview",{}); request("CancelDecorationPreview",{}); request("CancelLightingPreview",{}) end) end end
	local function close() generation+=1; closeModal(); setManagementOpen(false); workspace:Hide(); if state and state.InGarage then task.spawn(function() request("CancelDisplayPreview",{}); request("CancelStructurePreview",{}); request("CancelDecorationPreview",{}); request("CancelLightingPreview",{}); request("SetManagementOpen",{Open=false}) end) end end
	closeCurrent=close; isOpenCurrent=function() return workspace.Root.Visible end
	local function refresh(token)
		if refreshRunning then return false end
		refreshRunning=true; local result=request("GetManagementState",{}); refreshRunning=false
		if token~=generation then return false end
		if not result.Success then workspace:Message(result.Message or "Garage state could not be refreshed. Please try again."); return false end
		if not result.InGarage then workspace:Message(result.Message or "Management requires an active garage interior."); close(); return false end
		state=result
		if queuedRevision and tonumber(queuedRevision) and tonumber(queuedRevision)<=tonumber(state.Revision or 0) then queuedRevision=nil end
		return true
	end
	local render
	local function operate(action,args,nextPage,expectedSlotId,expectedVehicleId,successMessage)
		if busy then return end; args=type(args)=="table" and args or {}; args.BaseRevision=state and state.Revision or nil; args.RequestId=HttpService:GenerateGUID(false); busy=true; workspace:Message("SAVING GARAGE..."); local result=request(action,args); busy=false
		if not result.Success then if result.Conflict then local token=generation; if refresh(token) then render(true) end end; workspace:Message(result.Message or "Garage update failed."); return end
		local committedState=type(result.ManagementState)=="table" and result.ManagementState or nil
		if expectedSlotId and expectedVehicleId then
			local committed=false
			if committedState then for _,space in ipairs(committedState.Slots or {}) do if tostring(space.SlotId or "")==tostring(expectedSlotId) and tostring(space.VehicleId or "")==tostring(expectedVehicleId) then committed=true; break end end
			else local raw=result.State; local propertyState=raw and raw.Properties and raw.Properties[state and state.CurrentPropertyId]; committed=propertyState and propertyState.DisplaySpaces and tostring(propertyState.DisplaySpaces[expectedSlotId] or "")==tostring(expectedVehicleId) end
			if not committed then workspace:Message("Display was not committed. Your saved garage was left unchanged."); return end
		end
		if committedState and committedState.Success then state=committedState; queuedRevision=nil; page=nextPage or page; previewReady=false; selectedVehicle=nil; render(true); workspace:Message(successMessage or "VEHICLE DISPLAYED")
		else local token=generation; if refresh(token) then queuedRevision=nil; page=nextPage or page; previewReady=false; selectedVehicle=nil; render(true); workspace:Message(successMessage or "VEHICLE DISPLAYED") end end
	end
	local function preview(vehicleId)
		if busy or not selectedSlot then return end
		previewGeneration+=1; local previewToken=previewGeneration; local token=generation; local requestedVehicle=tostring(vehicleId or ""); local requestedSlot=selectedSlot; previewReady=false; selectedVehicle=nil; workspace:Message("LOADING VEHICLE PREVIEW...")
		task.spawn(function()
			local result=request("PreviewDisplay",{SlotId=requestedSlot,VehicleId=requestedVehicle})
			if token~=generation or previewToken~=previewGeneration or page~="DisplayVehicles" then return end
			if not result.Success then workspace:Message(result.Message or "Vehicle preview failed."); render(false); return end
			selectedVehicle=requestedVehicle; previewReady=true; render(false)
		end)
	end
	local function confirmUsedElsewhere(item,onYes)
		closeModal(); modal=Shared.ConfirmationModal(workspace.Root,{Title="VEHICLE ALREADY DISPLAYED",Body="This vehicle is displayed in "..tostring(item.DisplayedGarageName or "another garage")..". Move it here?",ConfirmText="CONTINUE",CancelText="CANCEL",OnConfirm=function() modal=nil; onYes() end,OnCancel=function() modal=nil end})
	end
	local function tabs()
		local definitions={{Id="DisplayCars",Text="Display Cars",Image=icon("DisplayCars"),Enabled=true},{Id="Structure",Text="Structure",Image=icon("Structure"),Enabled=state and state.Capabilities and state.Capabilities.Structure},{Id="Decorations",Text="Decorations",Image=icon("Decorations"),Enabled=state and state.Capabilities and state.Capabilities.Decorations},{Id="Lighting",Text="Lighting",Image=icon("Lighting"),Enabled=state and state.Capabilities and state.Capabilities.Lighting}}
		local result={}; for _,definition in ipairs(definitions) do local item=definition; local selected=(item.Id=="DisplayCars" and (page=="DisplaySpaces" or page=="DisplayVehicles")) or (item.Id=="Structure" and string.sub(page,1,9)=="Structure") or (item.Id=="Decorations" and string.sub(page,1,10)=="Decoration") or (item.Id=="Lighting" and string.sub(page,1,8)=="Lighting") or page==item.Id; table.insert(result,{Id=item.Id,Text=item.Text,Image=item.Image,ImageZoom=.5,Selected=selected,OnSelect=function() if item.Enabled~=true then workspace:Message(string.upper(item.Text).." COMING LATER"); return end; if item.Id=="DisplayCars" then page="DisplaySpaces" else page=item.Id end; cancelPreview(); render(true) end}) end; return result
	end
	local function context(subtitle,cards)
		local item=property(); return {Title="GARAGE MANAGEMENT",Subtitle=subtitle,ShowLeft=true,LeftItems=tabs(),LeftFloating=true,LeftCardMode=true,LeftSharedCardSize=true,LeftAlignCarouselBottom=true,Cards=cards,Cash=state and state.Cash or 0,CapacityText=tostring(item and item.Filled or 0).."/"..tostring(item and item.Capacity or 0).." DISPLAY SPACES",ShowStats=false,ShowCashPlus=true,ShowCapacityPlus=false,NextVisible=false,ExitVisible=true,ExitText="EXIT",ExitIcon=navIcon("Exit"),BackIcon=navIcon("Back"),OnExit=close,CarouselScrollKey="OwnedGarage:"..page,CategoryScrollKey="OwnedGarageTabs",RuntimeAudit=false}
	end
	render=function(full)
		if not state then return end; local cards={}; local view
		if page=="DisplaySpaces" then
			if not selectedSlot or not slot(selectedSlot) then selectedSlot=state.Slots and state.Slots[1] and state.Slots[1].SlotId end
			for _,space in ipairs(state.Slots or {}) do local spaceItem=space; local vehicleItem=vehicle(spaceItem.VehicleId); local row={Id=spaceItem.SlotId,CardKind="Vehicle",DisplayName=vehicleItem and vehicleItem.DisplayName or "EMPTY DISPLAY SPACE",Image=vehicleItem and asset(vehicleItem.Image) or "",Badge=vehicleItem and (tostring(vehicleItem.Tier).." "..tostring(vehicleItem.Rating)) or nil,BadgeColor=vehicleItem and tierColours[vehicleItem.Tier] or nil,Selected=spaceItem.SlotId==selectedSlot,Footer=vehicleItem and "DISPLAYED" or "ADD VEHICLE",EmptyPlus=vehicleItem==nil}; row.OnSelect=function() selectedSlot=spaceItem.SlotId; render(false) end; table.insert(cards,row) end
			view=context("Choose a display space to manage.",cards)
			local selectedSpace=slot(selectedSlot); view.SelectedAction={RowId=selectedSlot,Text=(selectedSpace and selectedSpace.VehicleId and selectedSpace.VehicleId~=false) and "CHANGE VEHICLE" or "ADD VEHICLE",OnActivate=function() previewReady=false; selectedVehicle=nil; page="DisplayVehicles"; render(true) end}
		elseif page=="DisplayVehicles" then
			local currentSlot=slot(selectedSlot); local assigned=tostring(currentSlot and currentSlot.VehicleId or ""); if assigned=="false" then assigned="" end
			local vehicles={}; for _,item in ipairs(state.Vehicles or {}) do table.insert(vehicles,item) end; table.sort(vehicles,function(a,b) if a.UsedInOtherGarage~=b.UsedInOtherGarage then return not a.UsedInOtherGarage end; if a.Rating~=b.Rating then return a.Rating>b.Rating end; return a.DisplayName<b.DisplayName end)
			for _,item in ipairs(vehicles) do local vehicleItem=item; local current=vehicleItem.VehicleId==assigned; local isReady=previewReady and vehicleItem.VehicleId==selectedVehicle; local row={Id=vehicleItem.VehicleId,CardKind="Vehicle",DisplayName=vehicleItem.DisplayName,Image=asset(vehicleItem.Image),Badge=tostring(vehicleItem.Tier).." "..tostring(vehicleItem.Rating),BadgeColor=tierColours[vehicleItem.Tier],Selected=isReady,Footer=current and "CURRENT DISPLAY" or (vehicleItem.UsedInOtherGarage and "USED IN "..string.upper(vehicleItem.DisplayedGarageName or "ANOTHER GARAGE") or "OWNED VEHICLE"),Muted=vehicleItem.UsedInOtherGarage}; row.OnSelect=function() preview(vehicleItem.VehicleId) end; table.insert(cards,row) end
			view=context(previewReady and "Preview ready. Press DISPLAY to save this vehicle." or "Choose a vehicle for this display space.",cards); view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() cancelPreview(); page="DisplaySpaces"; render(true) end; view.EmptyMessage="NO OWNED VEHICLES AVAILABLE"
			local chosen=previewReady and vehicle(selectedVehicle) or nil; if chosen then local current=chosen.VehicleId==assigned; view.SelectedAction={RowId=chosen.VehicleId,Text=current and "DISPLAYED" or "DISPLAY",OnActivate=function() if current or busy or not previewReady then return end; local targetSlot=selectedSlot; local targetVehicle=chosen.VehicleId; local apply=function() operate("AssignDisplay",{SlotId=targetSlot,VehicleId=targetVehicle},"DisplaySpaces",targetSlot,targetVehicle) end; if chosen.UsedInOtherGarage then confirmUsedElsewhere(chosen,apply) else apply() end end} end
		elseif string.sub(page,1,9)=="Structure" then
			local structure=state.Structure or {}; local sectionList=structure.Sections or {}; local selectedData=structure.Selected and structure.Selected[selectedSection]; local function sectionName(id) for _,item in ipairs(sectionList) do if item.Id==id then return item.Name end end return id end
			if page=="Structure" then for _,item in ipairs(sectionList) do local section=item; table.insert(cards,{Id=section.Id,DisplayName=section.Name,Footer="CHOOSE STRUCTURE",Selected=section.Id==selectedSection,OnSelect=function() selectedSection=section.Id; selectedStyle=nil; page="StructureStyles"; render(true) end}) end; view=context("Choose a structure location.",cards)
			elseif page=="StructureStyles" then for _,item in ipairs((structure.Styles and structure.Styles[selectedSection]) or {}) do local style=item; local owned=structure.OwnedStyles and structure.OwnedStyles[style.StyleId]; local current=selectedData and selectedData.StyleId==style.StyleId; table.insert(cards,{Id=style.StyleId,CardKind="Listing",VehicleName=sectionName(selectedSection),DisplayName=style.DisplayName,Price=owned and nil or style.Price,Footer=current and "CURRENT" or (owned and "OWNED" or "LOCKED"),SemanticState=current and "Equipped" or (owned and "Available" or "Locked"),Selected=style.StyleId==selectedStyle,OnSelect=function() selectedStyle=style.StyleId; request("PreviewStructure",{SectionId=selectedSection,StyleId=style.StyleId}); render(false) end}) end; view=context("Choose a style for "..sectionName(selectedSection)..".",cards); local chosen; for _,item in ipairs((structure.Styles and structure.Styles[selectedSection]) or {}) do if item.StyleId==selectedStyle then chosen=item end end; if chosen then local owned=structure.OwnedStyles and structure.OwnedStyles[chosen.StyleId]; view.SelectedAction={RowId=chosen.StyleId,Text=owned and "CUSTOMISE" or "BUY",OnActivate=function() if owned then operate("ConfigureStructure",{SectionId=selectedSection,Action="Equip",StyleId=chosen.StyleId},"StructureCustomise",nil,nil,"STRUCTURE EQUIPPED") else operate("ConfigureStructure",{SectionId=selectedSection,Action="Purchase",StyleId=chosen.StyleId},"StructureCustomise",nil,nil,"STRUCTURE PURCHASED") end end} end
			elseif page=="StructureCustomise" then cards={{Id="Colour",DisplayName="Colour",Footer="PRIMARY / SECONDARY / DETAIL",OnSelect=function() page="StructureColour"; render(true) end},{Id="Material",DisplayName="Material",Footer="PRIMARY / SECONDARY / DETAIL",OnSelect=function() page="StructureMaterial"; render(true) end}}; view=context("Customise "..sectionName(selectedSection)..".",cards)
			elseif page=="StructureColour" then view=context("Adjust structure colours.",{}); view.ColorChannels=structure.Channels or {"Primary","Secondary","Detail"}; view.SelectedChannel=selectedChannel; view.Colors=selectedData and selectedData.Colors or {}; view.OnChannel=function(channel) selectedChannel=channel; render(true) end; view.OnColor=function(channel,color,commit) if commit then operate("ConfigureStructure",{SectionId=selectedSection,Action="SetColour",Channel=channel,Color=color},"StructureColour",nil,nil,"COLOUR SAVED") end end
			elseif page=="StructureMaterial" then for _,material in ipairs(structure.Materials or {}) do local name=material; table.insert(cards,{Id=name,DisplayName=name,Footer=(selectedData and selectedData.Materials and selectedData.Materials[selectedChannel]==name) and "CURRENT" or selectedChannel,Selected=selectedData and selectedData.Materials and selectedData.Materials[selectedChannel]==name,OnSelect=function() operate("ConfigureStructure",{SectionId=selectedSection,Action="SetMaterial",Channel=selectedChannel,Material=name},"StructureMaterial",nil,nil,"MATERIAL SAVED") end}) end; view=context("Choose "..selectedChannel.." material.",cards)
			end
			view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() request("CancelStructurePreview",{}); if page=="Structure" then page="DisplaySpaces" elseif page=="StructureStyles" then page="Structure" elseif page=="StructureCustomise" then page="StructureStyles" else page="StructureCustomise" end; render(true) end
		elseif string.sub(page,1,10)=="Decoration" then
			local decorations=state.Decorations or {}; local function itemById(id) for _,list in pairs(decorations.ItemsByCategory or {}) do for _,item in ipairs(list) do if item.ItemId==id then return item end end end end
			if page=="Decorations" then for _,item in ipairs(decorations.Categories or {}) do local category=item; table.insert(cards,{Id=category.CategoryId,DisplayName=category.DisplayName,Footer="CHOOSE CATEGORY",OnSelect=function() selectedDecorationCategory=category.CategoryId; selectedDecorationAnchor=nil; selectedDecorationItem=nil; page="DecorationAnchors"; render(true) end}) end; view=context("Choose a decoration category.",cards)
			elseif page=="DecorationAnchors" then for _,item in ipairs(decorations.Anchors or {}) do local anchor=item; local currentId=decorations.Placements and decorations.Placements[anchor.AnchorId]; local current=itemById(currentId); table.insert(cards,{Id=anchor.AnchorId,DisplayName=current and current.DisplayName or "EMPTY POSITION",Footer=current and "DISPLAYED" or "CHOOSE POSITION",EmptyPlus=current==nil,Selected=anchor.AnchorId==selectedDecorationAnchor,OnSelect=function() selectedDecorationAnchor=anchor.AnchorId; selectedDecorationItem=nil; page="DecorationItems"; render(true) end}) end; view=context("Choose a position for this decoration.",cards)
			elseif page=="DecorationItems" then local list=(decorations.ItemsByCategory and decorations.ItemsByCategory[selectedDecorationCategory]) or {}; local currentId=decorations.Placements and decorations.Placements[selectedDecorationAnchor]; for _,item in ipairs(list) do local decoration=item; local owned=decorations.OwnedItems and decorations.OwnedItems[decoration.ItemId]; local current=currentId==decoration.ItemId; table.insert(cards,{Id=decoration.ItemId,CardKind="Listing",VehicleName=string.upper(selectedDecorationCategory or "DECORATION"),DisplayName=decoration.DisplayName,Price=owned and nil or decoration.Price,Footer=current and "CURRENT" or (owned and "OWNED" or "LOCKED"),SemanticState=current and "Equipped" or (owned and "Available" or "Locked"),Selected=decoration.ItemId==selectedDecorationItem,OnSelect=function() selectedDecorationItem=decoration.ItemId; request("PreviewDecoration",{AnchorId=selectedDecorationAnchor,ItemId=decoration.ItemId}); render(false) end}) end; view=context("Choose a decoration to preview.",cards); local chosen=itemById(selectedDecorationItem); if chosen then local owned=decorations.OwnedItems and decorations.OwnedItems[chosen.ItemId]; local current=currentId==chosen.ItemId; view.SelectedAction={RowId=chosen.ItemId,Text=current and "REMOVE" or (owned and "PLACE" or "BUY"),OnActivate=function() if current then operate("ConfigureDecoration",{AnchorId=selectedDecorationAnchor,Action="Clear"},"DecorationAnchors",nil,nil,"DECORATION REMOVED") elseif owned then operate("ConfigureDecoration",{AnchorId=selectedDecorationAnchor,ItemId=chosen.ItemId,Action="Place"},"DecorationAnchors",nil,nil,"DECORATION PLACED") else operate("ConfigureDecoration",{AnchorId=selectedDecorationAnchor,ItemId=chosen.ItemId,Action="Purchase"},"DecorationAnchors",nil,nil,"DECORATION PURCHASED") end end} end
			end
			view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() request("CancelDecorationPreview",{}); selectedDecorationItem=nil; if page=="Decorations" then page="DisplaySpaces" elseif page=="DecorationAnchors" then page="Decorations" else page="DecorationAnchors" end; render(true) end
		elseif string.sub(page,1,8)=="Lighting" then
			local lighting=state.Lighting or {}; local function presetById(id) for _,item in ipairs(lighting.Presets or {}) do if item.PresetId==id then return item end end end
			if page=="Lighting" then cards={{Id="Presets",DisplayName="Presets",Footer="ROOM COLOUR / MOOD",OnSelect=function() selectedLightingPreset=nil; page="LightingPresets"; render(true) end},{Id="Intensity",DisplayName="Intensity",Footer="LOW / BALANCED / HIGH",OnSelect=function() selectedLightingIntensity=nil; page="LightingIntensity"; render(true) end}}; view=context("Choose a room-lighting control.",cards)
			elseif page=="LightingPresets" then for _,item in ipairs(lighting.Presets or {}) do local preset=item; local owned=lighting.OwnedPresets and lighting.OwnedPresets[preset.PresetId]; local current=lighting.PresetId==preset.PresetId; table.insert(cards,{Id=preset.PresetId,CardKind="Listing",VehicleName="ROOM LIGHTING",DisplayName=preset.DisplayName,Price=owned and nil or preset.Price,Footer=current and "CURRENT" or (owned and "OWNED" or "LOCKED"),SemanticState=current and "Equipped" or (owned and "Available" or "Locked"),Selected=preset.PresetId==selectedLightingPreset,OnSelect=function() selectedLightingPreset=preset.PresetId; request("PreviewLighting",{PresetId=preset.PresetId}); render(false) end}) end; view=context("Choose a room-lighting preset.",cards); local chosen=presetById(selectedLightingPreset); if chosen then local owned=lighting.OwnedPresets and lighting.OwnedPresets[chosen.PresetId]; local current=lighting.PresetId==chosen.PresetId; view.SelectedAction={RowId=chosen.PresetId,Text=current and "CURRENT" or (owned and "APPLY" or "BUY"),OnActivate=function() if current then return elseif owned then operate("ConfigureLighting",{Action="Equip",PresetId=chosen.PresetId},"Lighting",nil,nil,"LIGHTING APPLIED") else operate("ConfigureLighting",{Action="Purchase",PresetId=chosen.PresetId},"Lighting",nil,nil,"LIGHTING PURCHASED") end end} end
			elseif page=="LightingIntensity" then local currentLevel; for _,level in ipairs(lighting.Levels or {}) do if math.abs((tonumber(level.Value) or 1)-(tonumber(lighting.Intensity) or 1))<.01 then currentLevel=level.Id end end; for _,item in ipairs(lighting.Levels or {}) do local level=item; local current=level.Id==currentLevel; table.insert(cards,{Id=level.Id,CardKind="Listing",VehicleName="ROOM LIGHTING",DisplayName=level.DisplayName,Footer=current and "CURRENT" or "INTENSITY",SemanticState=current and "Equipped" or "Available",Selected=selectedLightingIntensity==level.Value or (selectedLightingIntensity==nil and current),OnSelect=function() selectedLightingIntensity=level.Value; request("PreviewLighting",{Intensity=level.Value}); render(false) end}) end; view=context("Choose garage light intensity.",cards); if selectedLightingIntensity and math.abs(selectedLightingIntensity-(tonumber(lighting.Intensity) or 1))>=.01 then local choice=selectedLightingIntensity; local choiceId=""; for _,level in ipairs(lighting.Levels or {}) do if level.Value==choice then choiceId=level.Id end end; view.SelectedAction={RowId=choiceId,Text="SAVE",OnActivate=function() operate("ConfigureLighting",{Action="SetIntensity",Intensity=choice},"Lighting",nil,nil,"LIGHTING INTENSITY SAVED") end} end
			end
			view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() request("CancelLightingPreview",{}); selectedLightingPreset=nil; selectedLightingIntensity=nil; if page=="Lighting" then page="DisplaySpaces" else page="Lighting" end; render(true) end
		elseif page=="Access" or page=="AccessInvites" then
			if page=="Access" then for _,mode in ipairs(state.AccessModes or {}) do local accessMode=mode; local current=state.AccessMode==accessMode; table.insert(cards,{Id=accessMode,CardKind="Listing",VehicleName="GARAGE ACCESS",DisplayName=(string.gsub(accessMode,"Only"," Only")),Footer=current and "CURRENT" or "SELECT ACCESS",SemanticState=current and "Equipped" or "Available",Selected=current,OnSelect=function() if not current then operate("SetAccessMode",{AccessMode=accessMode},"Access",nil,nil,"ACCESS MODE SAVED") end end}) end; table.insert(cards,{Id="InvitePlayers",DisplayName="Invitations",Footer=state.InvitationsEnabled and "MANAGE PLAYERS" or "COMING LATER",OnSelect=function() if state.InvitationsEnabled then page="AccessInvites"; selectedInviteUserId=nil; render(true) end end}); view=context("Choose who may access this garage.",cards); view.SelectedAction={RowId="InvitePlayers",Text="MANAGE INVITES",OnActivate=function() page="AccessInvites"; selectedInviteUserId=nil; render(true) end}
			else for _,item in ipairs(state.InvitationRows or {}) do local row=item; table.insert(cards,{Id=tostring(row.UserId),CardKind="Listing",VehicleName=row.Online and string.upper(row.Username or "ONLINE") or "OFFLINE INVITATION",DisplayName=row.DisplayName,Footer=row.Invited and "INVITED" or "AVAILABLE",SemanticState=row.Invited and "Equipped" or "Available",Selected=selectedInviteUserId==row.UserId,OnSelect=function() selectedInviteUserId=row.UserId; render(false) end}) end; view=context("Invite or revoke same-server players.",cards); view.EmptyMessage="NO OTHER PLAYERS IN THIS SERVER"; local chosen; for _,item in ipairs(state.InvitationRows or {}) do if item.UserId==selectedInviteUserId then chosen=item end end; if chosen then view.SelectedAction={RowId=tostring(chosen.UserId),Text=chosen.Invited and "REVOKE" or "INVITE",OnActivate=function() operate("SetInvitation",{Action=chosen.Invited and "Revoke" or "Invite",TargetUserId=chosen.UserId},"AccessInvites",nil,nil,chosen.Invited and "INVITATION REVOKED" or "PLAYER INVITED") end} end end
			view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() selectedInviteUserId=nil; if page=="AccessInvites" then page="Access" else page="DisplaySpaces" end; render(true) end
		else
			view=context(page.." is definition-ready and activates in its dedicated implementation phase.",{}); view.EmptyMessage=string.upper(page).." COMING NEXT"; view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() page="DisplaySpaces"; render(true) end
		end

		local startedAt=os.clock(); if full~=false or not workspace.Root.Visible then workspace:Show(view) else workspace:RefreshCards(view) end; if cfg:GetAttribute("DebugTimingEnabled")==true then print("[NTR Owned Garage Timing] page="..page.." renderMs="..math.floor((os.clock()-startedAt)*1000+.5)) end
	end
	local function open(requested)
		generation+=1; local token=generation; page=type(requested)=="table" and tostring(requested.Page or "DisplaySpaces") or "DisplaySpaces"; selectedVehicle=nil; setManagementOpen(true)
		if state and state.InGarage then render(true) else workspace:Show(context("Loading garage management...",{})); workspace:Message("LOADING GARAGE...") end
		task.spawn(function() request("SetManagementOpen",{Open=true}); if refresh(token) then selectedSlot=(state.Slots and state.Slots[1] and state.Slots[1].SlotId) or nil; render(true) end end)
	end
	openEvent.Event:Connect(function(requested) if workspace.Root.Visible then close() else open(requested) end end)
	push.OnClientEvent:Connect(function(message)
		if type(message)~="table" then return end
		if message.Type=="OpenManagement" then if not workspace.Root.Visible then open() end
		elseif message.Type=="DriveOut" then close()
		elseif message.Type=="ManagementUpdated" and workspace.Root.Visible then
			local revision=tonumber(message.Revision); if revision and state and revision<=tonumber(state.Revision or 0) then return end
			if busy or refreshRunning then queuedRevision=math.max(tonumber(queuedRevision) or 0,revision or 0); return end
			local token=generation; task.spawn(function() if refresh(token) then render(true) end end)
		elseif message.Type=="DriveOutResult" and message.Success==false then workspace:Message(message.Message or "Could not drive out.") end
	end)
	started=true; print("[NTR Owned Garage] Canonical Phase 8 workspace active."); return true,"Started"
end
return Controller
