-- Neo Tokyo Racers - Owned Garage Style UX and stable preview lifecycle V1
-- Run once in the Roblox Studio Command Bar while NOT playing.
-- One transactional install: icons, shop states, bulk styling, responsive layout and flicker-safe presentation.

local RunService=game:GetService("RunService")
assert(not RunService:IsRunning(),"Run this installer in Roblox Studio Edit mode.")
local HttpService=game:GetService("HttpService")
local ReplicatedStorage=game:GetService("ReplicatedStorage")
local ServerScriptService=game:GetService("ServerScriptService")
local StarterPlayer=game:GetService("StarterPlayer")

local TAG="[NTR Owned Garage Style UX V1]"
local BASE="NTR_OWNED_GARAGE_ICON_CONFIG_V1_1_LOCATION_SCALE"
local REVISION="NTR_OWNED_GARAGE_STYLE_UX_V1_BATCH_STABLE_PREVIEW"
local RUN_ID=HttpService:GenerateGUID(false)

local function find(root,path) local object=root; for segment in string.gmatch(path,"[^.]+") do object=object and object:FindFirstChild(segment) end; return object end
local function count(source,needle) local result=0; local cursor=1; while true do local a,b=source:find(needle,cursor,true); if not a then return result end; result+=1; cursor=b+1 end end
local function replaceOnce(source,needle,replacement,label) local n=count(source,needle); assert(n==1,label.." anchor count was "..n); local a,b=source:find(needle,1,true); return source:sub(1,a-1)..replacement..source:sub(b+1) end
local function replaceBetween(source,first,last,replacement,label) local n=count(source,first); local m=count(source,last); assert(n==1 and m==1,label.." boundary counts were "..n.."/"..m); local a=assert(source:find(first,1,true)); local b=assert(source:find(last,a+#first,true)); return source:sub(1,a-1)..replacement..source:sub(b) end
local function compile(source,name) local fn,problem=loadstring(source,"="..name); assert(fn,name.." compile failed: "..tostring(problem)) end

local kit=assert(ReplicatedStorage:FindFirstChild("NeoTokyoRacers"),"NeoTokyoRacers missing")
local replacement=assert(find(kit,"Config.UI.GarageReplacement"),"GarageReplacement config missing")
local icons=assert(replacement:FindFirstChild("OwnedGarageIcons"),"Install and mirror Owned Garage Icon Config V1.1 first")
local uiRoot=assert(find(StarterPlayer,"StarterPlayerScripts.NeoTokyoRacersClient.Controllers.UI"),"Client UI controllers missing")
local garageRoot=assert(find(ServerScriptService,"NeoTokyoRacers.Services.Garage"),"Server garage services missing")
local owned=assert(uiRoot:FindFirstChild("OwnedGarageWorkspaceController"),"OwnedGarageWorkspaceController missing")
local workspaceController=assert(uiRoot:FindFirstChild("GarageWorkspaceController"),"GarageWorkspaceController missing")
local shared=assert(uiRoot:FindFirstChild("GarageReplacementComponents"),"GarageReplacementComponents missing")
local management=assert(garageRoot:FindFirstChild("OwnedGarageManagementRuntime"),"OwnedGarageManagementRuntime missing")
local profile=assert(garageRoot:FindFirstChild("OwnedGarageProfileRuntime"),"OwnedGarageProfileRuntime missing")
local containers={owned,workspaceController,shared,management,profile}
for _,container in ipairs(containers) do assert(container:IsA("LuaSourceContainer"),container:GetFullName().." is not a source container"); compile(container.Source,container.Name) end
assert(owned.Source:find(BASE,1,true),"Fresh V1.1 owned workspace marker missing")

local projected={}

local function projectOwned(source)
	if source:find(REVISION,1,true) then return source end
	source=replaceOnce(source,"-- "..BASE.."\n","-- "..BASE.."\n-- "..REVISION.."\n","owned revision")
	source=replaceOnce(source,'local function subset(values,channels) local result={}; for _,channel in ipairs(channels or {}) do if values and values[channel]~=nil then result[channel]=values[channel] end end; return result end','local function subset(values,channels) local result={}; for _,channel in ipairs(channels or {}) do if values and values[channel]~=nil then result[channel]=values[channel] end end; return result end\n\tlocal function union(list,key) local result,seen={},{}; for _,entry in ipairs(list or {}) do for _,channel in ipairs(entry and entry[key] or {}) do if not seen[channel] then seen[channel]=true; table.insert(result,channel) end end end; return result end\n\tlocal function aggregate(list,key,channels) local values,mixed={},{}; for _,channel in ipairs(channels or {}) do local value; local set=false; for _,entry in ipairs(list or {}) do if table.find(entry and entry[key=="Colors" and "ColourChannels" or "MaterialChannels"] or {},channel) then local candidate=entry[key] and entry[key][channel]; if not set then value=candidate; set=true elseif value~=candidate then mixed[channel]=true end end end; if set and not mixed[channel] then values[channel]=value end end; return values,mixed end','owned aggregate helpers')
	source=replaceOnce(source,'local iconContract={ModeDisplayCars={"Modes","DisplayCars","OwnedModulesIcon"},ModeBuildGarage={"Modes","BuildGarage","BuildModulesIcon"},ModeStyleGarage={"Modes","StyleGarage","CustomiseModulesIcon"},FamilyStructure={"Families","Structure","BuildModulesIcon"},FamilyDecorations={"Families","Decorations","CustomiseModulesIcon"},FamilyLighting={"Families","Lighting","BuyModulesIcon"},NavigationBack={"Navigation","Back","BackIcon"},NavigationExit={"Navigation","Exit","ExitIcon"},EconomyCapacity={"Economy","Capacity"}}','local iconContract={ModeDisplayCars={"Modes","DisplayCars","OwnedModulesIcon"},ModeBuildGarage={"Modes","BuildGarage","BuildModulesIcon"},ModeStyleGarage={"Modes","StyleGarage","CustomiseModulesIcon"},FamilyStructure={"Families","Structure","BuildModulesIcon"},FamilyDecorations={"Families","Decorations","CustomiseModulesIcon"},FamilyLighting={"Families","Lighting","BuyModulesIcon"},NavigationBack={"Navigation","Back","BackIcon"},NavigationExit={"Navigation","Exit","ExitIcon"},NavigationSave={"Navigation","Save"},ActionColour={"Actions","Colour"},ActionMaterial={"Actions","Material"},StateLocked={"States","Locked","ModuleLockIcon"},EconomyCapacity={"Economy","Capacity"}}','owned icon contract')
	source=replaceOnce(source,'local function cancelPreview() previewGeneration+=1; previewReady=false; selectedVehicle=nil; if state and state.InGarage then task.spawn(function() request("CancelDisplayPreview",{}); request("CancelStructurePreview",{}); request("CancelDecorationPreview",{}); request("CancelLightingPreview",{}) end) end end','local function cancelPreview() previewGeneration+=1; previewReady=false; selectedVehicle=nil; if state and state.InGarage then task.spawn(function() request("CancelAllPreviews",{}) end) end end','unified client cancel')
	source=replaceOnce(source,'if state and state.InGarage then task.spawn(function() request("CancelDisplayPreview",{}); request("CancelStructurePreview",{}); request("CancelDecorationPreview",{}); request("CancelLightingPreview",{}); request("SetManagementOpen",{Open=false}) end) end','if state and state.InGarage then task.spawn(function() request("CancelAllPreviews",{}); request("SetManagementOpen",{Open=false}) end) end','unified close cancel')
	source=replaceOnce(source,'local function operate(action,args,nextPage,expectedSlotId,expectedVehicleId,successMessage)','local function operate(action,args,nextPage,expectedSlotId,expectedVehicleId,successMessage,quietSuccess)','quiet operation signature')
	source=replaceOnce(source,'render(true); workspace:Message(successMessage or "VEHICLE DISPLAYED")\n\t\telse local token=generation; if refresh(token) then queuedRevision=nil; page=nextPage or page; previewReady=false; selectedVehicle=nil; render(true); workspace:Message(successMessage or "VEHICLE DISPLAYED") end end','render(true); if not quietSuccess then workspace:Message(successMessage or "VEHICLE DISPLAYED") end\n\t\telse local token=generation; if refresh(token) then queuedRevision=nil; page=nextPage or page; previewReady=false; selectedVehicle=nil; render(true); if not quietSuccess then workspace:Message(successMessage or "VEHICLE DISPLAYED") end end end','quiet operation completion')
	local oldTabs=source:sub(assert(source:find('\tlocal function locationTabs()',1,true)),assert(source:find('\tlocal function tabs()',1,true))-1)
	local newTabs=[==[	local function locationTabs()
		local result={}; local structure=state and state.Structure or {}; local decorations=state and state.Decorations or {}
		if string.sub(page,1,14)=="BuildStructure" or string.sub(page,1,14)=="StyleStructure" then
			local styleMode=string.sub(page,1,5)=="Style"; if styleMode then table.insert(result,{Id="__ALL_STRUCTURE",Text="All Structure",Image=scopedIcon("StructureLocations","AllStructure","FamilyStructure"),ImageZoom=locationIconZoom("StructureLocationImageZoom"),Selected=selectedSection=="__ALL_STRUCTURE",OnSelect=function() request("CancelStructurePreview",{}); selectedSection="__ALL_STRUCTURE"; pendingStructureColors=nil; pendingStructureMaterials=nil; page="StyleStructure"; render(true) end}) end; for _,entry in ipairs(structure.Sections or {}) do local section=entry; table.insert(result,{Id=section.Id,Text=section.Name,Image=scopedIcon("StructureLocations",section.Id,"FamilyStructure"),ImageZoom=locationIconZoom("StructureLocationImageZoom"),Selected=selectedSection==section.Id,OnSelect=function() request("CancelStructurePreview",{}); selectedSection=section.Id; selectedStyle=nil; pendingStructureColors=nil; pendingStructureMaterials=nil; page=styleMode and "StyleStructure" or "BuildStructure"; render(true) end}) end
		elseif string.sub(page,1,16)=="BuildDecorations" or string.sub(page,1,16)=="StyleDecorations" then
			local styleMode=string.sub(page,1,5)=="Style"; if styleMode then table.insert(result,{Id="__ALL_DECORATIONS",Text="All Decorations",Image=scopedIcon("DecorationLocations","AllDecorations","FamilyDecorations"),ImageZoom=locationIconZoom("DecorationLocationImageZoom"),Selected=selectedDecorationAnchor=="__ALL_DECORATIONS",OnSelect=function() request("CancelDecorationPreview",{}); selectedDecorationAnchor="__ALL_DECORATIONS"; pendingDecorationColors=nil; page="StyleDecorations"; render(true) end}) end; for _,entry in ipairs(decorations.Zones or {}) do local zone=entry; table.insert(result,{Id=zone.SlotId,Text=zone.DisplayName,Image=scopedIcon("DecorationLocations",zone.SlotId,"FamilyDecorations"),ImageZoom=locationIconZoom("DecorationLocationImageZoom"),Selected=selectedDecorationAnchor==zone.SlotId,OnSelect=function() request("CancelDecorationPreview",{}); selectedDecorationAnchor=zone.SlotId; selectedDecorationItem=nil; pendingDecorationColors=nil; if styleMode then page="StyleDecorations" else page="BuildDecorations" end; render(true) end}) end
		end; return #result>0 and result or nil
	end
]==]
	source=replaceOnce(source,oldTabs,newTabs,"owned location tabs")
	source=replaceOnce(source,'RuntimeAudit=false}','RuntimeAudit=false,ExitBelowEconomy=true}','owned exit placement context')
	source=replaceOnce(source,'OnSelect=function() selectedStyle=nil; pendingStructureColors=nil; pendingStructureMaterials=nil; page=build and "BuildStructure" or "StyleStructure"; render(true) end}','OnSelect=function() selectedStyle=nil; pendingStructureColors=nil; pendingStructureMaterials=nil; if not build then selectedSection="__ALL_STRUCTURE" end; page=build and "BuildStructure" or "StyleStructure"; render(true) end}',"default all structure")
	source=replaceOnce(source,'else selectedDecorationAnchor=nil; page="StyleDecorations" end','else selectedDecorationAnchor="__ALL_DECORATIONS"; page="StyleDecorations" end','default all decorations')
	source=replaceOnce(source,'Footer=current and "CURRENT" or (owned and "OWNED" or "LOCKED"),SemanticState=current and "Equipped" or (owned and "Available" or "Locked"),Selected=style.StyleId==selectedStyle','Footer=current and "CURRENT" or (owned and "OWNED" or ""),SemanticState=current and "Equipped" or "Available",PriceColor=(not owned and (tonumber(state.Cash) or 0)<(tonumber(style.Price) or 0)) and (replacement:GetAttribute("OwnedGarageUnaffordablePriceColor") or Color3.fromRGB(255,75,85)) or nil,Selected=style.StyleId==selectedStyle','structure shop state')
	source=replaceOnce(source,'Footer=current and "CURRENT" or (owned and "OWNED" or "LOCKED"),SemanticState=current and "Equipped" or (owned and "Available" or "Locked"),Selected=decoration.ItemId==selectedDecorationItem','Footer=current and "CURRENT" or (owned and "OWNED" or ""),SemanticState=current and "Equipped" or "Available",PriceColor=(not owned and (tonumber(state.Cash) or 0)<(tonumber(decoration.Price) or 0)) and (replacement:GetAttribute("OwnedGarageUnaffordablePriceColor") or Color3.fromRGB(255,75,85)) or nil,Selected=decoration.ItemId==selectedDecorationItem','decoration shop state')
	source=replaceOnce(source,'Footer=current and "CURRENT" or (owned and "OWNED" or "LOCKED"),SemanticState=current and "Equipped" or (owned and "Available" or "Locked"),Selected=preset.PresetId==selectedLightingPreset','Footer=current and "CURRENT" or (owned and "OWNED" or ""),SemanticState=current and "Equipped" or "Available",PriceColor=(not owned and (tonumber(state.Cash) or 0)<(tonumber(preset.Price) or 0)) and (replacement:GetAttribute("OwnedGarageUnaffordablePriceColor") or Color3.fromRGB(255,75,85)) or nil,Selected=preset.PresetId==selectedLightingPreset','lighting shop state')
	local styleStart='\t\telseif string.sub(page,1,14)=="StyleStructure" then'
	local styleEnd='\t\telseif page=="StyleLighting" then'
	local styleBlock=[==[		elseif string.sub(page,1,14)=="StyleStructure" then
			local structure=state.Structure or {}; local all=selectedSection=="__ALL_STRUCTURE"; local selectedData=not all and structure.Selected and structure.Selected[selectedSection]; local selectedList={}; if all then for _,entry in ipairs(structure.Sections or {}) do local item=structure.Selected and structure.Selected[entry.Id]; if item then table.insert(selectedList,item) end end else selectedList={selectedData} end; local colourChannels=all and union(selectedList,"ColourChannels") or (selectedData and selectedData.ColourChannels or {}); local materialChannels=all and union(selectedList,"MaterialChannels") or (selectedData and selectedData.MaterialChannels or {}); local sectionName=all and "All Structure" or selectedSection; for _,entry in ipairs(structure.Sections or {}) do if entry.Id==selectedSection then sectionName=entry.Name end end
			if page=="StyleStructure" then local function actionCard(id,label,channels,icon,reason,onSelect) if #channels==0 then return {Id=id,CardKind="Listing",VehicleName="GARAGE STYLE",DisplayName=label,Footer=reason,SemanticState="Locked",LockImage=namedIcon("StateLocked")} end; return {Id=id,DisplayName=label,Image=namedIcon(icon),Footer=table.concat(channels," / "),OnSelect=onSelect} end; cards={actionCard("Colour","Colour",colourChannels,"ActionColour","NO COLOUR CHANNELS",function() selectedChannel=first(colourChannels,"Primary"); if all then pendingStructureColors=aggregate(selectedList,"Colors",colourChannels) else pendingStructureColors=copy(selectedData.Colors or {}) end; page="StyleStructureColour"; render(true) end),actionCard("Material","Material",materialChannels,"ActionMaterial","NO MATERIAL CHANNELS",function() selectedChannel=first(materialChannels,"Primary"); if all then pendingStructureMaterials=aggregate(selectedList,"Materials",materialChannels) else pendingStructureMaterials=copy(selectedData.Materials or {}) end; page="StyleStructureMaterial"; render(true) end)}; view=context("Style the equipped "..tostring(sectionName)..".",cards)
			elseif page=="StyleStructureColour" then pendingStructureColors=pendingStructureColors or {}; view=context("Adjust structure colours.",{}); view.ColorChannels=colourChannels; view.SelectedChannel=selectedChannel; view.Colors=pendingStructureColors; view.OnChannel=function(channel) selectedChannel=channel; render(true) end; view.OnColor=function(channel,color,commit) pendingStructureColors[channel]=color; if commit then local result=request(all and "PreviewStructureFinishAll" or "PreviewStructureFinish",{SectionId=selectedSection,Colors=pendingStructureColors}); if not result.Success then workspace:Message(result.Message or "COLOUR PREVIEW FAILED") end; render(true) end end; view.NextVisible=true; view.NextText="SAVE"; view.NextIcon=namedIcon("NavigationSave"); view.OnNext=function() operate("ConfigureStructure",{SectionId=selectedSection,Action=all and "SetFinishAll" or "SetFinish",Colors=pendingStructureColors,Materials={}},"StyleStructureColour",nil,nil,nil,all) end
			else pendingStructureMaterials=pendingStructureMaterials or {}; for _,material in ipairs(structure.Materials or {}) do local definition=material; local materialId=tostring(definition.Id or ""); local selected=pendingStructureMaterials[selectedChannel]==materialId; table.insert(cards,{Id=materialId,DisplayName=tostring(definition.DisplayName or materialId),Image=scopedIcon("Materials",materialId,"ActionMaterial"),Footer=selected and "SELECTED" or "",Selected=selected,OnSelect=function() pendingStructureMaterials[selectedChannel]=materialId; local result=request(all and "PreviewStructureFinishAll" or "PreviewStructureFinish",{SectionId=selectedSection,Materials=pendingStructureMaterials}); if not result.Success then workspace:Message(result.Message or "MATERIAL PREVIEW FAILED") end; render(false) end}) end; view=context("Choose a material for "..selectedChannel..".",cards); view.MaterialChannels=materialChannels; view.SelectedChannel=selectedChannel; view.OnChannel=function(channel) selectedChannel=channel; render(false) end; view.NextVisible=true; view.NextText="SAVE"; view.NextIcon=namedIcon("NavigationSave"); view.OnNext=function() operate("ConfigureStructure",{SectionId=selectedSection,Action=all and "SetFinishAll" or "SetFinish",Colors={},Materials=pendingStructureMaterials},"StyleStructureMaterial",nil,nil,nil,all) end end
			view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() request("CancelStructurePreview",{}); if page=="StyleStructure" then page="Style" else page="StyleStructure" end; pendingStructureColors=nil; pendingStructureMaterials=nil; render(true) end
		elseif page=="StyleDecorations" or page=="StyleDecorationsColour" then
			local decorations=state.Decorations or {}; local all=selectedDecorationAnchor=="__ALL_DECORATIONS"; local placement=not all and decorations.Placements and decorations.Placements[selectedDecorationAnchor]; local placements={}; if all then for _,entry in pairs(decorations.Placements or {}) do if entry then table.insert(placements,entry) end end else placements={placement} end; local channels=all and union(placements,"ColourChannels") or (placement and placement.ColourChannels or {})
			if page=="StyleDecorationsColour" then pendingDecorationColors=pendingDecorationColors or {}; view=context("Adjust equipped decoration colours.",{}); view.ColorChannels=channels; view.SelectedChannel=selectedChannel; view.Colors=pendingDecorationColors; view.OnChannel=function(channel) selectedChannel=channel; render(true) end; view.OnColor=function(channel,color,commit) pendingDecorationColors[channel]=color; if commit then local result=request(all and "PreviewDecorationFinishAll" or "PreviewDecorationFinish",{SlotId=selectedDecorationAnchor,Colors=pendingDecorationColors}); if not result.Success then workspace:Message(result.Message or "COLOUR PREVIEW FAILED") end; render(true) end end; view.NextVisible=true; view.NextText="SAVE"; view.NextIcon=namedIcon("NavigationSave"); view.OnNext=function() operate("ConfigureDecoration",{SlotId=selectedDecorationAnchor,Action=all and "SetFinishAll" or "SetFinish",Colors=pendingDecorationColors},"StyleDecorationsColour",nil,nil,nil,all) end
			else local function openColour() if #channels==0 then return end; selectedChannel=first(channels,"Primary"); if all then pendingDecorationColors=aggregate(placements,"Colors",channels) else pendingDecorationColors=copy(placement.Colors or {}) end; page="StyleDecorationsColour"; render(true) end; if all or placement then if #channels>0 then cards={{Id="Colour",DisplayName="Colour",Image=namedIcon("ActionColour"),Footer=table.concat(channels," / "),OnSelect=openColour}} else cards={{Id="Colour",CardKind="Listing",VehicleName="GARAGE STYLE",DisplayName="Colour",Footer="NO COLOUR CHANNELS",SemanticState="Locked",LockImage=namedIcon("StateLocked")}} end elseif selectedDecorationAnchor then cards={{Id="InstallAsset",DisplayName="Install Asset",Image=scopedIcon("Actions","InstallAsset","FamilyDecorations"),Footer="OPEN BUILD GARAGE",OnSelect=function() selectedDecorationItem=nil; page="BuildDecorations"; render(true) end}} end; view=context(all and "Style all equipped decorations." or (placement and "Style this equipped decoration." or "Install an asset before styling this location."),cards) end; view.BackVisible=true; view.BackText="BACK"; view.OnBack=function() request("CancelDecorationPreview",{}); pendingDecorationColors=nil; if page=="StyleDecorationsColour" then page="StyleDecorations" else selectedDecorationAnchor="__ALL_DECORATIONS"; page="Style" end; render(true) end
]==]
	source=replaceBetween(source,styleStart,styleEnd,styleBlock,"owned style pages")
	compile(source,owned.Name.."_Projected")
	return source
end

local function projectWorkspace(source)
	if source:find(REVISION,1,true) then return source end
	source=replaceOnce(source,"-- NTR_OWNED_GARAGE_ICON_CONFIG_V1\n","-- NTR_OWNED_GARAGE_ICON_CONFIG_V1\n-- "..REVISION.."\n","workspace revision")
	source=replaceOnce(source,'if self.Context.LeftAlignCarouselBottom then local top=self.Categories.Position.Y.Offset; self.Categories.Size=UDim2.fromOffset(self.Categories.Size.X.Offset,math.max(170,shell.CarouselTop+N("CarouselHeight",166)-top)) end','if self.Context.LeftAlignCarouselBottom then local top=self.Categories.Position.Y.Offset; local bottom=shell.CarouselTop+N("CarouselHeight",166); if self.Context.MaterialChannels then bottom=shell.CarouselTop-math.max(0,tonumber(cfg:GetAttribute("MaterialRailTabClearance")) or 48) end; self.Categories.Size=UDim2.fromOffset(self.Categories.Size.X.Offset,math.max(170,bottom-top)) end','material rail cutoff')
	compile(source,workspaceController.Name.."_Projected")
	return source
end

local function projectShared(source)
	if source:find(REVISION,1,true) then return source end
	source=replaceOnce(source,"-- NTR_OWNED_GARAGE_PHASE8_SHARED_PRESENTATION\n","-- NTR_OWNED_GARAGE_PHASE8_SHARED_PRESENTATION\n-- "..REVISION.."\n","shared revision")
	source=replaceOnce(source,'local actionWidth=(N("StatsWidth",354)-gap)*.5; local actionHeight=responsiveNumber(N,"NavigationButtonHeight",N("EconomyHeight",46)); local actionBottom=carouselTop-responsiveNumber(N,"NavigationPopupClearance",48); local actionX=vw-margin; for _,actionButton in ipairs(options.Actions or {}) do if actionButton.Visible then actionButton.AnchorPoint=Vector2.new(1,1); actionButton.Size=UDim2.fromOffset(actionWidth,actionHeight); actionButton.Position=UDim2.fromOffset(actionX,actionBottom); actionX-=actionWidth+gap end end','local actionWidth=(N("StatsWidth",354)-gap)*.5; local actionHeight=responsiveNumber(N,"NavigationButtonHeight",N("EconomyHeight",46)); local actionBottom=carouselTop-responsiveNumber(N,"NavigationPopupClearance",48); local actionX=vw-margin; if ui.Context and ui.Context.ExitBelowEconomy and ui.Exit.Visible then ui.Exit.AnchorPoint=Vector2.new(1,0); ui.Exit.Size=UDim2.fromOffset(actionWidth,actionHeight); ui.Exit.Position=UDim2.fromOffset(vw-margin,28+economyCardHeight*2+economyStackGap+gap) end; for _,actionButton in ipairs(options.Actions or {}) do if actionButton.Visible and not (ui.Context and ui.Context.ExitBelowEconomy and actionButton==ui.Exit) then actionButton.AnchorPoint=Vector2.new(1,1); actionButton.Size=UDim2.fromOffset(actionWidth,actionHeight); actionButton.Position=UDim2.fromOffset(actionX,actionBottom); actionX-=actionWidth+gap end end','shared action placement')
	compile(source,shared.Name.."_Projected")
	return source
end

local function projectManagement(source)
	if source:find(REVISION,1,true) then return source end
	source=replaceOnce(source,"-- NTR_OWNED_GARAGE_PHASE14_V1_LIGHTING_STATE_FOUNDATION\n","-- NTR_OWNED_GARAGE_PHASE14_V1_LIGHTING_STATE_FOUNDATION\n-- "..REVISION.."\n","management revision")
	local oldApply=[==[	local function applyInteriorStyles(profile,session)
		local property=profile.OwnedGarage.Properties[session.PropertyId]; local definition=catalog.ById(session.PropertyId); local sections=definition and definition.StructureSections or {}; local structureState=styleCatalog.NormalizeStructure(property and property.Customisation and property.Customisation.Structure,sections); local preview=session.StructurePreview; local slots=session.Interior:FindFirstChild("StructureSlots"); if not slots then return false,"Structure asset contract is missing." end
		local runtime=session.Interior:FindFirstChild("StructureRuntime"); if not runtime then runtime=Instance.new("Folder"); runtime.Name="StructureRuntime"; runtime.Parent=session.Interior end
		for _,base in ipairs(session.Interior:GetDescendants()) do if base:IsA("BasePart") and base:GetAttribute("StructureSection") and not base:IsDescendantOf(runtime) and not base:IsDescendantOf(slots) then base.Transparency=1; base.CanCollide=false; base.CanTouch=false; base.CanQuery=false end end
		for _,section in ipairs(sections) do local selected=structureState.Sections[section]; if preview and preview.SectionId==section then selected=preview end; local style=selected and styleCatalog.ById(section,selected.StyleId); local slot=slots:FindFirstChild(section); local asset=style and finishRuntime.StructureAsset(definition.TemplateId,section,style.AssetOption); if not (style and slot and slot:IsA("BasePart") and asset) then return false,"Structure asset missing: "..tostring(section).."/"..tostring(style and style.AssetOption or "") end; local old=runtime:FindFirstChild(section); if old then old:Destroy() end; local origin=session.Interior:FindFirstChild("TemplateOrigin",true); local placementAnchor=asset:GetAttribute("GaragePlacementMode")=="TemplateOrigin" and origin or slot; local model,message=finishRuntime.CloneAt(asset,placementAnchor,"Structure",selected,section); if not model then return false,message end; model:SetAttribute("StructureSection",section); model:SetAttribute("StructureStyleId",style.StyleId); model:SetAttribute("StructurePreview",preview and preview.SectionId==section or false); model.Parent=runtime end; return true
	end
	local function applyDecorations(profile,session)
		local property=profile.OwnedGarage.Properties[session.PropertyId]; local definition=catalog.ById(session.PropertyId); local slotDefinitions=definition and definition.DecorationSlots or {}; local decorationsState=decorationCatalog.Normalize(property and property.Customisation and property.Customisation.Decorations,slotDefinitions); for _,slot in ipairs(slotDefinitions) do local group=tostring(slot.HideSurfaceGroup or ""); if group~="" then for _,object in ipairs(session.Interior:GetDescendants()) do if object:IsA("BasePart") and object:GetAttribute("SurfaceGroup")==group then local original=object:GetAttribute("NTRGarageOriginalTransparency"); if original==nil then object:SetAttribute("NTRGarageOriginalTransparency",object.Transparency); object:SetAttribute("NTRGarageOriginalCanCollide",object.CanCollide); object:SetAttribute("NTRGarageOriginalCanTouch",object.CanTouch); object:SetAttribute("NTRGarageOriginalCanQuery",object.CanQuery); original=object.Transparency end; object.Transparency=original; object.CanCollide=object:GetAttribute("NTRGarageOriginalCanCollide")==true; object.CanTouch=object:GetAttribute("NTRGarageOriginalCanTouch")==true; object.CanQuery=object:GetAttribute("NTRGarageOriginalCanQuery")==true end end end end; local slotRoot=session.Interior:FindFirstChild("DecorationSlots"); if not slotRoot then return false,"Decoration slots are missing." end
		for _,slot in ipairs(slotDefinitions) do local activePlacement=decorationsState.Placements[slot.SlotId]; if session.DecorationPreview and session.DecorationPreview.SlotId==slot.SlotId then activePlacement=session.DecorationPreview end; local hideSurface=tostring(slot.HideSurfaceGroup or ""); if activePlacement and hideSurface~="" then for _,object in ipairs(session.Interior:GetDescendants()) do if object:IsA("BasePart") and object:GetAttribute("SurfaceGroup")==hideSurface and not object:IsDescendantOf(session.Interior:FindFirstChild("DecorationRuntime") or slotRoot) then object.Transparency=1; object.CanCollide=false; object.CanTouch=false; object.CanQuery=false end end end; local rootName=tostring(slot.HideTemplateModel or ""); local rootModel=rootName~="" and session.Interior:FindFirstChild(rootName); if rootModel then local promptAnchor=rootModel:FindFirstChild("DeskPromptAnchor"); for _,object in ipairs(rootModel:GetDescendants()) do if object:IsA("BasePart") and object~=promptAnchor and not (promptAnchor and object:IsDescendantOf(promptAnchor)) then object.Transparency=1; object.CanCollide=false; object.CanTouch=false; object.CanQuery=false elseif object:IsA("Light") or object:IsA("ParticleEmitter") or object:IsA("Beam") or object:IsA("Trail") then object.Enabled=false end end end end
		local runtime=session.Interior:FindFirstChild("DecorationRuntime"); if not runtime then runtime=Instance.new("Folder"); runtime.Name="DecorationRuntime"; runtime.Parent=session.Interior end; runtime:ClearAllChildren()
		for _,slot in ipairs(slotDefinitions) do local slotId=slot.SlotId; local placement=decorationsState.Placements[slotId]; if session.DecorationPreview and session.DecorationPreview.SlotId==slotId then placement=session.DecorationPreview end; if placement then local item=decorationCatalog.ById(placement.ItemId); local anchorName=tostring(slot.AnchorId or slotId); local anchor=slotRoot:FindFirstChild(anchorName) or session.Interior:FindFirstChild(anchorName,true); local asset=item and finishRuntime.DecorationAsset(definition.TemplateId,slotId,item.AssetName,item.AssetGroupId or slot.AssetGroupId); local placementAnchor=asset and asset:GetAttribute("GaragePlacementMode")=="TemplateOrigin" and session.Interior:FindFirstChild("TemplateOrigin",true) or anchor; if not (item and placementAnchor and placementAnchor:IsA("BasePart") and asset and finishRuntime.IsDecorationAvailable(definition.TemplateId,item)) then return false,"Decoration asset missing or unavailable: "..tostring(placement.ItemId).."/"..tostring(slotId) end; local model,message=finishRuntime.CloneAt(asset,placementAnchor,"Decoration",placement,slotId); if not model then return false,message end; model:SetAttribute("DecorationSlotId",slotId); model:SetAttribute("DecorationItemId",item.ItemId); model:SetAttribute("DecorationPreview",session.DecorationPreview and session.DecorationPreview.SlotId==slotId or false); model.Parent=runtime end end; return true
	end
	local function applyLighting(profile,session)
		local property=profile.OwnedGarage.Properties[session.PropertyId]; local definition=catalog.ById(session.PropertyId); local lighting=lightingCatalog.Normalize(property and property.Customisation and property.Customisation.Lighting); if session.LightingPreview then lighting=session.LightingPreview end; local preset=lightingCatalog.ById(lighting.PresetId); local asset=preset and finishRuntime.LightingAsset(definition and definition.TemplateId,preset.AssetName); local origin=session.Interior:FindFirstChild("TemplateOrigin",true); if not (preset and asset and origin and origin:IsA("BasePart")) then return false,"Garage lighting contract is missing." end
		local runtime=session.Interior:FindFirstChild("LightingRuntime"); if not runtime then runtime=Instance.new("Folder"); runtime.Name="LightingRuntime"; runtime.Parent=session.Interior end; runtime:ClearAllChildren(); local appearance=lightingCatalog.Finish(lighting,preset.PresetId); local clone,message=finishRuntime.CloneAt(asset,origin,"Lighting",appearance,"WholeGarageLighting"); if not clone then return false,message end
		for _,object in ipairs(clone:GetDescendants()) do if object:IsA("PointLight") or object:IsA("SpotLight") or object:IsA("SurfaceLight") then object.Brightness=math.max(0,tonumber(preset.Brightness) or object.Brightness)*math.clamp(tonumber(lighting.Intensity) or 1,.5,1.5); if object:IsA("PointLight") or object:IsA("SpotLight") then object.Range=math.min(36,math.max(8,tonumber(preset.Range) or object.Range)) end; object.Shadows=false; object.Enabled=true end end
		clone:SetAttribute("LightingPresetId",preset.PresetId); clone:SetAttribute("LightingPreview",session.LightingPreview~=nil); clone.Parent=runtime; return true
	end]==]
	local newApply=[==[	local function swapRuntimeModel(runtime,key,model)
		local old=runtime:FindFirstChild(key); local stale=runtime:FindFirstChild(key.."__Next"); if stale then stale:Destroy() end; model.Name=key.."__Next"; model:SetAttribute("RuntimeGeneration",HttpService:GenerateGUID(false)); model.Parent=runtime; if old then old:Destroy() end; model.Name=key; return model
	end
	local function structurePreview(session,section) return (session.StructurePreviewAll and session.StructurePreviewAll[section]) or (session.StructurePreview and session.StructurePreview.SectionId==section and session.StructurePreview) or nil end
	local function decorationPreview(session,slotId) return (session.DecorationPreviewAll and session.DecorationPreviewAll[slotId]) or (session.DecorationPreview and session.DecorationPreview.SlotId==slotId and session.DecorationPreview) or nil end
	local function applyInteriorStyles(profile,session)
		local property=profile.OwnedGarage.Properties[session.PropertyId]; local definition=catalog.ById(session.PropertyId); local sections=definition and definition.StructureSections or {}; local structureState=styleCatalog.NormalizeStructure(property and property.Customisation and property.Customisation.Structure,sections); local slots=session.Interior:FindFirstChild("StructureSlots"); if not slots then return false,"Structure asset contract is missing." end
		local runtime=session.Interior:FindFirstChild("StructureRuntime"); if not runtime then runtime=Instance.new("Folder"); runtime.Name="StructureRuntime"; runtime.Parent=session.Interior end
		for _,base in ipairs(session.Interior:GetDescendants()) do if base:IsA("BasePart") and base:GetAttribute("StructureSection") and not base:IsDescendantOf(runtime) and not base:IsDescendantOf(slots) then base.Transparency=1; base.CanCollide=false; base.CanTouch=false; base.CanQuery=false end end
		for _,section in ipairs(sections) do local preview=structurePreview(session,section); local selected=preview or structureState.Sections[section]; local style=selected and styleCatalog.ById(section,selected.StyleId); local slot=slots:FindFirstChild(section); local asset=style and finishRuntime.StructureAsset(definition.TemplateId,section,style.AssetOption); if not (style and slot and slot:IsA("BasePart") and asset) then return false,"Structure asset missing: "..tostring(section).."/"..tostring(style and style.AssetOption or "") end; local current=runtime:FindFirstChild(section); if current and current:GetAttribute("StructureStyleId")==style.StyleId then finishRuntime.Apply(current,"Structure",selected); current:SetAttribute("StructurePreview",preview~=nil) else local origin=session.Interior:FindFirstChild("TemplateOrigin",true); local placementAnchor=asset:GetAttribute("GaragePlacementMode")=="TemplateOrigin" and origin or slot; local model,message=finishRuntime.CloneAt(asset,placementAnchor,"Structure",selected,section); if not model then return false,message end; model:SetAttribute("StructureSection",section); model:SetAttribute("StructureStyleId",style.StyleId); model:SetAttribute("StructurePreview",preview~=nil); swapRuntimeModel(runtime,section,model) end end; return true
	end
	local function applyDecorations(profile,session)
		local property=profile.OwnedGarage.Properties[session.PropertyId]; local definition=catalog.ById(session.PropertyId); local slotDefinitions=definition and definition.DecorationSlots or {}; local decorationsState=decorationCatalog.Normalize(property and property.Customisation and property.Customisation.Decorations,slotDefinitions); for _,slot in ipairs(slotDefinitions) do local group=tostring(slot.HideSurfaceGroup or ""); if group~="" then for _,object in ipairs(session.Interior:GetDescendants()) do if object:IsA("BasePart") and object:GetAttribute("SurfaceGroup")==group then local original=object:GetAttribute("NTRGarageOriginalTransparency"); if original==nil then object:SetAttribute("NTRGarageOriginalTransparency",object.Transparency); object:SetAttribute("NTRGarageOriginalCanCollide",object.CanCollide); object:SetAttribute("NTRGarageOriginalCanTouch",object.CanTouch); object:SetAttribute("NTRGarageOriginalCanQuery",object.CanQuery); original=object.Transparency end; object.Transparency=original; object.CanCollide=object:GetAttribute("NTRGarageOriginalCanCollide")==true; object.CanTouch=object:GetAttribute("NTRGarageOriginalCanTouch")==true; object.CanQuery=object:GetAttribute("NTRGarageOriginalCanQuery")==true end end end end; local slotRoot=session.Interior:FindFirstChild("DecorationSlots"); if not slotRoot then return false,"Decoration slots are missing." end
		for _,slot in ipairs(slotDefinitions) do local activePlacement=decorationPreview(session,slot.SlotId) or decorationsState.Placements[slot.SlotId]; local hideSurface=tostring(slot.HideSurfaceGroup or ""); if activePlacement and hideSurface~="" then for _,object in ipairs(session.Interior:GetDescendants()) do if object:IsA("BasePart") and object:GetAttribute("SurfaceGroup")==hideSurface and not object:IsDescendantOf(session.Interior:FindFirstChild("DecorationRuntime") or slotRoot) then object.Transparency=1; object.CanCollide=false; object.CanTouch=false; object.CanQuery=false end end end; local rootName=tostring(slot.HideTemplateModel or ""); local rootModel=rootName~="" and session.Interior:FindFirstChild(rootName); if rootModel then local promptAnchor=rootModel:FindFirstChild("DeskPromptAnchor"); for _,object in ipairs(rootModel:GetDescendants()) do if object:IsA("BasePart") and object~=promptAnchor and not (promptAnchor and object:IsDescendantOf(promptAnchor)) then object.Transparency=1; object.CanCollide=false; object.CanTouch=false; object.CanQuery=false elseif object:IsA("Light") or object:IsA("ParticleEmitter") or object:IsA("Beam") or object:IsA("Trail") then object.Enabled=false end end end end
		local runtime=session.Interior:FindFirstChild("DecorationRuntime"); if not runtime then runtime=Instance.new("Folder"); runtime.Name="DecorationRuntime"; runtime.Parent=session.Interior end
		for _,slot in ipairs(slotDefinitions) do local slotId=slot.SlotId; local preview=decorationPreview(session,slotId); local placement=preview or decorationsState.Placements[slotId]; local current=runtime:FindFirstChild(slotId); if not placement then if current then current:Destroy() end else local item=decorationCatalog.ById(placement.ItemId); local anchorName=tostring(slot.AnchorId or slotId); local anchor=slotRoot:FindFirstChild(anchorName) or session.Interior:FindFirstChild(anchorName,true); local asset=item and finishRuntime.DecorationAsset(definition.TemplateId,slotId,item.AssetName,item.AssetGroupId or slot.AssetGroupId); local placementAnchor=asset and asset:GetAttribute("GaragePlacementMode")=="TemplateOrigin" and session.Interior:FindFirstChild("TemplateOrigin",true) or anchor; if not (item and placementAnchor and placementAnchor:IsA("BasePart") and asset and finishRuntime.IsDecorationAvailable(definition.TemplateId,item)) then return false,"Decoration asset missing or unavailable: "..tostring(placement.ItemId).."/"..tostring(slotId) end; if current and current:GetAttribute("DecorationItemId")==item.ItemId then finishRuntime.Apply(current,"Decoration",placement); current:SetAttribute("DecorationPreview",preview~=nil) else local model,message=finishRuntime.CloneAt(asset,placementAnchor,"Decoration",placement,slotId); if not model then return false,message end; model:SetAttribute("DecorationSlotId",slotId); model:SetAttribute("DecorationItemId",item.ItemId); model:SetAttribute("DecorationPreview",preview~=nil); swapRuntimeModel(runtime,slotId,model) end end end; return true
	end
	local function configureLightingModel(model,preset,lighting,enabled)
		for _,object in ipairs(model:GetDescendants()) do if object:IsA("PointLight") or object:IsA("SpotLight") or object:IsA("SurfaceLight") then object.Brightness=math.max(0,tonumber(preset.Brightness) or object.Brightness)*math.clamp(tonumber(lighting.Intensity) or 1,.5,1.5); if object:IsA("PointLight") or object:IsA("SpotLight") then object.Range=math.min(36,math.max(8,tonumber(preset.Range) or object.Range)) end; object.Shadows=false; object.Enabled=enabled==true end end
	end
	local function applyLighting(profile,session)
		local property=profile.OwnedGarage.Properties[session.PropertyId]; local definition=catalog.ById(session.PropertyId); local lighting=lightingCatalog.Normalize(property and property.Customisation and property.Customisation.Lighting); if session.LightingPreview then lighting=session.LightingPreview end; local preset=lightingCatalog.ById(lighting.PresetId); local asset=preset and finishRuntime.LightingAsset(definition and definition.TemplateId,preset.AssetName); local origin=session.Interior:FindFirstChild("TemplateOrigin",true); if not (preset and asset and origin and origin:IsA("BasePart")) then return false,"Garage lighting contract is missing." end
		local runtime=session.Interior:FindFirstChild("LightingRuntime"); if not runtime then runtime=Instance.new("Folder"); runtime.Name="LightingRuntime"; runtime.Parent=session.Interior end; local appearance=lightingCatalog.Finish(lighting,preset.PresetId); local current=runtime:FindFirstChild("WholeGarageLighting"); if current and current:GetAttribute("LightingPresetId")==preset.PresetId then finishRuntime.Apply(current,"Lighting",appearance); configureLightingModel(current,preset,lighting,true); current:SetAttribute("LightingPreview",session.LightingPreview~=nil); return true end
		local model,message=finishRuntime.CloneAt(asset,origin,"Lighting",appearance,"WholeGarageLighting"); if not model then return false,message end; configureLightingModel(model,preset,lighting,true); model:SetAttribute("LightingPresetId",preset.PresetId); model:SetAttribute("LightingPreview",session.LightingPreview~=nil); swapRuntimeModel(runtime,"WholeGarageLighting",model); return true
	end]==]
	source=replaceOnce(source,oldApply,newApply,"stable runtime presentation")
	source=replaceOnce(source,'elseif operation=="SetSurfaceStyle" or operation=="ConfigureStructure" then session.StructurePreview=nil; presented=applyInteriorStyles(committed,session) elseif operation=="ConfigureDecoration" then session.DecorationPreview=nil; presented=applyDecorations(committed,session)','elseif operation=="SetSurfaceStyle" or operation=="ConfigureStructure" then session.StructurePreview=nil; session.StructurePreviewAll=nil; presented=applyInteriorStyles(committed,session) elseif operation=="ConfigureDecoration" then session.DecorationPreview=nil; session.DecorationPreviewAll=nil; presented=applyDecorations(committed,session)',"clear batch previews after commit")
	source=replaceOnce(source,'or action=="PreviewStructureFinish" or action=="CancelStructurePreview" or action=="PreviewDecoration" or action=="PreviewDecorationFinish" or action=="CancelDecorationPreview" or action=="PreviewLighting"','or action=="PreviewStructureFinish" or action=="PreviewStructureFinishAll" or action=="CancelStructurePreview" or action=="PreviewDecoration" or action=="PreviewDecorationFinish" or action=="PreviewDecorationFinishAll" or action=="CancelDecorationPreview" or action=="CancelAllPreviews" or action=="PreviewLighting"',"control action allowlist")
	source=replaceOnce(source,'session.StructurePreview={SectionId=section,StyleId=style.StyleId,Colors=clone(finish.Colors or {}),Materials=clone(finish.Materials or {})}; local rendered,message=applyInteriorStyles(profile,session)','session.StructurePreviewAll=nil; session.StructurePreview={SectionId=section,StyleId=style.StyleId,Colors=clone(finish.Colors or {}),Materials=clone(finish.Materials or {})}; local rendered,message=applyInteriorStyles(profile,session)',"single structure preview ownership")
	local structureFinishAnchor=[==[			elseif action=="PreviewStructureFinish" then local session=sessions[player]; local definition=session and catalog.ById(session.PropertyId); local section=tostring(args.SectionId or ""); local property=definition and profile.OwnedGarage.Properties[session.PropertyId]; local structureState=property and styleCatalog.NormalizeStructure(property.Customisation.Structure,definition.StructureSections); local committed=structureState and clone(structureState.Sections[section]); local selected=(session and session.StructurePreview and session.StructurePreview.SectionId==section and committed and session.StructurePreview.StyleId==committed.StyleId) and clone(session.StructurePreview) or committed; local style=selected and styleCatalog.ById(section,selected.StyleId); if not (session and selected and style) then return {Success=false,Message="Structure finish preview is invalid."} end; local colors=type(args.Colors)=="table" and args.Colors or {}; local materials=type(args.Materials)=="table" and args.Materials or {}; local valid,message=finishRuntime.ValidateStructureFinish(definition.TemplateId,section,style.AssetOption,colors,materials); if not valid then return {Success=false,Message=message} end; for channel,value in pairs(colors) do selected.Colors[channel]=value end; for channel,value in pairs(materials) do selected.Materials[channel]=value end; selected.SectionId=section; session.StructurePreview=selected; local rendered,renderMessage=applyInteriorStyles(profile,session); return {Success=rendered==true,Message=renderMessage or "Structure finish preview ready."}
			elseif action=="CancelStructurePreview" then local session=sessions[player]; if not session then return {Success=false,Message="Garage session is not active."} end; session.StructurePreview=nil; applyInteriorStyles(profile,session); return {Success=true,Message="Structure preview cleared."}]==]
	local structureFinishReplacement=[==[			elseif action=="PreviewStructureFinish" then local session=sessions[player]; local definition=session and catalog.ById(session.PropertyId); local section=tostring(args.SectionId or ""); local property=definition and profile.OwnedGarage.Properties[session.PropertyId]; local structureState=property and styleCatalog.NormalizeStructure(property.Customisation.Structure,definition.StructureSections); local committed=structureState and clone(structureState.Sections[section]); local selected=(session and session.StructurePreview and session.StructurePreview.SectionId==section and committed and session.StructurePreview.StyleId==committed.StyleId) and clone(session.StructurePreview) or committed; local style=selected and styleCatalog.ById(section,selected.StyleId); if not (session and selected and style) then return {Success=false,Message="Structure finish preview is invalid."} end; local colors=type(args.Colors)=="table" and args.Colors or {}; local materials=type(args.Materials)=="table" and args.Materials or {}; local valid,message=finishRuntime.ValidateStructureFinish(definition.TemplateId,section,style.AssetOption,colors,materials); if not valid then return {Success=false,Message=message} end; for channel,value in pairs(colors) do selected.Colors[channel]=value end; for channel,value in pairs(materials) do selected.Materials[channel]=value end; selected.SectionId=section; session.StructurePreviewAll=nil; session.StructurePreview=selected; local rendered,renderMessage=applyInteriorStyles(profile,session); return {Success=rendered==true,Message=renderMessage or "Structure finish preview ready."}
			elseif action=="PreviewStructureFinishAll" then local session=sessions[player]; local definition=session and catalog.ById(session.PropertyId); local property=definition and profile.OwnedGarage.Properties[session.PropertyId]; local structureState=property and styleCatalog.NormalizeStructure(property.Customisation.Structure,definition.StructureSections); local colors=type(args.Colors)=="table" and args.Colors or {}; local materials=type(args.Materials)=="table" and args.Materials or {}; if not (session and structureState) then return {Success=false,Message="Structure finish preview is invalid."} end; local previews={}; for _,section in ipairs(definition.StructureSections or {}) do local selected=clone(structureState.Sections[section]); local style=selected and styleCatalog.ById(section,selected.StyleId); local asset=style and finishRuntime.StructureAsset(definition.TemplateId,section,style.AssetOption); local capability=asset and finishRuntime.Inspect(asset,"Structure"); if capability then local targetColors={}; local targetMaterials={}; for channel,value in pairs(colors) do if table.find(capability.ColourChannels or {},channel) then targetColors[channel]=value end end; for channel,value in pairs(materials) do if table.find(capability.MaterialChannels or {},channel) then targetMaterials[channel]=value end end; if next(targetColors) or next(targetMaterials) then local valid,message=finishRuntime.ValidateStructureFinish(definition.TemplateId,section,style.AssetOption,targetColors,targetMaterials); if not valid then return {Success=false,Message=message} end; for channel,value in pairs(targetColors) do selected.Colors[channel]=value end; for channel,value in pairs(targetMaterials) do selected.Materials[channel]=value end; selected.SectionId=section; previews[section]=selected end end end; if next(previews)==nil then return {Success=false,Message="No equipped structure supports this finish."} end; session.StructurePreview=nil; session.StructurePreviewAll=previews; local rendered,renderMessage=applyInteriorStyles(profile,session); return {Success=rendered==true,Message=renderMessage or "All-structure preview ready."}
			elseif action=="CancelStructurePreview" then local session=sessions[player]; if not session then return {Success=false,Message="Garage session is not active."} end; if not session.StructurePreview and not session.StructurePreviewAll then return {Success=true,NoChange=true,Message="No structure preview was active."} end; session.StructurePreview=nil; session.StructurePreviewAll=nil; local rendered,message=applyInteriorStyles(profile,session); return {Success=rendered==true,Message=message or "Structure preview cleared."}]==]
	source=replaceOnce(source,structureFinishAnchor,structureFinishReplacement,"structure finish preview batch")
	source=replaceOnce(source,'session.DecorationPreview={SlotId=slotId,ItemId=item.ItemId,Colors=(current and current.ItemId==item.ItemId) and clone(current.Colors) or {}}; local rendered,message=applyDecorations(profile,session)','session.DecorationPreviewAll=nil; session.DecorationPreview={SlotId=slotId,ItemId=item.ItemId,Colors=(current and current.ItemId==item.ItemId) and clone(current.Colors) or {}}; local rendered,message=applyDecorations(profile,session)',"single decoration preview ownership")
	local decorationFinishAnchor=[==[			elseif action=="PreviewDecorationFinish" then local session=sessions[player]; local definition=session and catalog.ById(session.PropertyId); local slotId=tostring(args.SlotId or ""); local property=definition and profile.OwnedGarage.Properties[session.PropertyId]; local decorationsState=property and decorationCatalog.Normalize(property.Customisation.Decorations,definition.DecorationSlots); local placement=decorationsState and decorationsState.Placements[slotId]; local item=placement and decorationCatalog.ById(placement.ItemId); local colors=type(args.Colors)=="table" and args.Colors or {}; local valid,message=finishRuntime.ValidateDecorationFinish(definition and definition.TemplateId,item,colors); if not (session and placement and valid) then return {Success=false,Message=message or "Decoration finish preview is invalid."} end; local preview=(session.DecorationPreview and session.DecorationPreview.SlotId==slotId and session.DecorationPreview.ItemId==item.ItemId) and clone(session.DecorationPreview) or {SlotId=slotId,ItemId=item.ItemId,Colors=clone(placement.Colors)}; for channel,value in pairs(colors) do preview.Colors[channel]=value end; session.DecorationPreview=preview; local rendered,renderMessage=applyDecorations(profile,session); return {Success=rendered==true,Message=renderMessage or "Decoration finish preview ready."}
			elseif action=="CancelDecorationPreview" then local session=sessions[player]; if not session then return {Success=false,Message="Garage session is not active."} end; session.DecorationPreview=nil; local rendered,message=applyDecorations(profile,session); return {Success=rendered==true,Message=message or "Decoration preview cleared."}]==]
	local decorationFinishReplacement=[==[			elseif action=="PreviewDecorationFinish" then local session=sessions[player]; local definition=session and catalog.ById(session.PropertyId); local slotId=tostring(args.SlotId or ""); local property=definition and profile.OwnedGarage.Properties[session.PropertyId]; local decorationsState=property and decorationCatalog.Normalize(property.Customisation.Decorations,definition.DecorationSlots); local placement=decorationsState and decorationsState.Placements[slotId]; local item=placement and decorationCatalog.ById(placement.ItemId); local colors=type(args.Colors)=="table" and args.Colors or {}; local valid,message=finishRuntime.ValidateDecorationFinish(definition and definition.TemplateId,item,colors); if not (session and placement and valid) then return {Success=false,Message=message or "Decoration finish preview is invalid."} end; local preview=(session.DecorationPreview and session.DecorationPreview.SlotId==slotId and session.DecorationPreview.ItemId==item.ItemId) and clone(session.DecorationPreview) or {SlotId=slotId,ItemId=item.ItemId,Colors=clone(placement.Colors)}; for channel,value in pairs(colors) do preview.Colors[channel]=value end; session.DecorationPreviewAll=nil; session.DecorationPreview=preview; local rendered,renderMessage=applyDecorations(profile,session); return {Success=rendered==true,Message=renderMessage or "Decoration finish preview ready."}
			elseif action=="PreviewDecorationFinishAll" then local session=sessions[player]; local definition=session and catalog.ById(session.PropertyId); local property=definition and profile.OwnedGarage.Properties[session.PropertyId]; local decorationsState=property and decorationCatalog.Normalize(property.Customisation.Decorations,definition.DecorationSlots); local colors=type(args.Colors)=="table" and args.Colors or {}; if not (session and decorationsState) then return {Success=false,Message="Decoration finish preview is invalid."} end; local previews={}; for _,slot in ipairs(definition.DecorationSlots or {}) do local slotId=tostring(slot.SlotId or ""); local placement=decorationsState.Placements[slotId]; local item=placement and decorationCatalog.ById(placement.ItemId); local asset=item and finishRuntime.DecorationAsset(definition.TemplateId,slotId,item.AssetName,item.AssetGroupId or slot.AssetGroupId); local capability=asset and finishRuntime.Inspect(asset,"Decoration"); if capability then local targetColors={}; for channel,value in pairs(colors) do if table.find(capability.ColourChannels or {},channel) then targetColors[channel]=value end end; if next(targetColors) then local valid,message=finishRuntime.ValidateDecorationFinish(definition.TemplateId,item,targetColors); if not valid then return {Success=false,Message=message} end; local preview={SlotId=slotId,ItemId=item.ItemId,Colors=clone(placement.Colors)}; for channel,value in pairs(targetColors) do preview.Colors[channel]=value end; previews[slotId]=preview end end end; if next(previews)==nil then return {Success=false,Message="No installed decoration supports this colour."} end; session.DecorationPreview=nil; session.DecorationPreviewAll=previews; local rendered,renderMessage=applyDecorations(profile,session); return {Success=rendered==true,Message=renderMessage or "All-decoration preview ready."}
			elseif action=="CancelDecorationPreview" then local session=sessions[player]; if not session then return {Success=false,Message="Garage session is not active."} end; if not session.DecorationPreview and not session.DecorationPreviewAll then return {Success=true,NoChange=true,Message="No decoration preview was active."} end; session.DecorationPreview=nil; session.DecorationPreviewAll=nil; local rendered,message=applyDecorations(profile,session); return {Success=rendered==true,Message=message or "Decoration preview cleared."}]==]
	source=replaceOnce(source,decorationFinishAnchor,decorationFinishReplacement,"decoration finish preview batch")
	source=replaceOnce(source,'elseif action=="CancelLightingPreview" then local session=sessions[player]; if not session then return {Success=false,Message="Garage session is not active."} end; session.LightingPreview=nil; local rendered,message=applyLighting(profile,session); return {Success=rendered==true,Message=message or "Lighting preview cleared."}','elseif action=="CancelLightingPreview" then local session=sessions[player]; if not session then return {Success=false,Message="Garage session is not active."} end; if not session.LightingPreview then return {Success=true,NoChange=true,Message="No lighting preview was active."} end; session.LightingPreview=nil; local rendered,message=applyLighting(profile,session); return {Success=rendered==true,Message=message or "Lighting preview cleared."}\n\t\t\telseif action=="CancelAllPreviews" then local session=sessions[player]; if not session then return {Success=false,Message="Garage session is not active."} end; local display=session.PreviewSlotId~=nil; local structure=session.StructurePreview~=nil or session.StructurePreviewAll~=nil; local decoration=session.DecorationPreview~=nil or session.DecorationPreviewAll~=nil; local lighting=session.LightingPreview~=nil; session.PreviewSlotId=nil; session.StructurePreview=nil; session.StructurePreviewAll=nil; session.DecorationPreview=nil; session.DecorationPreviewAll=nil; session.LightingPreview=nil; if display then renderDisplays(player,profile,session) end; if structure then applyInteriorStyles(profile,session) end; if decoration then applyDecorations(profile,session) end; if lighting then applyLighting(profile,session) end; return {Success=true,NoChange=not (display or structure or decoration or lighting),Message="Garage previews cleared."}',"unified preview cancellation")
	compile(source,management.Name.."_Projected")
	return source
end

local function projectProfile(source)
	if source:find(REVISION,1,true) then return source end
	source=replaceOnce(source,"-- NTR_OWNED_GARAGE_PHASE14_V1_LIGHTING_STATE_FOUNDATION\n","-- NTR_OWNED_GARAGE_PHASE14_V1_LIGHTING_STATE_FOUNDATION\n-- "..REVISION.."\n","profile revision")
	local oldStructure=[==[function Runtime.ConfigureStructure(profile,args)
	args=type(args)=="table" and args or {}; local garage=Runtime.Ensure(profile,false); local garageId=tostring(args.GarageId or garage.ActiveGarageId or ""); local property=garage.Properties[garageId]; local definition=Catalog().ById(garageId); local section=tostring(args.SectionId or ""); local action=tostring(args.Action or "")
	if not (property and property.Owned and definition) then return false,"Garage is not owned." end; local validSection=false; for _,id in ipairs(definition.StructureSections or {}) do if id==section then validSection=true end end; if not validSection then return false,"Structure section is invalid." end
	local structureState=StyleCatalog().NormalizeStructure(property.Customisation.Structure,definition.StructureSections); property.Customisation.Structure=structureState; local selected=structureState.Sections[section]
	if action=="Purchase" then local style=StyleCatalog().ById(section,args.StyleId); if not style then return false,"Structure style is invalid." end; if structureState.OwnedStyles[style.StyleId] then return false,"Structure style is already owned." end; local cost=math.max(0,math.floor(tonumber(style.Price) or 0)); if (tonumber(profile.Cash) or 0)<cost then return false,"Not enough cash." end; profile.Cash=(tonumber(profile.Cash) or 0)-cost; structureState.OwnedStyles[style.StyleId]=true; selected=StyleCatalog().SelectStyle(structureState,section,style.StyleId)
	elseif action=="Equip" then local style=StyleCatalog().ById(section,args.StyleId); if not (style and structureState.OwnedStyles[style.StyleId]) then return false,"Purchase this structure style first." end; selected=StyleCatalog().SelectStyle(structureState,section,style.StyleId)
	elseif action=="SetFinish" then local style=StyleCatalog().ById(section,selected.StyleId); local colors=type(args.Colors)=="table" and args.Colors or {}; local materials=type(args.Materials)=="table" and args.Materials or {}; local valid,message=FinishRuntime().ValidateStructureFinish(definition.TemplateId,section,style and style.AssetOption,colors,materials); if not valid then return false,message end; for channel,value in pairs(colors) do selected.Colors[channel]=StyleCatalog().EncodeColor(value) end; for channel,value in pairs(materials) do selected.Materials[channel]=tostring(value) end; StyleCatalog().StoreFinish(structureState,section,selected)
	elseif action=="SetColour" then local style=StyleCatalog().ById(section,selected.StyleId); local colors={[tostring(args.Channel or "")]=args.Color}; local valid,message=FinishRuntime().ValidateStructureFinish(definition.TemplateId,section,style and style.AssetOption,colors,{}); if not valid then return false,message end; for channel,value in pairs(colors) do selected.Colors[channel]=StyleCatalog().EncodeColor(value) end; StyleCatalog().StoreFinish(structureState,section,selected)
	elseif action=="SetMaterial" then local style=StyleCatalog().ById(section,selected.StyleId); local materials={[tostring(args.Channel or "")]=tostring(args.Material or "")}; local valid,message=FinishRuntime().ValidateStructureFinish(definition.TemplateId,section,style and style.AssetOption,{},materials); if not valid then return false,message end; for channel,value in pairs(materials) do selected.Materials[channel]=value end; StyleCatalog().StoreFinish(structureState,section,selected)
	else return false,"Unknown structure action." end; garage.Revision+=1; return true,"Structure updated."
end]==]
	local newStructure=[==[function Runtime.ConfigureStructure(profile,args)
	args=type(args)=="table" and args or {}; local garage=Runtime.Ensure(profile,false); local garageId=tostring(args.GarageId or garage.ActiveGarageId or ""); local property=garage.Properties[garageId]; local definition=Catalog().ById(garageId); local section=tostring(args.SectionId or ""); local action=tostring(args.Action or "")
	if not (property and property.Owned and definition) then return false,"Garage is not owned." end
	local structureState=StyleCatalog().NormalizeStructure(property.Customisation.Structure,definition.StructureSections); property.Customisation.Structure=structureState
	if action=="SetFinishAll" then
		local colors=type(args.Colors)=="table" and args.Colors or {}; local materials=type(args.Materials)=="table" and args.Materials or {}; if next(colors)==nil and next(materials)==nil then return false,"Choose a colour or material before saving." end; local draft=clone(structureState); local affected=0
		for _,targetSection in ipairs(definition.StructureSections or {}) do local selected=draft.Sections[targetSection]; local style=selected and StyleCatalog().ById(targetSection,selected.StyleId); local asset=style and FinishRuntime().StructureAsset(definition.TemplateId,targetSection,style.AssetOption); local capability=asset and FinishRuntime().Inspect(asset,"Structure"); if capability then local targetColors={}; local targetMaterials={}; for channel,value in pairs(colors) do if table.find(capability.ColourChannels or {},channel) then targetColors[channel]=value end end; for channel,value in pairs(materials) do if table.find(capability.MaterialChannels or {},channel) then targetMaterials[channel]=value end end; if next(targetColors) or next(targetMaterials) then local valid,message=FinishRuntime().ValidateStructureFinish(definition.TemplateId,targetSection,style.AssetOption,targetColors,targetMaterials); if not valid then return false,message end; for channel,value in pairs(targetColors) do selected.Colors[channel]=StyleCatalog().EncodeColor(value) end; for channel,value in pairs(targetMaterials) do selected.Materials[channel]=tostring(value) end; StyleCatalog().StoreFinish(draft,targetSection,selected); affected+=1 end end end
		if affected==0 then return false,"No equipped structure supports this finish." end; property.Customisation.Structure=draft; garage.Revision+=1; return true,"Structure finishes updated."
	end
	local validSection=false; for _,id in ipairs(definition.StructureSections or {}) do if id==section then validSection=true end end; if not validSection then return false,"Structure section is invalid." end; local selected=structureState.Sections[section]
	if action=="Purchase" then local style=StyleCatalog().ById(section,args.StyleId); if not style then return false,"Structure style is invalid." end; if structureState.OwnedStyles[style.StyleId] then return false,"Structure style is already owned." end; local cost=math.max(0,math.floor(tonumber(style.Price) or 0)); if (tonumber(profile.Cash) or 0)<cost then return false,"Not enough cash." end; profile.Cash=(tonumber(profile.Cash) or 0)-cost; structureState.OwnedStyles[style.StyleId]=true; selected=StyleCatalog().SelectStyle(structureState,section,style.StyleId)
	elseif action=="Equip" then local style=StyleCatalog().ById(section,args.StyleId); if not (style and structureState.OwnedStyles[style.StyleId]) then return false,"Purchase this structure style first." end; selected=StyleCatalog().SelectStyle(structureState,section,style.StyleId)
	elseif action=="SetFinish" then local style=StyleCatalog().ById(section,selected.StyleId); local colors=type(args.Colors)=="table" and args.Colors or {}; local materials=type(args.Materials)=="table" and args.Materials or {}; local valid,message=FinishRuntime().ValidateStructureFinish(definition.TemplateId,section,style and style.AssetOption,colors,materials); if not valid then return false,message end; for channel,value in pairs(colors) do selected.Colors[channel]=StyleCatalog().EncodeColor(value) end; for channel,value in pairs(materials) do selected.Materials[channel]=tostring(value) end; StyleCatalog().StoreFinish(structureState,section,selected)
	elseif action=="SetColour" then local style=StyleCatalog().ById(section,selected.StyleId); local colors={[tostring(args.Channel or "")]=args.Color}; local valid,message=FinishRuntime().ValidateStructureFinish(definition.TemplateId,section,style and style.AssetOption,colors,{}); if not valid then return false,message end; for channel,value in pairs(colors) do selected.Colors[channel]=StyleCatalog().EncodeColor(value) end; StyleCatalog().StoreFinish(structureState,section,selected)
	elseif action=="SetMaterial" then local style=StyleCatalog().ById(section,selected.StyleId); local materials={[tostring(args.Channel or "")]=tostring(args.Material or "")}; local valid,message=FinishRuntime().ValidateStructureFinish(definition.TemplateId,section,style and style.AssetOption,{},materials); if not valid then return false,message end; for channel,value in pairs(materials) do selected.Materials[channel]=value end; StyleCatalog().StoreFinish(structureState,section,selected)
	else return false,"Unknown structure action." end; garage.Revision+=1; return true,"Structure updated."
end]==]
	source=replaceOnce(source,oldStructure,newStructure,"profile structure batch")
	local oldDecoration=[==[function Runtime.ConfigureDecoration(profile,args)
	args=type(args)=="table" and args or {}; local garage=Runtime.Ensure(profile,false); local garageId=tostring(args.GarageId or garage.ActiveGarageId or ""); local property=garage.Properties[garageId]; local definition=Catalog().ById(garageId); local action=tostring(args.Action or ""); local slotId=tostring(args.SlotId or args.AnchorId or ""); local itemId=tostring(args.ItemId or "")
	if not (property and property.Owned and definition) then return false,"Garage is not owned." end; local slot=DecorationCatalog().ZoneById(slotId,definition.DecorationSlots); if not slot then return false,"Decoration zone is invalid." end; local decorations=DecorationCatalog().Normalize(property.Customisation.Decorations,definition.DecorationSlots); property.Customisation.Decorations=decorations
	if action=="Purchase" or action=="Place" then local item=DecorationCatalog().ById(itemId); if not (item and item.ZoneId==slotId) then return false,"Decoration is not compatible with this zone." end; if not FinishRuntime().IsDecorationAvailable(definition.TemplateId,item) then return false,"Decoration asset is not populated or enabled." end; if action=="Purchase" then if decorations.OwnedItems[itemId] then return false,"Decoration is already owned." end; local cost=math.max(0,math.floor(tonumber(item.Price) or 0)); if (tonumber(profile.Cash) or 0)<cost then return false,"Not enough cash." end; profile.Cash=(tonumber(profile.Cash) or 0)-cost; decorations.OwnedItems[itemId]=true elseif not decorations.OwnedItems[itemId] then return false,"Purchase this decoration first." end; decorations.Placements[slotId]=DecorationCatalog().NewPlacement(itemId)
	elseif action=="Clear" then if slot.Required then return false,"This fixture is required for the garage." end; decorations.Placements[slotId]=nil
	elseif action=="SetFinish" then local placement=decorations.Placements[slotId]; local item=placement and DecorationCatalog().ById(placement.ItemId); if not item then return false,"Place a decoration before customising it." end; local colors=type(args.Colors)=="table" and args.Colors or {}; local valid,message=FinishRuntime().ValidateDecorationFinish(definition.TemplateId,item,colors); if not valid then return false,message end; for channel,value in pairs(colors) do placement.Colors[channel]=DecorationCatalog().EncodeColor(value) end
	else return false,"Unknown decoration action." end; garage.Revision+=1; return true,action=="Clear" and "Decoration removed." or "Decoration updated."
end]==]
	local newDecoration=[==[function Runtime.ConfigureDecoration(profile,args)
	args=type(args)=="table" and args or {}; local garage=Runtime.Ensure(profile,false); local garageId=tostring(args.GarageId or garage.ActiveGarageId or ""); local property=garage.Properties[garageId]; local definition=Catalog().ById(garageId); local action=tostring(args.Action or ""); local slotId=tostring(args.SlotId or args.AnchorId or ""); local itemId=tostring(args.ItemId or "")
	if not (property and property.Owned and definition) then return false,"Garage is not owned." end; local decorations=DecorationCatalog().Normalize(property.Customisation.Decorations,definition.DecorationSlots); property.Customisation.Decorations=decorations
	if action=="SetFinishAll" then local colors=type(args.Colors)=="table" and args.Colors or {}; if next(colors)==nil then return false,"Choose a colour before saving." end; local draft=clone(decorations); local affected=0; for _,slotDefinition in ipairs(definition.DecorationSlots or {}) do local targetSlot=tostring(slotDefinition.SlotId or ""); local placement=draft.Placements[targetSlot]; local item=placement and DecorationCatalog().ById(placement.ItemId); local asset=item and FinishRuntime().DecorationAsset(definition.TemplateId,targetSlot,item.AssetName,item.AssetGroupId or slotDefinition.AssetGroupId); local capability=asset and FinishRuntime().Inspect(asset,"Decoration"); if capability then local targetColors={}; for channel,value in pairs(colors) do if table.find(capability.ColourChannels or {},channel) then targetColors[channel]=value end end; if next(targetColors) then local valid,message=FinishRuntime().ValidateDecorationFinish(definition.TemplateId,item,targetColors); if not valid then return false,message end; for channel,value in pairs(targetColors) do placement.Colors[channel]=DecorationCatalog().EncodeColor(value) end; affected+=1 end end end; if affected==0 then return false,"No installed decoration supports this colour." end; property.Customisation.Decorations=draft; garage.Revision+=1; return true,"Decoration colours updated." end
	local slot=DecorationCatalog().ZoneById(slotId,definition.DecorationSlots); if not slot then return false,"Decoration zone is invalid." end
	if action=="Purchase" or action=="Place" then local item=DecorationCatalog().ById(itemId); if not (item and item.ZoneId==slotId) then return false,"Decoration is not compatible with this zone." end; if not FinishRuntime().IsDecorationAvailable(definition.TemplateId,item) then return false,"Decoration asset is not populated or enabled." end; if action=="Purchase" then if decorations.OwnedItems[itemId] then return false,"Decoration is already owned." end; local cost=math.max(0,math.floor(tonumber(item.Price) or 0)); if (tonumber(profile.Cash) or 0)<cost then return false,"Not enough cash." end; profile.Cash=(tonumber(profile.Cash) or 0)-cost; decorations.OwnedItems[itemId]=true elseif not decorations.OwnedItems[itemId] then return false,"Purchase this decoration first." end; decorations.Placements[slotId]=DecorationCatalog().NewPlacement(itemId)
	elseif action=="Clear" then if slot.Required then return false,"This fixture is required for the garage." end; decorations.Placements[slotId]=nil
	elseif action=="SetFinish" then local placement=decorations.Placements[slotId]; local item=placement and DecorationCatalog().ById(placement.ItemId); if not item then return false,"Place a decoration before customising it." end; local colors=type(args.Colors)=="table" and args.Colors or {}; local valid,message=FinishRuntime().ValidateDecorationFinish(definition.TemplateId,item,colors); if not valid then return false,message end; for channel,value in pairs(colors) do placement.Colors[channel]=DecorationCatalog().EncodeColor(value) end
	else return false,"Unknown decoration action." end; garage.Revision+=1; return true,action=="Clear" and "Decoration removed." or "Decoration updated."
end]==]
	source=replaceOnce(source,oldDecoration,newDecoration,"profile decoration batch")
	compile(source,profile.Name.."_Projected")
	return source
end

projected[owned]=projectOwned(owned.Source)
projected[workspaceController]=projectWorkspace(workspaceController.Source)
projected[shared]=projectShared(shared.Source)
projected[management]=projectManagement(management.Source)
projected[profile]=projectProfile(profile.Source)
assert(projected[owned]:find('Id="__ALL_STRUCTURE"',1,true) and projected[owned]:find('Id="__ALL_DECORATIONS"',1,true),"Bulk style navigation projection missing")
assert(projected[owned]:find('PriceColor=',1,true) and projected[owned]:find('NavigationSave',1,true),"Shop/icon projection missing")
assert(projected[management]:find('PreviewStructureFinishAll',1,true) and projected[management]:find('CancelAllPreviews',1,true),"Batch preview lifecycle projection missing")
assert(not projected[management]:find('runtime:ClearAllChildren()',1,true),"Destructive presentation rebuild survived projection")
assert(projected[profile]:find('action=="SetFinishAll"',1,true),"Atomic bulk finish command projection missing")

local configDefaults={
	Actions={Colour=tostring(replacement:GetAttribute("ModuleColourIcon") or ""),Material=""},
	Navigation={Save=""},
	States={Locked=tostring(replacement:GetAttribute("ModuleLockIcon") or "")},
	StructureLocations={AllStructure=""},
	DecorationLocations={AllDecorations=""},
	Materials={CONCRETE="",METAL="",WOOD="",PAINT="",TILES_A="",TILES_B="",TILES_C="",TILES_D="",TILES_E="",TILES_F=""},
}

local originalSources={}; local originalSourceAttrs={}
for container in pairs(projected) do originalSources[container]=container.Source; originalSourceAttrs[container]={Revision=container:GetAttribute("OwnedGarageStyleUxRevision"),RunId=container:GetAttribute("OwnedGarageStyleUxRunId")} end
local rootAttrs={ContractVersion=icons:GetAttribute("ContractVersion"),Revision=icons:GetAttribute("Revision"),InstallRunId=icons:GetAttribute("InstallRunId"),EditNote=icons:GetAttribute("EditNote")}
local configSnapshots={}
for group,values in pairs(configDefaults) do local folder=icons:FindFirstChild(group); assert(not folder or folder:IsA("Folder"),group.." icon config is not a Folder"); local snapshot={Folder=folder,Values={}}; if folder then for key in pairs(values) do snapshot.Values[key]=folder:GetAttribute(key) end end; configSnapshots[group]=snapshot end
local layoutAttrs={MaterialRailTabClearance=replacement:GetAttribute("MaterialRailTabClearance"),OwnedGarageUnaffordablePriceColor=replacement:GetAttribute("OwnedGarageUnaffordablePriceColor")}

local ok,problem=pcall(function()
	for group,values in pairs(configDefaults) do local folder=icons:FindFirstChild(group); if not folder then folder=Instance.new("Folder"); folder.Name=group; folder.Parent=icons end; for key,value in pairs(values) do if folder:GetAttribute(key)==nil then folder:SetAttribute(key,value) end; assert(type(folder:GetAttribute(key))=="string",group.."."..key.." must be a String attribute") end end
	if replacement:GetAttribute("MaterialRailTabClearance")==nil then replacement:SetAttribute("MaterialRailTabClearance",48) end
	if replacement:GetAttribute("OwnedGarageUnaffordablePriceColor")==nil then replacement:SetAttribute("OwnedGarageUnaffordablePriceColor",Color3.fromRGB(255,75,85)) end
	icons:SetAttribute("ContractVersion",3); icons:SetAttribute("Revision",REVISION); icons:SetAttribute("InstallRunId",RUN_ID); icons:SetAttribute("EditNote","Owned-garage icon folders include Save, Colour, Material, Locked, All locations and one icon per material. Blank values retain documented fallbacks.")
	for container,source in pairs(projected) do if container.Source~=source then container.Source=source end; container:SetAttribute("OwnedGarageStyleUxRevision",REVISION); container:SetAttribute("OwnedGarageStyleUxRunId",RUN_ID); assert(container.Source:find(REVISION,1,true),container.Name.." revision did not persist"); compile(container.Source,container.Name) end
	assert(icons.Actions:GetAttribute("Colour")~=nil and icons.Navigation:GetAttribute("Save")~=nil and icons.Materials:GetAttribute("TILES_F")~=nil,"Style icon configuration did not persist")
end)
if not ok then
	for container,source in pairs(originalSources) do pcall(function() local attrs=originalSourceAttrs[container]; container.Source=source; container:SetAttribute("OwnedGarageStyleUxRevision",attrs.Revision); container:SetAttribute("OwnedGarageStyleUxRunId",attrs.RunId) end) end
	pcall(function()
		for group,values in pairs(configDefaults) do local snapshot=configSnapshots[group]; local folder=icons:FindFirstChild(group); if not snapshot.Folder then if folder then folder:Destroy() end else for key in pairs(values) do snapshot.Folder:SetAttribute(key,snapshot.Values[key]) end end end
		icons:SetAttribute("ContractVersion",rootAttrs.ContractVersion); icons:SetAttribute("Revision",rootAttrs.Revision); icons:SetAttribute("InstallRunId",rootAttrs.InstallRunId); icons:SetAttribute("EditNote",rootAttrs.EditNote)
		replacement:SetAttribute("MaterialRailTabClearance",layoutAttrs.MaterialRailTabClearance); replacement:SetAttribute("OwnedGarageUnaffordablePriceColor",layoutAttrs.OwnedGarageUnaffordablePriceColor)
	end)
	error(TAG.." INSTALL ROLLED BACK: "..tostring(problem))
end

local writes=0; for container,source in pairs(projected) do if originalSources[container]~=source then writes+=1 end end
print(TAG.." PASS sourceWrites="..writes.." iconGroups=12 iconSlots=46 schemaMigration=false remoteAdded=false revision="..REVISION.." runId="..RUN_ID)
print(TAG.." READY: restart Studio, test stable previews, shared shop pricing, bulk Style editing and responsive navigation, then refresh the full mirror.")
