"""Guarded installer for step 4 (coloured veil at the sky change, bluer day, less bloom, stronger far blur) in v3.
Before state: ../backup/after-step3.json and ../step2/after/*.lua (the live sources). Modes: AUDIT, APPLY, ROLLBACK."""
import json
from pathlib import Path
HERE = Path(__file__).resolve().parent
state = json.loads((HERE.parent / 'backup/after-step3.json').read_text(encoding='utf8'))
spec = json.loads((HERE / 'spec.json').read_text(encoding='utf8'))
assert state['place_id'] == 93959280828322 and state['mode'] == 'Edit'
CFG = ['ReplicatedStorage', 'Config', 'World', 'Lighting']
SOURCES = {'LightingCycle': 'ReplicatedStorage.Modules.Game.World.LightingCycle', 'LightingCycleDefinition': 'ReplicatedStorage.Modules.Game.World.LightingCycleDefinition'}
def child(node, name):
    found = [c for c in node['children'] if c['name'] == name]
    assert len(found) == 1, name
    return found[0]
def lua(v):
    if v is None: return 'nil'
    if type(v) is bool: return str(v).lower()
    if type(v) in (int, float): return repr(v)
    if isinstance(v, str):
        return '"' + v.replace('\\', '\\\\').replace('"', '\\"').replace('\r', '\\r').replace('\n', '\\n').replace('\t', '\\t') + '"'
    if isinstance(v, list): return '{' + ','.join(lua(x) for x in v) + '}'
    if v.get('Type') == 'Color3': return 'Color3.new(%r,%r,%r)' % (v['R'], v['G'], v['B'])
    return '{' + ','.join('[%s]=%s' % (lua(k), lua(x)) for k, x in v.items()) + '}'
def same(a, b):
    if a is None or b is None: return a is b
    if isinstance(a, dict) and isinstance(b, dict): return all(abs(a[c] - b[c]) < 1e-4 for c in 'RGB')
    if type(a) in (int, float) and type(b) in (int, float) and type(a) is not bool and type(b) is not bool: return abs(a - b) < 1e-7
    return type(a) == type(b) and a == b
ops, summary = [], {}
for name, path in SOURCES.items():
    before = (HERE.parent / 'step2/after' / (name + '.lua')).read_bytes().decode('utf8')
    after = (HERE / 'after' / (name + '.lua')).read_bytes().decode('utf8')
    assert before != after
    ops.append(dict(kind='source', path=path.split('.'), class_name='ModuleScript', before=before, after=after))
def attribute(path, old, key, value, label, new_ok=False):
    assert new_ok or key in old, label
    prev = old.get(key)
    if isinstance(value, list): value = dict(Type='Color3', R=value[0] / 255, G=value[1] / 255, B=value[2] / 255)
    if prev is not None: assert (type(prev) is bool) == (type(value) is bool) and isinstance(prev, dict) == isinstance(value, dict), label
    if not same(prev, value):
        ops.append(dict(kind='attribute', path=path, class_name='Folder', key=key, before=prev, after=value))
        show = lambda c: [round(c[k] * 255) for k in 'RGB'] if isinstance(c, dict) else c
        summary[label] = [show(prev), show(value)]
presets = child(state['config'], 'ContinuousPresets'); looks = child(state['config'], 'ContinuousLooks')
for look, sections in spec['looks'].items():
    for section, values in sections.items():
        old = child(child(presets, look), section)['attributes']
        for key, value in values.items(): attribute(CFG + ['ContinuousPresets', look, section], old, key, value, '%s.%s.%s' % (look, section, key))
for name, values in spec.get('milestones', {}).items():
    old = child(looks, name)['attributes']
    for key, value in values.items(): attribute(CFG + ['ContinuousLooks', name], old, key, value, 'milestone.%s.%s' % (name, key))
for key, value in spec['config'].items(): attribute(CFG, state['config']['attributes'], key, value, 'config.' + key, new_ok=True)
bundle = dict(placeId=state['place_id'], beforeCapture='scripts/lighting_realism/backup/after-step3.json @ ' + state['taken_utc'], operations=ops, guards=[])
engine = (HERE.parent.parent / 'continuous_lighting/installer_engine.lua').read_text(encoding='utf8')
text = '-- Generated by scripts/lighting_realism/step4/build.py. ROLLBACK restores the state after step 3.\nlocal bundle=' + lua(bundle) + '\nlocal run=(function()\n' + engine + '\nend)()\nreturn function(mode) assert(mode=="AUDIT" or mode=="APPLY" or mode=="ROLLBACK","Use AUDIT, APPLY or ROLLBACK") return run(mode) end\n'
(HERE / 'install.lua').write_text(text, encoding='utf8', newline='\n')
(HERE / 'changes.json').write_text(json.dumps(summary, indent=1) + '\n', encoding='utf8', newline='\n')
print(json.dumps(dict(operations=len(ops), installer_bytes=len(text))))
